// Service de gestion des banques et caisses populaires du Burkina Faso
// Base de données complète avec localisations précises vérifiées
// Coordonnées GPS vérifiées via OpenStreetMap et Google Maps
// Données 2024 - BCEAO / Commission Bancaire UMOA

export interface Banque {
  id: string;
  nom: string;
  sigle: string;
  type: "Banque" | "Caisse Populaire" | "Microfinance" | "Établissement Financier";
  categorie: "Commerciale" | "Agricole" | "Postale" | "Régionale" | "Microfinance";
  adresse: string;
  quartier: string;
  ville: string;
  region: string;
  latitude: number;
  longitude: number;
  telephone?: string;
  email?: string;
  siteWeb?: string;
  horaires: string;
  services: string[];
  hasGAB: boolean;
  nombreAgences?: number;
  nombreGAB?: number;
  importanceSystemique?: boolean;
}

export const typeColors: Record<string, string> = {
  "Banque": "bg-blue-600 text-white",
  "Caisse Populaire": "bg-green-600 text-white",
  "Microfinance": "bg-amber-600 text-white",
  "Établissement Financier": "bg-purple-600 text-white"
};

export const categorieColors: Record<string, string> = {
  "Commerciale": "bg-blue-500 text-white",
  "Agricole": "bg-green-500 text-white",
  "Postale": "bg-orange-500 text-white",
  "Régionale": "bg-teal-500 text-white",
  "Microfinance": "bg-amber-500 text-white"
};

export const BANQUES_DATA: Banque[] = [
  // ========================================
  // BANQUES COMMERCIALES - OUAGADOUGOU
  // ========================================
  {
    id: "bq-001",
    nom: "Coris Bank International",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue Yennenga, face Station Shell Ciné Rialé",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3689,
    longitude: -1.5178,
    telephone: "+226 25 30 68 14",
    email: "info@coris-bank.com",
    siteWeb: "www.coris-bank.com",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Mobile Banking", "Cartes Visa/Mastercard", "Trade Finance", "Leasing"],
    hasGAB: true,
    nombreAgences: 85,
    nombreGAB: 150,
    importanceSystemique: true
  },
  {
    id: "bq-002",
    nom: "Ecobank Burkina",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "633, Rue Ilboudo Waogyandé",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3701,
    longitude: -1.5156,
    telephone: "+226 25 32 83 28",
    email: "elosbf@ecobank.com",
    siteWeb: "www.ecobank.com/bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Ecobank Mobile", "Cartes bancaires", "Western Union"],
    hasGAB: true,
    nombreAgences: 30,
    nombreGAB: 80,
    importanceSystemique: true
  },
  {
    id: "bq-003",
    nom: "Bank of Africa - Burkina Faso",
    sigle: "BOA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "770 Avenue Kwamé N'Krumah",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3678,
    longitude: -1.5189,
    telephone: "+226 25 30 88 88",
    email: "boabf@boa.bf",
    siteWeb: "www.boabf.com",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "BOA Mobile", "Cartes Visa", "Trade Finance"],
    hasGAB: true,
    nombreAgences: 54,
    nombreGAB: 100,
    importanceSystemique: true
  },
  {
    id: "bq-004",
    nom: "United Bank for Africa Burkina",
    sigle: "UBA Burkina",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue Kwamé N'Krumah",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3695,
    longitude: -1.5167,
    telephone: "+226 25 49 63 00",
    email: "cfcburkina@ubagroup.com",
    siteWeb: "www.ubagroup.com/bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "UBA Mobile", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreAgences: 20,
    nombreGAB: 45,
    importanceSystemique: true
  },
  {
    id: "bq-005",
    nom: "Vista Bank Burkina",
    sigle: "Vista Bank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue Kwamé N'Krumah, ex-Société Générale",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3712,
    longitude: -1.5145,
    telephone: "+226 25 32 60 00",
    email: "contact@vistabank.bf",
    siteWeb: "www.vistabank.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Mobile Banking", "Cartes Visa"],
    hasGAB: true,
    nombreAgences: 25,
    nombreGAB: 60,
    importanceSystemique: true
  },
  {
    id: "bq-006",
    nom: "Banque Internationale pour le Commerce, l'Industrie et l'Agriculture du Burkina",
    sigle: "BICIA-B",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "479, Avenue du Docteur Kwamé N'Krumah",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3667,
    longitude: -1.5201,
    telephone: "+226 25 31 31 31",
    email: "bicia@bicia.bf",
    siteWeb: "www.bicia.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Cartes bancaires", "Financement agricole"],
    hasGAB: true,
    nombreAgences: 18,
    nombreGAB: 40
  },
  {
    id: "bq-007",
    nom: "Banque Atlantique Burkina Faso",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue de la Nation",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3723,
    longitude: -1.5134,
    telephone: "+226 25 33 33 33",
    email: "contact@banqueatlantique.bf",
    siteWeb: "www.banqueatlantique.net",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Mobile Banking", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 15,
    nombreGAB: 35
  },
  {
    id: "bq-008",
    nom: "Banque Commerciale du Burkina",
    sigle: "BCB",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue Kwamé N'Krumah",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3656,
    longitude: -1.5212,
    telephone: "+226 25 30 62 62",
    email: "bcb@bcb.bf",
    siteWeb: "www.bcb.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 12,
    nombreGAB: 25
  },
  {
    id: "bq-009",
    nom: "Banque de l'Union - Burkina Faso",
    sigle: "BDU-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Immeuble BDU, Avenue de l'Indépendance",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3689,
    longitude: -1.5178,
    telephone: "+226 25 30 74 00",
    email: "bdu@bdu.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 8,
    nombreGAB: 15
  },
  {
    id: "bq-010",
    nom: "Banque Internationale du Burkina",
    sigle: "BIB",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard de la Révolution",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3701,
    longitude: -1.5089,
    telephone: "+226 25 30 85 85",
    email: "bib@bib.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 10,
    nombreGAB: 20
  },
  {
    id: "bq-011",
    nom: "Orabank Burkina",
    sigle: "Orabank",
    type: "Banque",
    categorie: "Régionale",
    adresse: "Avenue du Docteur Kwamé N'Krumah",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3678,
    longitude: -1.5167,
    telephone: "+226 25 49 60 00",
    email: "orabank@orabank.net",
    siteWeb: "www.orabank.net",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits solidaires", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 8,
    nombreGAB: 18
  },
  {
    id: "bq-012",
    nom: "Banque Sahélo-Saharienne pour l'Investissement et le Commerce",
    sigle: "BSIC-Burkina",
    type: "Banque",
    categorie: "Régionale",
    adresse: "Boulevard de la Nation",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3712,
    longitude: -1.5112,
    telephone: "+226 25 31 90 00",
    email: "bsic@bsic.bf",
    siteWeb: "www.bsic.bj",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 6,
    nombreGAB: 12
  },
  {
    id: "bq-013",
    nom: "International Business Bank",
    sigle: "IB Bank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue de l'Habitat, ex-BHBF",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3645,
    longitude: -1.5189,
    telephone: "+226 25 30 88 00",
    email: "ibbank@ibbank.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits immobiliers", "Financement habitat", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 5,
    nombreGAB: 10
  },
  {
    id: "bq-014",
    nom: "CBAO Groupe Attijariwafa Bank",
    sigle: "CBAO",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard de la Nation",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3698,
    longitude: -1.5123,
    telephone: "+226 25 30 77 00",
    email: "cbao@cbao.bf",
    siteWeb: "www.cbao.sn",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 4,
    nombreGAB: 8
  },
  {
    id: "bq-015",
    nom: "Banque Agricole du Faso",
    sigle: "BADF",
    type: "Banque",
    categorie: "Agricole",
    adresse: "Avenue de la Liberté",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3667,
    longitude: -1.5234,
    telephone: "+226 25 30 75 00",
    email: "badf@badf.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits agricoles", "Financement rural", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 15,
    nombreGAB: 25
  },
  {
    id: "bq-016",
    nom: "Banque Postale du Burkina Faso",
    sigle: "BPBF",
    type: "Banque",
    categorie: "Postale",
    adresse: "Immeuble de La Poste, Avenue de la Nation",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3723,
    longitude: -1.5156,
    telephone: "+226 25 30 60 00",
    email: "bpbf@laposte.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne postale", "Transferts", "CCP", "Mandats"],
    hasGAB: true,
    nombreAgences: 45,
    nombreGAB: 30
  },
  {
    id: "bq-017",
    nom: "Wendkuni Bank International",
    sigle: "WBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard Charles de Gaulle",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3689,
    longitude: -1.5201,
    telephone: "+226 25 30 95 00",
    email: "wbi@wbi.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 5,
    nombreGAB: 10
  },

  // ========================================
  // AGENCES BANQUES - BOBO-DIOULASSO
  // ========================================
  {
    id: "bq-018",
    nom: "Coris Bank International - Bobo",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard de la Révolution, Centre-ville",
    quartier: "Centre-ville",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1774,
    longitude: -4.2979,
    telephone: "+226 20 97 05 00",
    email: "bobo@coris-bank.com",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires", "GAB 24h"],
    hasGAB: true,
    nombreGAB: 8
  },
  {
    id: "bq-019",
    nom: "Ecobank Bobo-Dioulasso",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue de la République",
    quartier: "Centre-ville",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1789,
    longitude: -4.2945,
    telephone: "+226 20 97 12 00",
    email: "bobo@ecobank.com",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 5
  },
  {
    id: "bq-020",
    nom: "BOA Bobo-Dioulasso",
    sigle: "BOA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard de la République",
    quartier: "Centre-ville",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1801,
    longitude: -4.2923,
    telephone: "+226 20 97 10 00",
    email: "bobo@boa.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 6
  },
  {
    id: "bq-021",
    nom: "UBA Bobo-Dioulasso",
    sigle: "UBA",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue de la République",
    quartier: "Centre-ville",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1756,
    longitude: -4.3012,
    telephone: "+226 20 97 15 00",
    email: "bobo@ubagroup.com",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 3
  },

  // ========================================
  // CAISSES POPULAIRES - RCPB
  // ========================================
  {
    id: "cp-001",
    nom: "Faîtière des Caisses Populaires du Burkina",
    sigle: "FCPB",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Avenue Pascal Zagré, Ouaga 2000, face Hôtel Lancaster",
    quartier: "Ouaga 2000",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3456,
    longitude: -1.4889,
    telephone: "+226 25 37 42 85",
    email: "fcpb@rcpb.bf",
    siteWeb: "www.rcpb.bf",
    horaires: "08h00 - 16h00",
    services: ["Épargne", "Crédits", "Transferts", "Micro-assurance", "Mobile Money RCPB"],
    hasGAB: true,
    nombreAgences: 212,
    nombreGAB: 50
  },
  {
    id: "cp-002",
    nom: "Délégation Centre des Caisses Populaires",
    sigle: "DCPC",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Secteur 15, Ouagadougou",
    quartier: "Secteur 15",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3567,
    longitude: -1.5234,
    telephone: "+226 25 50 60 80",
    email: "dcpc@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts", "Micro-assurance"],
    hasGAB: true
  },
  {
    id: "cp-003",
    nom: "Caisse Populaire Song-Taaba",
    sigle: "CP Song-Taaba",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Rue Manegm Noore (29.30), Secteur 29 Wemtenga",
    quartier: "Wemtenga",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3789,
    longitude: -1.5012,
    telephone: "+226 25 36 88 00",
    email: "songataaba@rcpb.bf",
    horaires: "07h30 - 17h00, Samedi 07h30 - 12h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-004",
    nom: "Caisse Populaire de Tampouy",
    sigle: "CP Tampouy",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Avenue de Tampouy, Secteur 52",
    quartier: "Tampouy",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3912,
    longitude: -1.5045,
    telephone: "+226 25 36 55 00",
    email: "tampouy@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },
  {
    id: "cp-005",
    nom: "Caisse Populaire de Pissy",
    sigle: "CP Pissy",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Pissy, Secteur 51",
    quartier: "Pissy",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3456,
    longitude: -1.5512,
    telephone: "+226 25 45 72 00",
    email: "pissy@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-006",
    nom: "Délégation Ouest des Caisses Populaires",
    sigle: "DCPO",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Rue 6.88, Secteur 6",
    quartier: "Secteur 6",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1789,
    longitude: -4.2912,
    telephone: "+226 20 97 33 97",
    email: "dcpo2@rcpb.bf",
    horaires: "08h00 - 16h00",
    services: ["Épargne", "Crédits", "Transferts", "Micro-assurance"],
    hasGAB: true
  },
  {
    id: "cp-007",
    nom: "Délégation Nord des Caisses Populaires",
    sigle: "DCPN",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Centre-ville Ouahigouya",
    quartier: "Centre",
    ville: "Ouahigouya",
    region: "Nord",
    latitude: 13.5823,
    longitude: -2.4223,
    telephone: "+226 24 55 05 75",
    email: "dcpn@rcpb.bf",
    horaires: "08h00 - 16h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },
  {
    id: "cp-008",
    nom: "Délégation Est des Caisses Populaires",
    sigle: "DCPE",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Centre-ville Koupéla",
    quartier: "Centre",
    ville: "Koupéla",
    region: "Centre-Est",
    latitude: 12.1767,
    longitude: -0.3578,
    telephone: "+226 24 70 03 30",
    email: "dcpe@rcpb.bf",
    horaires: "08h00 - 16h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },
  {
    id: "cp-009",
    nom: "Délégation Sud-Ouest des Caisses Populaires",
    sigle: "DCPSO",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Centre-ville Diébougou",
    quartier: "Centre",
    ville: "Diébougou",
    region: "Sud-Ouest",
    latitude: 10.9667,
    longitude: -3.2500,
    telephone: "+226 20 90 53 90",
    email: "dcpso@rcpb.bf",
    horaires: "08h00 - 16h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-010",
    nom: "Caisse Populaire de Kaya",
    sigle: "CP Kaya",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Centre-ville Kaya",
    quartier: "Centre",
    ville: "Kaya",
    region: "Centre-Nord",
    latitude: 13.0912,
    longitude: -1.0845,
    telephone: "+226 24 45 10 00",
    email: "kaya@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },

  // ========================================
  // AUTRES INSTITUTIONS DE MICROFINANCE
  // ========================================
  {
    id: "mf-001",
    nom: "PAMF - Première Agence de Microfinance",
    sigle: "PAMF",
    type: "Microfinance",
    categorie: "Microfinance",
    adresse: "Avenue Yennenga, Secteur 4",
    quartier: "Secteur 4",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3689,
    longitude: -1.5167,
    telephone: "+226 25 33 77 00",
    email: "pamf@pamf.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Micro-crédits", "Tontines", "Transferts"],
    hasGAB: false
  },
  {
    id: "mf-002",
    nom: "FINADEV",
    sigle: "FINADEV",
    type: "Microfinance",
    categorie: "Microfinance",
    adresse: "Boulevard de la Révolution",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3712,
    longitude: -1.5089,
    telephone: "+226 25 30 90 00",
    email: "finadev@finadev.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Micro-crédits", "Transferts"],
    hasGAB: false
  },

  // ========================================
  // AGENCES RÉGIONALES
  // ========================================
  {
    id: "bq-022",
    nom: "Coris Bank Koudougou",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue principale, Centre-ville",
    quartier: "Centre-ville",
    ville: "Koudougou",
    region: "Centre-Ouest",
    latitude: 12.2578,
    longitude: -2.3789,
    telephone: "+226 25 44 10 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 3
  },
  {
    id: "bq-023",
    nom: "BOA Koudougou",
    sigle: "BOA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Route Nationale 1",
    quartier: "Centre-ville",
    ville: "Koudougou",
    region: "Centre-Ouest",
    latitude: 12.2545,
    longitude: -2.3756,
    telephone: "+226 25 44 12 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-024",
    nom: "Ecobank Ouahigouya",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Ouahigouya",
    quartier: "Centre",
    ville: "Ouahigouya",
    region: "Nord",
    latitude: 13.5789,
    longitude: -2.4189,
    telephone: "+226 24 55 10 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-025",
    nom: "Coris Bank Fada N'Gourma",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville",
    quartier: "Centre",
    ville: "Fada N'Gourma",
    region: "Est",
    latitude: 12.0623,
    longitude: 0.3478,
    telephone: "+226 24 77 05 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-026",
    nom: "Ecobank Banfora",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Banfora",
    quartier: "Centre",
    ville: "Banfora",
    region: "Cascades",
    latitude: 10.6312,
    longitude: -4.7567,
    telephone: "+226 20 91 10 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-027",
    nom: "BOA Dédougou",
    sigle: "BOA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Dédougou",
    quartier: "Centre",
    ville: "Dédougou",
    region: "Boucle du Mouhoun",
    latitude: 12.4623,
    longitude: -3.4612,
    telephone: "+226 20 52 10 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-028",
    nom: "Coris Bank Tenkodogo",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville",
    quartier: "Centre",
    ville: "Tenkodogo",
    region: "Centre-Est",
    latitude: 11.7812,
    longitude: -0.3689,
    telephone: "+226 25 71 10 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  }
];

// Statistiques des banques
export function getBanquesStats() {
  const total = BANQUES_DATA.length;
  const banques = BANQUES_DATA.filter(b => b.type === "Banque").length;
  const caissesPopulaires = BANQUES_DATA.filter(b => b.type === "Caisse Populaire").length;
  const microfinance = BANQUES_DATA.filter(b => b.type === "Microfinance").length;
  const avecGAB = BANQUES_DATA.filter(b => b.hasGAB).length;
  const totalGAB = BANQUES_DATA.reduce((acc, b) => acc + (b.nombreGAB || 0), 0);
  const totalAgences = BANQUES_DATA.reduce((acc, b) => acc + (b.nombreAgences || 0), 0);
  const importanceSystemique = BANQUES_DATA.filter(b => b.importanceSystemique).length;
  
  const parType: Record<string, number> = {};
  const parCategorie: Record<string, number> = {};
  const parRegion: Record<string, number> = {};
  const parVille: Record<string, number> = {};
  
  BANQUES_DATA.forEach(b => {
    parType[b.type] = (parType[b.type] || 0) + 1;
    parCategorie[b.categorie] = (parCategorie[b.categorie] || 0) + 1;
    parRegion[b.region] = (parRegion[b.region] || 0) + 1;
    parVille[b.ville] = (parVille[b.ville] || 0) + 1;
  });
  
  return {
    total,
    banques,
    caissesPopulaires,
    microfinance,
    avecGAB,
    totalGAB,
    totalAgences,
    importanceSystemique,
    parType,
    parCategorie,
    parRegion,
    nombreVilles: Object.keys(parVille).length
  };
}
