export interface Ministere {
  id: string;
  nom: string;
  nomCourt: string;
  ministre: string;
  rang: "Presidence" | "Primature" | "Ministre d'Etat" | "Ministre" | "Ministre Delegue";
  domaines: string[];
  adresse: string;
  quartier: string;
  ville: string;
  telephone?: string;
  telephoneSecondaire?: string;
  email?: string;
  website?: string;
  bp?: string;
  horaires: string;
  latitude: number;
  longitude: number;
  porteparole?: boolean;
  gardeDesSceaux?: boolean;
  attributions: string[];
  titreComplet?: string;
  dateNomination?: string;
  biographie?: string[];
  reseauxSociaux?: { plateforme: string; url: string }[];
  servicesRattaches?: string[];
}

export const PRESIDENCE_PRIMATURE: Ministere[] = [
  {
    id: "presidence-du-faso",
    nom: "Presidence du Faso",
    nomCourt: "Presidence",
    ministre: "Capitaine Ibrahim TRAORE",
    rang: "Presidence",
    titreComplet: "President du Faso, Chef de l'Etat, Chef Supreme des Forces Armees Nationales",
    dateNomination: "21 octobre 2022",
    domaines: ["Chef de l'Etat", "Defense nationale", "Politique etrangere", "Unite nationale", "Transition"],
    adresse: "Palais de Kosyam, Avenue Charles de Gaulle",
    quartier: "Ouaga 2000",
    ville: "Ouagadougou",
    telephone: "+226 25 30 66 30",
    telephoneSecondaire: "+226 25 30 66 31",
    email: "contact@presidencedufaso.bf",
    website: "https://www.presidencedufaso.bf",
    bp: "BP 03 Ouagadougou 03",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3433,
    longitude: -1.5094,
    biographie: [
      "Ne le 1er octobre 1988 a Tambarga (province de la Kompienga)",
      "Capitaine de l'Armee de terre du Burkina Faso",
      "Formation a l'Academie militaire Georges Namoano de Po",
      "Artilleur de formation, officier des Forces speciales",
      "Chef de l'Etat depuis le 30 septembre 2022",
      "Plus jeune chef d'Etat au monde lors de sa prise de fonction (34 ans)",
      "Prestation de serment le 21 octobre 2022 devant le Conseil constitutionnel"
    ],
    reseauxSociaux: [
      { plateforme: "Twitter/X", url: "https://x.com/presidencebf" },
      { plateforme: "Twitter/X Personnel", url: "https://x.com/CapitaineIb226" },
      { plateforme: "Instagram", url: "https://www.instagram.com/president_ibrahim_traore/" },
      { plateforme: "Facebook", url: "https://www.facebook.com/PresidenceBF" },
      { plateforme: "YouTube", url: "https://www.youtube.com/@presidencedufaso" }
    ],
    servicesRattaches: [
      "Secretariat general de la Presidence du Faso",
      "Cabinet civil du President du Faso",
      "Cabinet militaire du President du Faso",
      "Etat-Major particulier du President du Faso",
      "Direction de la Communication presidentielle",
      "Conseil superieur de la Defense nationale",
      "Haut Conseil pour la Reconciliation et l'Unite nationale",
      "Conseil economique et social",
      "Conseil constitutionnel",
      "Comite national de la Transition",
      "Mediateur du Faso",
      "Commission electorale nationale independante (CENI)",
      "Autorite superieure de controle d'Etat et de lutte contre la corruption (ASCE-LC)"
    ],
    attributions: [
      "Chef de l'Etat et garant de l'unite nationale",
      "Chef Supreme des Forces Armees Nationales",
      "Conduite de la Transition",
      "Politique de defense et de securite",
      "Politique etrangere et cooperation internationale",
      "Nomination aux hautes fonctions civiles et militaires",
      "Presidence du Conseil des ministres",
      "Promulgation des lois",
      "Droit de grace",
      "Accreditation des ambassadeurs",
      "Garant de l'independance de la justice"
    ]
  },
  {
    id: "primature",
    nom: "Primature du Burkina Faso",
    nomCourt: "Primature",
    ministre: "Rimtalba Jean Emmanuel OUEDRAOGO",
    rang: "Primature",
    titreComplet: "Premier Ministre, Chef du Gouvernement",
    dateNomination: "7 decembre 2024",
    domaines: ["Chef du Gouvernement", "Coordination gouvernementale", "Politique generale", "Action gouvernementale"],
    adresse: "Avenue de l'Independance",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 32 48 89",
    telephoneSecondaire: "+226 25 33 62 65",
    email: "contact@primature.gov.bf",
    website: "https://primature.gov.bf",
    bp: "BP 7027 Ouagadougou 03",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3686,
    longitude: -1.5246,
    porteparole: false,
    biographie: [
      "Ne le 26 decembre 1980",
      "Journaliste et homme de medias de formation",
      "Diplome en Sciences et Techniques de l'Information et de la Communication (CSTIC cycle A)",
      "Licence en Sociologie rurale et sociologie du developpement",
      "Master en mediation et gestion des conflits (Universite de Ouagadougou)",
      "Ex-Directeur de la Television nationale du Burkina (RTB)",
      "Ex-Redacteur en chef de la Television du Burkina (2016-2021)",
      "Ex-Ministre d'Etat en charge de la Communication, de la Culture, des Arts et du Tourisme (2022-2024)",
      "Ex-Porte-parole du Gouvernement (2022-2024)",
      "Animateur des emissions: Sur la Breche, Techno Inno, Zoommine, Vision environnement",
      "Nomme Premier Ministre le 7 decembre 2024"
    ],
    reseauxSociaux: [
      { plateforme: "Site officiel", url: "https://primature.gov.bf" },
      { plateforme: "Gouvernement", url: "https://gouvernement.gov.bf" }
    ],
    servicesRattaches: [
      "Secretariat general du Gouvernement et du Conseil des ministres",
      "Cabinet du Premier Ministre",
      "Direction generale des etudes et des statistiques sectorielles",
      "Service d'information du Gouvernement (SIG)",
      "Autorite de regulation des communications electroniques et des postes (ARCEP)",
      "Commission de l'informatique et des libertes (CIL)",
      "Conseil national de lutte contre le SIDA (CNLS)",
      "Coordination nationale de lutte contre la fraude",
      "Comite national de pilotage du Plan national de developpement economique et social (PNDES II)"
    ],
    attributions: [
      "Chef du Gouvernement",
      "Coordination de l'action gouvernementale",
      "Execution de la politique de la Nation",
      "Direction de l'administration publique",
      "Application des lois et reglements",
      "Presidence du Conseil de cabinet",
      "Proposition de nomination des membres du Gouvernement",
      "Convocation des reunions interministerielles",
      "Suivi de l'execution des decisions du Conseil des ministres",
      "Relations avec les institutions de la Republique"
    ]
  }
];

export const MINISTERES: Ministere[] = [
  {
    id: "min-guerre-defense",
    nom: "Ministere de la Guerre et de la Defense patriotique",
    nomCourt: "Guerre & Defense",
    ministre: "General de Division Celestin SIMPORE",
    rang: "Ministre d'Etat",
    domaines: ["Defense", "Securite nationale", "Armee"],
    adresse: "Boulevard de la Revolution",
    quartier: "Koulouba",
    ville: "Ouagadougou",
    telephone: "+226 25 30 72 52",
    website: "https://www.defense.gov.bf",
    bp: "BP 496 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3780,
    longitude: -1.5170,
    attributions: ["Defense nationale", "Forces armees", "Anciens combattants", "Service militaire", "Gendarmerie nationale", "Cooperation militaire"]
  },
  {
    id: "min-agriculture",
    nom: "Ministere de l'Agriculture, de l'Eau, des Ressources animales et halieutiques",
    nomCourt: "Agriculture & Elevage",
    ministre: "Commandant Ismael SOMBIE",
    rang: "Ministre d'Etat",
    domaines: ["Agriculture", "Elevage", "Peche", "Eau"],
    adresse: "Rue Agostino Neto",
    quartier: "Koulouba",
    ville: "Ouagadougou",
    telephone: "+226 25 32 41 12",
    telephoneSecondaire: "+226 25 32 41 14",
    email: "sg@agriculture.gov.bf",
    website: "https://www.agriculture.gov.bf",
    bp: "BP 7005 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3750,
    longitude: -1.5200,
    attributions: ["Politique agricole", "Securite alimentaire", "Ressources animales", "Peche et aquaculture", "Hydraulique agricole", "Foncier rural"]
  },
  {
    id: "min-admin-territoriale",
    nom: "Ministere de l'Administration territoriale et de la Mobilite",
    nomCourt: "Administration territoriale",
    ministre: "Emile ZERBO",
    rang: "Ministre d'Etat",
    domaines: ["Administration", "Decentralisation", "Mobilite"],
    adresse: "Avenue de l'Independance",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 32 48 42",
    email: "sg@matd.gov.bf",
    website: "https://www.matd.gov.bf",
    bp: "BP 7034 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3700,
    longitude: -1.5190,
    attributions: ["Administration du territoire", "Decentralisation", "Collectivites territoriales", "Etat civil", "Mobilite des personnes", "Securite interieure"]
  },
  {
    id: "min-communication",
    nom: "Ministere de la Communication, de la Culture, des Arts et du Tourisme",
    nomCourt: "Communication & Culture",
    ministre: "Pingdwende Gilbert OUEDRAOGO",
    rang: "Ministre",
    domaines: ["Communication", "Culture", "Arts", "Tourisme"],
    adresse: "Avenue de la Liberte",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 32 63 04",
    telephoneSecondaire: "+226 25 33 09 64",
    email: "contact@communication.gov.bf",
    website: "https://www.communication.gov.bf",
    bp: "BP 7045 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3710,
    longitude: -1.5230,
    porteparole: true,
    attributions: ["Presse et medias", "Patrimoine culturel", "Promotion des arts", "Tourisme", "Cinema", "Porte-parole du Gouvernement"]
  },
  {
    id: "min-economie-finances",
    nom: "Ministere de l'Economie et des Finances",
    nomCourt: "Economie & Finances",
    ministre: "Aboubakar NACANABO",
    rang: "Ministre",
    domaines: ["Economie", "Finances", "Budget"],
    adresse: "Avenue d'Oubritenga",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 32 42 05",
    telephoneSecondaire: "+226 25 31 27 15",
    email: "sg@finances.gov.bf",
    website: "https://www.finances.gov.bf",
    bp: "BP 7012 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3685,
    longitude: -1.5205,
    attributions: ["Politique economique", "Budget de l'Etat", "Fiscalite", "Douanes", "Tresor public", "Planification economique"]
  },
  {
    id: "min-securite",
    nom: "Ministere de la Securite",
    nomCourt: "Securite",
    ministre: "Commissaire divisionnaire Mahamadou SANA",
    rang: "Ministre",
    domaines: ["Securite", "Police", "Protection civile"],
    adresse: "Avenue de l'Independance",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 31 68 91",
    email: "infos@securite.gov.bf",
    website: "https://www.securite.gov.bf",
    bp: "BP 01 BP 6466 Ouagadougou 01",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3695,
    longitude: -1.5215,
    attributions: ["Police nationale", "Protection civile", "Securite publique", "Lutte contre la criminalite", "Sapeurs-pompiers", "Securite routiere"]
  },
  {
    id: "min-affaires-etrangeres",
    nom: "Ministere des Affaires etrangeres, de la Cooperation regionale et des Burkinabe de l'exterieur",
    nomCourt: "Affaires etrangeres",
    ministre: "Karamoko Jean-Marie TRAORE",
    rang: "Ministre",
    domaines: ["Diplomatie", "Cooperation", "Diaspora"],
    adresse: "Avenue du Burkina",
    quartier: "Koulouba",
    ville: "Ouagadougou",
    telephone: "+226 25 32 47 33",
    telephoneSecondaire: "+226 25 32 47 37",
    email: "mae@diplomatie.gov.bf",
    website: "https://www.mae.gov.bf",
    bp: "BP 03 BP 7038 Ouagadougou 03",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3740,
    longitude: -1.5180,
    attributions: ["Relations diplomatiques", "Cooperation internationale", "Burkinabe de l'exterieur", "Organisations internationales", "Traites et conventions", "Cooperation regionale"]
  },
  {
    id: "min-justice",
    nom: "Ministere de la Justice et des Droits humains",
    nomCourt: "Justice",
    ministre: "Edasso Rodrigue BAYALA",
    rang: "Ministre",
    domaines: ["Justice", "Droits humains", "Legislation"],
    adresse: "Avenue de l'Independance",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 32 48 33",
    email: "sg@justice.gov.bf",
    website: "https://www.justice.gov.bf",
    bp: "BP 526 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3670,
    longitude: -1.5195,
    gardeDesSceaux: true,
    attributions: ["Organisation judiciaire", "Droits humains", "Legislation", "Administration penitentiaire", "Acces a la justice", "Garde des Sceaux"]
  },
  {
    id: "min-famille-solidarite",
    nom: "Ministere de la Famille et de la Solidarite",
    nomCourt: "Famille & Solidarite",
    ministre: "Lieutenant-Colonel Passowendee Pelagie KABRE/KABORE",
    rang: "Ministre",
    domaines: ["Famille", "Solidarite", "Protection sociale"],
    adresse: "Avenue du Tresor",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 30 68 29",
    email: "sg@famille.gov.bf",
    website: "https://www.action-sociale.gov.bf",
    bp: "BP 515 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3660,
    longitude: -1.5210,
    attributions: ["Protection de la famille", "Solidarite nationale", "Protection sociale", "Genre et promotion de la femme", "Protection de l'enfant", "Personnes agees"]
  },
  {
    id: "min-sante",
    nom: "Ministere de la Sante et de l'Hygiene publique",
    nomCourt: "Sante",
    ministre: "Robert Lucien Jean-Claude KARGOUGOU",
    rang: "Ministre",
    domaines: ["Sante", "Hygiene publique", "Hopitaux"],
    adresse: "Avenue de l'Independance",
    quartier: "Paspanga",
    ville: "Ouagadougou",
    telephone: "+226 25 32 63 81",
    telephoneSecondaire: "+226 25 32 63 82",
    email: "sg@sante.gov.bf",
    website: "https://www.sante.gov.bf",
    bp: "BP 7009 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3720,
    longitude: -1.5160,
    attributions: ["Politique sanitaire", "Hopitaux publics", "Hygiene publique", "Pharmacie et medicaments", "Prevention epidemies", "Sante maternelle et infantile"]
  },
  {
    id: "min-transition-digitale",
    nom: "Ministere de la Transition digitale, des Postes et des Communications electroniques",
    nomCourt: "Transition digitale",
    ministre: "Aminata ZERBO-SABANE",
    rang: "Ministre",
    domaines: ["Numerique", "Postes", "Telecommunications"],
    adresse: "Avenue de la Nation",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 49 00 02",
    telephoneSecondaire: "+226 25 49 00 04",
    email: "secretariat.mdenp@tic.gov.bf",
    website: "https://www.mdenp.gov.bf",
    bp: "BP 7048 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3730,
    longitude: -1.5220,
    attributions: ["Transformation digitale", "Postes", "Telecommunications", "Economie numerique", "Cybersecurite", "E-gouvernement"]
  },
  {
    id: "min-industrie-commerce",
    nom: "Ministere du Developpement industriel, du Commerce, de l'Artisanat et des PME",
    nomCourt: "Industrie & Commerce",
    ministre: "Serge Gnaniodem PODA",
    rang: "Ministre",
    domaines: ["Industrie", "Commerce", "Artisanat", "PME"],
    adresse: "Rue Joseph Badoua",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 32 48 15",
    email: "sg@commerce.gov.bf",
    website: "https://www.commerce.gov.bf",
    bp: "BP 365 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3690,
    longitude: -1.5175,
    attributions: ["Developpement industriel", "Commerce interieur et exterieur", "Artisanat", "PME/PMI", "Concurrence et prix", "Normalisation"]
  },
  {
    id: "min-energie-mines",
    nom: "Ministere de l'Energie, des Mines et des Carrieres",
    nomCourt: "Energie & Mines",
    ministre: "Yacouba Zabre GOUBA",
    rang: "Ministre",
    domaines: ["Energie", "Mines", "Carrieres"],
    adresse: "Rue de la Chance",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 31 84 29",
    email: "sg@energie.gov.bf",
    website: "https://www.mines.gov.bf",
    bp: "BP 7016 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3675,
    longitude: -1.5185,
    attributions: ["Politique energetique", "Exploitation miniere", "Energies renouvelables", "Carrieres", "Hydrocarbures", "Electrification rurale"]
  },
  {
    id: "min-enseignement-base",
    nom: "Ministere de l'Enseignement de base, de l'Alphabetisation et de la Promotion des Langues nationales",
    nomCourt: "Enseignement de base",
    ministre: "Jacques Sosthene DINGARA",
    rang: "Ministre",
    domaines: ["Education primaire", "Alphabetisation", "Langues nationales"],
    adresse: "Avenue de l'UEMOA",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 30 66 09",
    telephoneSecondaire: "+226 25 30 66 10",
    email: "sg@education.gov.bf",
    website: "https://www.education.gov.bf",
    bp: "BP 7032 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3650,
    longitude: -1.5240,
    attributions: ["Enseignement primaire", "Prescolaire", "Alphabetisation", "Promotion des langues nationales", "Manuels scolaires", "Formation des enseignants"]
  },
  {
    id: "min-enseignement-secondaire",
    nom: "Ministere de l'Enseignement secondaire, de la Formation professionnelle et Technique",
    nomCourt: "Enseignement secondaire",
    ministre: "Boubakar SAVADOGO",
    rang: "Ministre",
    domaines: ["Education secondaire", "Formation professionnelle"],
    adresse: "Avenue du Dr Kwame N'Krumah",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 32 45 60",
    email: "sg@secondaire.gov.bf",
    website: "https://www.messrs.gov.bf",
    bp: "BP 7047 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3640,
    longitude: -1.5200,
    attributions: ["Enseignement secondaire", "Formation professionnelle", "Formation technique", "Examens et concours", "Lycees et colleges", "Orientation scolaire"]
  },
  {
    id: "min-enseignement-superieur",
    nom: "Ministere de l'Enseignement superieur, de la Recherche et de l'Innovation",
    nomCourt: "Enseignement superieur",
    ministre: "Ardjouma THIOMBIANO",
    rang: "Ministre",
    domaines: ["Universite", "Recherche", "Innovation"],
    adresse: "Avenue Charles de Gaulle",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 32 45 48",
    telephoneSecondaire: "+226 25 32 45 49",
    email: "sg@recherche.gov.bf",
    website: "https://www.mesri.gov.bf",
    bp: "BP 7047 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3655,
    longitude: -1.5225,
    attributions: ["Universites publiques", "Recherche scientifique", "Innovation technologique", "Bourses d'etudes", "Cooperation universitaire", "Grandes ecoles"]
  },
  {
    id: "min-environnement",
    nom: "Ministere de l'Environnement, de l'Eau et de l'Assainissement",
    nomCourt: "Environnement & Eau",
    ministre: "Roger BARRO",
    rang: "Ministre",
    domaines: ["Environnement", "Eau", "Assainissement"],
    adresse: "Avenue Pascal Zagre",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 32 40 74",
    email: "sg@environnement.gov.bf",
    website: "https://www.environnement.gov.bf",
    bp: "BP 7044 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3635,
    longitude: -1.5180,
    attributions: ["Protection de l'environnement", "Gestion des eaux", "Assainissement", "Changements climatiques", "Forets et faune", "Developpement durable"]
  },
  {
    id: "min-urbanisme",
    nom: "Ministere de l'Urbanisme et de l'Habitat",
    nomCourt: "Urbanisme & Habitat",
    ministre: "Mikailou SIDIBE",
    rang: "Ministre",
    domaines: ["Urbanisme", "Habitat", "Logement"],
    adresse: "Avenue d'Oubritenga",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 32 63 03",
    email: "sg@urbanisme.gov.bf",
    website: "https://www.urbanisme.gov.bf",
    bp: "BP 153 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3645,
    longitude: -1.5165,
    attributions: ["Urbanisme et amenagement", "Habitat social", "Logement", "Construction", "Cadastre et domaine foncier", "Permis de construire"]
  },
  {
    id: "min-sports-jeunesse",
    nom: "Ministere des Sports, de la Jeunesse et de l'Emploi",
    nomCourt: "Sports & Jeunesse",
    ministre: "Anuuyirtole Roland SOMDA",
    rang: "Ministre",
    domaines: ["Sports", "Jeunesse", "Emploi"],
    adresse: "Avenue de la Jeunesse",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 32 48 70",
    email: "sg@sports.gov.bf",
    website: "https://www.sports.gov.bf",
    bp: "BP 7035 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3630,
    longitude: -1.5155,
    attributions: ["Promotion du sport", "Politique de la jeunesse", "Emploi et insertion", "Infrastructures sportives", "Mouvement associatif", "Service civique"]
  },
  {
    id: "min-infrastructures",
    nom: "Ministere des Infrastructures et du Desenclavement",
    nomCourt: "Infrastructures",
    ministre: "Adama L. SORGHO",
    rang: "Ministre",
    domaines: ["Infrastructures", "Routes", "Transport"],
    adresse: "Avenue du 11 Decembre",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 32 47 25",
    email: "sg@infrastructures.gov.bf",
    website: "https://www.infrastructures.gov.bf",
    bp: "BP 7011 Ouagadougou",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3620,
    longitude: -1.5145,
    attributions: ["Routes nationales", "Ponts et ouvrages", "Desenclavement", "Transport aerien", "Transport ferroviaire", "Batiments publics"]
  },
  {
    id: "min-serviteurs-peuple",
    nom: "Ministere des Serviteurs du Peuple",
    nomCourt: "Serviteurs du Peuple",
    ministre: "Mathias TRAORE",
    rang: "Ministre",
    domaines: ["Gouvernance", "Service public", "Ethique"],
    adresse: "Centre-ville",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 30 80 00",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3680,
    longitude: -1.5250,
    attributions: ["Gouvernance morale", "Ethique du service public", "Lutte contre la corruption", "Controle des agents publics", "Transparence", "Redevabilite"]
  },
  {
    id: "min-delegue-agriculture",
    nom: "Ministere Delegue aupres du Ministre de l'Agriculture (Ressources animales)",
    nomCourt: "Ressources animales",
    ministre: "Amadou DICKO",
    rang: "Ministre Delegue",
    domaines: ["Elevage", "Ressources animales"],
    adresse: "Rue Agostino Neto",
    quartier: "Koulouba",
    ville: "Ouagadougou",
    telephone: "+226 25 32 41 16",
    email: "sg@elevage.gov.bf",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3748,
    longitude: -1.5198,
    attributions: ["Elevage", "Sante animale", "Industries animales", "Paturages", "Lait et viande", "Aviculture"]
  },
  {
    id: "min-delegue-budget",
    nom: "Ministere Delegue aupres du Ministre de l'Economie et des Finances (Budget)",
    nomCourt: "Budget",
    ministre: "Fatoumata BAKO/TRAORE",
    rang: "Ministre Delegue",
    domaines: ["Budget", "Finances publiques"],
    adresse: "Avenue d'Oubritenga",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    telephone: "+226 25 32 42 08",
    email: "sg@budget.gov.bf",
    website: "https://www.budget.gov.bf",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3683,
    longitude: -1.5203,
    attributions: ["Preparation du budget", "Execution budgetaire", "Controle budgetaire", "Marches publics", "Finances locales", "Depense publique"]
  },
  {
    id: "min-delegue-cooperation",
    nom: "Ministere Delegue aupres du Ministre des Affaires etrangeres (Cooperation regionale)",
    nomCourt: "Cooperation regionale",
    ministre: "Stella Eldine KABRE/KABORE",
    rang: "Ministre Delegue",
    domaines: ["Cooperation regionale", "Integration"],
    adresse: "Avenue du Burkina",
    quartier: "Koulouba",
    ville: "Ouagadougou",
    telephone: "+226 25 32 47 35",
    email: "cooperation@diplomatie.gov.bf",
    horaires: "Lun-Ven: 07h30-12h30, 15h00-17h30",
    latitude: 12.3738,
    longitude: -1.5178,
    attributions: ["Cooperation regionale", "Integration africaine", "AES (Alliance des Etats du Sahel)", "CEDEAO", "UEMOA", "Union Africaine"]
  },
];
