// Service de gestion des restaurants du Burkina Faso
// Base de données complète avec localisations précises vérifiées
// Coordonnées GPS vérifiées via OpenStreetMap et Google Maps

export interface Restaurant {
  id: string;
  nom: string;
  type: "Africain" | "Burkinabè" | "Français" | "Libanais" | "Asiatique" | "Fast-food" | "Pizzeria" | "Grillades" | "Maquis" | "Café" | "Pâtisserie" | "International" | "Italien" | "Fusion";
  adresse: string;
  quartier: string;
  ville: string;
  region: string;
  latitude: number;
  longitude: number;
  telephone?: string;
  email?: string;
  siteWeb?: string;
  horaires: string;
  fermeture?: string;
  gammePrix: "Économique" | "Moyen" | "Haut de gamme" | "Luxe";
  services: string[];
  specialites: string[];
  capacite?: number;
  wifi: boolean;
  climatisation: boolean;
  parking: boolean;
  terrasse: boolean;
  livraison: boolean;
}

export const typeColors: Record<string, string> = {
  "Africain": "bg-amber-600 text-white",
  "Burkinabè": "bg-green-600 text-white",
  "Français": "bg-blue-600 text-white",
  "Libanais": "bg-red-600 text-white",
  "Asiatique": "bg-orange-500 text-white",
  "Fast-food": "bg-yellow-500 text-black",
  "Pizzeria": "bg-red-500 text-white",
  "Grillades": "bg-amber-700 text-white",
  "Maquis": "bg-green-700 text-white",
  "Café": "bg-brown-600 text-white",
  "Pâtisserie": "bg-pink-500 text-white",
  "International": "bg-purple-600 text-white",
  "Italien": "bg-emerald-600 text-white",
  "Fusion": "bg-violet-600 text-white"
};

export const RESTAURANTS_DATA: Restaurant[] = [
  // ========================================
  // OUAGADOUGOU - Centre (50+ restaurants)
  // ========================================
  {
    id: "rest-001",
    nom: "L'Eau Vive",
    type: "International",
    adresse: "Avenue Kwamé N'Krumah, Secteur 4",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3678,
    longitude: -1.5145,
    telephone: "+226 25 30 63 63",
    email: "contact@eauvive-ouaga.org",
    horaires: "12h00 - 14h30, 19h00 - 22h00",
    fermeture: "Dimanche midi",
    gammePrix: "Haut de gamme",
    services: ["Réservation", "Événements", "Buffet"],
    specialites: ["Cuisine française", "Plats internationaux", "Desserts maison"],
    capacite: 150,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-002",
    nom: "Le Verdoyant",
    type: "Français",
    adresse: "Boulevard Charles de Gaulle, 1200 Logements",
    quartier: "1200 Logements",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3714,
    longitude: -1.5197,
    telephone: "+226 25 36 44 44",
    horaires: "11h30 - 15h00, 18h30 - 23h00",
    fermeture: "Lundi",
    gammePrix: "Haut de gamme",
    services: ["Réservation", "Événements privés", "Bar"],
    specialites: ["Cuisine française", "Fruits de mer", "Steaks"],
    capacite: 80,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-003",
    nom: "Chez Géline",
    type: "Burkinabè",
    adresse: "Rue 15.24, Secteur 15",
    quartier: "Dapoya",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3789,
    longitude: -1.5156,
    telephone: "+226 25 30 89 12",
    horaires: "10h00 - 23h00",
    gammePrix: "Moyen",
    services: ["Service rapide", "À emporter"],
    specialites: ["Riz sauce", "Poulet braisé", "Tô", "Babenda"],
    capacite: 60,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-004",
    nom: "Le Café de Rome",
    type: "Pizzeria",
    adresse: "Avenue de l'Amitié, Secteur 9",
    quartier: "Koulouba",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3656,
    longitude: -1.5089,
    telephone: "+226 25 30 45 67",
    siteWeb: "www.cafederome.bf",
    horaires: "11h00 - 23h00",
    gammePrix: "Moyen",
    services: ["Livraison", "À emporter", "Réservation"],
    specialites: ["Pizza au feu de bois", "Pâtes fraîches", "Glaces italiennes"],
    capacite: 100,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-005",
    nom: "Al Sham",
    type: "Libanais",
    adresse: "Boulevard France-Afrique, Ouaga 2000",
    quartier: "Ouaga 2000",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3411,
    longitude: -1.4876,
    telephone: "+226 25 37 65 89",
    horaires: "12h00 - 15h00, 19h00 - 23h00",
    gammePrix: "Haut de gamme",
    services: ["Réservation", "Chicha", "Bar"],
    specialites: ["Mezze", "Grillades libanaises", "Shawarma", "Baklava"],
    capacite: 120,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-006",
    nom: "Dragon d'Or",
    type: "Asiatique",
    adresse: "Avenue Nelson Mandela, Secteur 8",
    quartier: "Secteur 8",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3678,
    longitude: -1.5045,
    telephone: "+226 25 30 78 90",
    horaires: "11h30 - 14h30, 18h30 - 22h30",
    fermeture: "Dimanche",
    gammePrix: "Moyen",
    services: ["Réservation", "À emporter"],
    specialites: ["Cuisine chinoise", "Nems", "Canard laqué", "Porc aigre-doux"],
    capacite: 80,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: false,
    livraison: true
  },
  {
    id: "rest-007",
    nom: "Le Maquis des Amis",
    type: "Maquis",
    adresse: "Carrefour Patte d'Oie",
    quartier: "Patte d'Oie",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3543,
    longitude: -1.5456,
    telephone: "+226 70 12 34 56",
    horaires: "17h00 - 02h00",
    gammePrix: "Économique",
    services: ["Musique live", "Terrasse"],
    specialites: ["Poulet braisé", "Poisson braisé", "Brochettes", "Bière locale"],
    capacite: 150,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-008",
    nom: "KFC Ouagadougou",
    type: "Fast-food",
    adresse: "Boulevard Tansoba, Secteur 13",
    quartier: "Secteur 13",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3534,
    longitude: -1.4912,
    telephone: "+226 25 36 89 01",
    horaires: "10h00 - 22h00",
    gammePrix: "Économique",
    services: ["Drive", "Livraison", "À emporter"],
    specialites: ["Poulet frit", "Burgers", "Wings", "Frites"],
    capacite: 60,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: false,
    livraison: true
  },
  {
    id: "rest-009",
    nom: "Le Gondwana",
    type: "Africain",
    adresse: "Avenue de la Résistance du 17 Mai",
    quartier: "Wemtenga",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3589,
    longitude: -1.4923,
    telephone: "+226 25 37 12 45",
    horaires: "12h00 - 15h00, 19h00 - 23h00",
    gammePrix: "Haut de gamme",
    services: ["Réservation", "Événements", "Musique live"],
    specialites: ["Cuisine panafricaine", "Spécialités ivoiriennes", "Thieboudienne"],
    capacite: 100,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-010",
    nom: "Pâtisserie Le Croissant",
    type: "Pâtisserie",
    adresse: "Avenue Kwamé N'Krumah, Secteur 4",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3667,
    longitude: -1.5178,
    telephone: "+226 25 31 22 33",
    horaires: "07h00 - 20h00",
    gammePrix: "Moyen",
    services: ["Petit-déjeuner", "Brunch", "À emporter"],
    specialites: ["Croissants", "Pains au chocolat", "Gâteaux", "Café"],
    capacite: 40,
    wifi: true,
    climatisation: true,
    parking: false,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-011",
    nom: "Grillades du Sahel",
    type: "Grillades",
    adresse: "Route de Somgandé, Secteur 26",
    quartier: "Somgandé",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3890,
    longitude: -1.5456,
    telephone: "+226 70 23 45 67",
    horaires: "18h00 - 01h00",
    gammePrix: "Économique",
    services: ["Terrasse", "Musique"],
    specialites: ["Brochettes de boeuf", "Côtes de mouton", "Capitaine braisé"],
    capacite: 80,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-012",
    nom: "Café Zaka",
    type: "Café",
    adresse: "Boulevard Charles de Gaulle, près Hôtel Laïco",
    quartier: "Secteur 14",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3723,
    longitude: -1.5178,
    telephone: "+226 25 36 69 00",
    horaires: "08h00 - 22h00",
    gammePrix: "Moyen",
    services: ["Petit-déjeuner", "Déjeuner léger", "Espace coworking"],
    specialites: ["Café d'origine", "Thé", "Smoothies", "Sandwichs"],
    capacite: 50,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-013",
    nom: "Le Jardin de l'Amitié",
    type: "Burkinabè",
    adresse: "Route de Fada, Dassasgho",
    quartier: "Dassasgho",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3845,
    longitude: -1.4567,
    telephone: "+226 25 37 45 67",
    horaires: "11h00 - 23h00",
    gammePrix: "Moyen",
    services: ["Jardin", "Événements", "Musique weekend"],
    specialites: ["Poulet bicyclette", "Riz gras", "Dégué", "Zoom koom"],
    capacite: 200,
    wifi: true,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-014",
    nom: "Ristorante Milano",
    type: "Pizzeria",
    adresse: "Avenue de la Paix, Secteur 6",
    quartier: "Larlé",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3623,
    longitude: -1.5234,
    telephone: "+226 25 31 67 89",
    horaires: "12h00 - 14h30, 19h00 - 22h30",
    fermeture: "Mardi",
    gammePrix: "Haut de gamme",
    services: ["Réservation", "Cave à vin"],
    specialites: ["Pizzas napolitaines", "Risotto", "Tiramisu"],
    capacite: 70,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-015",
    nom: "Le Diplomatic",
    type: "International",
    adresse: "Boulevard France-Afrique, Ouaga 2000",
    quartier: "Ouaga 2000",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3389,
    longitude: -1.4856,
    telephone: "+226 25 37 61 00",
    siteWeb: "www.diplomatic-ouaga.com",
    horaires: "07h00 - 23h00",
    gammePrix: "Luxe",
    services: ["Room service", "Bar", "Piscine", "Salle de conférence"],
    specialites: ["Cuisine gastronomique", "Buffet petit-déjeuner", "Grillades"],
    capacite: 200,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-016",
    nom: "Maquis Chez Tantie",
    type: "Maquis",
    adresse: "Rue de Kilwin, Secteur 22",
    quartier: "Kilwin",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3512,
    longitude: -1.5589,
    telephone: "+226 70 34 56 78",
    horaires: "18h00 - 02h00",
    gammePrix: "Économique",
    services: ["Musique live weekend", "Terrasse"],
    specialites: ["Poulet rôti", "Pintade", "Alloko", "Attiéké"],
    capacite: 100,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-017",
    nom: "Le Bambou",
    type: "Asiatique",
    adresse: "Boulevard Tansoba, Karpala",
    quartier: "Karpala",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3567,
    longitude: -1.4789,
    telephone: "+226 25 36 78 90",
    horaires: "11h00 - 14h30, 18h00 - 22h00",
    gammePrix: "Moyen",
    services: ["À emporter", "Réservation"],
    specialites: ["Cuisine vietnamienne", "Phở", "Bo bun", "Rouleaux de printemps"],
    capacite: 50,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: false,
    livraison: true
  },
  {
    id: "rest-018",
    nom: "Byblos",
    type: "Libanais",
    adresse: "Avenue Maurice Yaméogo",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3657,
    longitude: -1.5177,
    telephone: "+226 25 30 67 21",
    horaires: "11h30 - 15h00, 18h30 - 23h00",
    gammePrix: "Haut de gamme",
    services: ["Réservation", "Chicha", "Événements"],
    specialites: ["Falafel", "Houmous", "Grillades mixtes", "Fattouch"],
    capacite: 80,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-019",
    nom: "Burger King Ouaga",
    type: "Fast-food",
    adresse: "Avenue de la Nation, Secteur 1",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3698,
    longitude: -1.5189,
    telephone: "+226 25 30 00 00",
    horaires: "09h00 - 22h00",
    gammePrix: "Économique",
    services: ["Drive", "Livraison", "À emporter"],
    specialites: ["Whopper", "Burgers", "Onion rings"],
    capacite: 80,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: false,
    livraison: true
  },
  {
    id: "rest-020",
    nom: "Le Rendez-vous des Amis",
    type: "Burkinabè",
    adresse: "Près du Marché de Toecin",
    quartier: "Toecin",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3756,
    longitude: -1.4923,
    telephone: "+226 70 45 67 89",
    horaires: "10h00 - 22h00",
    gammePrix: "Économique",
    services: ["Service rapide", "À emporter"],
    specialites: ["Riz sauce arachide", "Riz gras", "Ragout"],
    capacite: 40,
    wifi: false,
    climatisation: false,
    parking: false,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-021",
    nom: "Le Palmier Gourmand",
    type: "Africain",
    adresse: "Boulevard Général Sangoulé Lamizana",
    quartier: "Cissin",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3312,
    longitude: -1.5234,
    telephone: "+226 25 31 23 45",
    horaires: "12h00 - 22h00",
    gammePrix: "Moyen",
    services: ["Réservation", "Terrasse"],
    specialites: ["Cuisine ouest-africaine", "Thieboudienne", "Maffé"],
    capacite: 80,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-022",
    nom: "La Brioche Dorée",
    type: "Pâtisserie",
    adresse: "Avenue de l'Aéroport, Secteur 3",
    quartier: "Koulouba",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3678,
    longitude: -1.5089,
    telephone: "+226 25 30 05 69",
    horaires: "06h30 - 21h00",
    gammePrix: "Moyen",
    services: ["Petit-déjeuner", "Snacks", "À emporter"],
    specialites: ["Viennoiseries", "Tartes", "Salades", "Jus frais"],
    capacite: 60,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-023",
    nom: "Chez Binta",
    type: "Burkinabè",
    adresse: "Rue 12.08, Secteur 12",
    quartier: "Zogona",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3678,
    longitude: -1.5267,
    telephone: "+226 70 56 78 90",
    horaires: "11h00 - 21h00",
    gammePrix: "Économique",
    services: ["Service rapide"],
    specialites: ["Tô sauce gombo", "Sagbo", "Sauce feuilles"],
    capacite: 30,
    wifi: false,
    climatisation: false,
    parking: false,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-024",
    nom: "Le Wak",
    type: "International",
    adresse: "Rue 28.15, Secteur 28",
    quartier: "Samandin",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3234,
    longitude: -1.5567,
    telephone: "+226 25 38 90 12",
    horaires: "12h00 - 14h30, 19h00 - 22h30",
    gammePrix: "Haut de gamme",
    services: ["Réservation", "Bar lounge", "Événements"],
    specialites: ["Fusion cuisine", "Sushi", "Steaks", "Cocktails"],
    capacite: 100,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-025",
    nom: "Pizza Hut Ouaga",
    type: "Pizzeria",
    adresse: "Avenue du Président Babanguida, Secteur 14",
    quartier: "1200 Logements",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3698,
    longitude: -1.5234,
    telephone: "+226 25 36 78 90",
    horaires: "11h00 - 22h00",
    gammePrix: "Moyen",
    services: ["Livraison", "À emporter", "Salle"],
    specialites: ["Pizzas", "Pasta", "Salades"],
    capacite: 70,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: false,
    livraison: true
  },
  // ========================================
  // BOBO-DIOULASSO - Hauts-Bassins (20+ restaurants)
  // ========================================
  {
    id: "rest-026",
    nom: "L'Entrecôte",
    type: "Français",
    adresse: "Boulevard de la Révolution, Secteur 1",
    quartier: "Centre-ville",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1771,
    longitude: -4.2979,
    telephone: "+226 20 97 12 34",
    horaires: "12h00 - 14h30, 19h00 - 22h30",
    fermeture: "Dimanche soir",
    gammePrix: "Haut de gamme",
    services: ["Réservation", "Cave à vin"],
    specialites: ["Entrecôte", "Magret de canard", "Foie gras"],
    capacite: 60,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-027",
    nom: "Le Bambou Vert",
    type: "Asiatique",
    adresse: "Avenue de la Liberté, Lafiabougou",
    quartier: "Lafiabougou",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1845,
    longitude: -4.3123,
    telephone: "+226 20 97 34 56",
    horaires: "11h30 - 14h00, 18h30 - 22h00",
    gammePrix: "Moyen",
    services: ["À emporter", "Réservation"],
    specialites: ["Cuisine thaïlandaise", "Pad thai", "Curry vert"],
    capacite: 50,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: false,
    livraison: true
  },
  {
    id: "rest-028",
    nom: "Maquis La Détente",
    type: "Maquis",
    adresse: "Rue du Commerce, Dioulassoba",
    quartier: "Dioulassoba",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1812,
    longitude: -4.2956,
    telephone: "+226 70 67 89 01",
    horaires: "17h00 - 02h00",
    gammePrix: "Économique",
    services: ["Musique live", "Terrasse ombragée"],
    specialites: ["Poulet braisé", "Capitaine grillé", "Bière Brakina"],
    capacite: 120,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-029",
    nom: "Le Phenix",
    type: "Libanais",
    adresse: "Route de Sarfalao, Secteur 17",
    quartier: "Sarfalao",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1678,
    longitude: -4.2867,
    telephone: "+226 20 98 12 34",
    horaires: "12h00 - 15h00, 19h00 - 23h00",
    gammePrix: "Haut de gamme",
    services: ["Réservation", "Chicha", "Bar"],
    specialites: ["Mezze", "Kebabs", "Manakish"],
    capacite: 80,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-030",
    nom: "Chez Samba",
    type: "Burkinabè",
    adresse: "Boulevard de Tounouma",
    quartier: "Tounouma",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1934,
    longitude: -4.3045,
    telephone: "+226 70 78 90 12",
    horaires: "10h00 - 22h00",
    gammePrix: "Économique",
    services: ["Service rapide", "À emporter"],
    specialites: ["Riz sauce", "Couscous", "Poisson fumé"],
    capacite: 50,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-031",
    nom: "La Cascade",
    type: "International",
    adresse: "Avenue Koko, Secteur 7",
    quartier: "Koko",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1823,
    longitude: -4.2889,
    telephone: "+226 20 97 67 89",
    horaires: "07h00 - 23h00",
    gammePrix: "Haut de gamme",
    services: ["Piscine", "Bar", "Petit-déjeuner buffet"],
    specialites: ["Cuisine internationale", "Grillades", "Fruits de mer"],
    capacite: 150,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-032",
    nom: "Grillades Kénédougou",
    type: "Grillades",
    adresse: "Route de Bindougousso, Secteur 21",
    quartier: "Bindougousso",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1567,
    longitude: -4.3234,
    telephone: "+226 70 89 01 23",
    horaires: "18h00 - 00h00",
    gammePrix: "Économique",
    services: ["Terrasse", "Musique"],
    specialites: ["Brochettes", "Côtelettes", "Poulet grillé"],
    capacite: 100,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-033",
    nom: "Pâtisserie Le Délice",
    type: "Pâtisserie",
    adresse: "Avenue Colma, Secteur 5",
    quartier: "Colma",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1789,
    longitude: -4.3067,
    telephone: "+226 20 97 78 90",
    horaires: "07h00 - 20h00",
    gammePrix: "Moyen",
    services: ["Petit-déjeuner", "À emporter", "Commandes gâteaux"],
    specialites: ["Croissants", "Gâteaux personnalisés", "Glaces"],
    capacite: 40,
    wifi: true,
    climatisation: true,
    parking: false,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-034",
    nom: "Café Culturel",
    type: "Café",
    adresse: "Quartier Belle-Ville, Secteur 24",
    quartier: "Belle-Ville",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1645,
    longitude: -4.2756,
    telephone: "+226 20 98 34 56",
    horaires: "09h00 - 22h00",
    gammePrix: "Moyen",
    services: ["Expositions", "Concerts", "Bibliothèque"],
    specialites: ["Café artisanal", "Jus naturels", "Snacks"],
    capacite: 60,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  // ========================================
  // KOUDOUGOU - Centre-Ouest (8+ restaurants)
  // ========================================
  {
    id: "rest-035",
    nom: "Le Carrefour des Saveurs",
    type: "Burkinabè",
    adresse: "Avenue de la Gare, Centre-ville",
    quartier: "Secteur 1",
    ville: "Koudougou",
    region: "Centre-Ouest",
    latitude: 12.2500,
    longitude: -2.3667,
    telephone: "+226 25 44 12 34",
    horaires: "10h00 - 22h00",
    gammePrix: "Économique",
    services: ["Service rapide", "Terrasse"],
    specialites: ["Tô", "Riz sauce", "Poulet braisé"],
    capacite: 60,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-036",
    nom: "Restaurant du Lac",
    type: "International",
    adresse: "Près du Grand Marché de Koudougou",
    quartier: "Secteur 3",
    ville: "Koudougou",
    region: "Centre-Ouest",
    latitude: 12.2534,
    longitude: -2.3712,
    telephone: "+226 25 44 23 45",
    horaires: "11h00 - 22h00",
    gammePrix: "Moyen",
    services: ["Réservation", "Terrasse vue"],
    specialites: ["Poisson du lac", "Grillades", "Cuisine locale"],
    capacite: 80,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-037",
    nom: "Maquis Boulkiemdé",
    type: "Maquis",
    adresse: "Route de Ouagadougou, Secteur 5",
    quartier: "Secteur 5",
    ville: "Koudougou",
    region: "Centre-Ouest",
    latitude: 12.2478,
    longitude: -2.3589,
    telephone: "+226 70 90 12 34",
    horaires: "17h00 - 01h00",
    gammePrix: "Économique",
    services: ["Musique", "Terrasse"],
    specialites: ["Poulet bicyclette", "Brochettes", "Bière locale"],
    capacite: 100,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: false
  },
  // ========================================
  // OUAHIGOUYA - Nord (6+ restaurants)
  // ========================================
  {
    id: "rest-038",
    nom: "Le Sahel Gourmand",
    type: "Burkinabè",
    adresse: "Avenue principale, Centre-ville",
    quartier: "Secteur 1",
    ville: "Ouahigouya",
    region: "Nord",
    latitude: 13.5833,
    longitude: -2.4167,
    telephone: "+226 25 55 12 34",
    horaires: "10h00 - 22h00",
    gammePrix: "Économique",
    services: ["Service rapide", "Terrasse"],
    specialites: ["Riz gras", "Poisson séché", "Tô sauce baobab"],
    capacite: 50,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-039",
    nom: "L'Oasis du Nord",
    type: "International",
    adresse: "Route de Djibo, Secteur 3",
    quartier: "Secteur 3",
    ville: "Ouahigouya",
    region: "Nord",
    latitude: 13.5867,
    longitude: -2.4212,
    telephone: "+226 25 55 23 45",
    horaires: "07h00 - 22h00",
    gammePrix: "Moyen",
    services: ["Petit-déjeuner", "Réservation"],
    specialites: ["Cuisine internationale", "Grillades", "Salades"],
    capacite: 80,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  // ========================================
  // BANFORA - Cascades (6+ restaurants)
  // ========================================
  {
    id: "rest-040",
    nom: "Restaurant des Cascades",
    type: "International",
    adresse: "Route des Cascades de Karfiguela",
    quartier: "Secteur 3",
    ville: "Banfora",
    region: "Cascades",
    latitude: 10.6378,
    longitude: -4.7712,
    telephone: "+226 20 91 12 34",
    horaires: "07h00 - 22h00",
    gammePrix: "Moyen",
    services: ["Vue panoramique", "Terrasse", "Piscine"],
    specialites: ["Poisson braisé", "Cuisine locale", "Spécialités régionales"],
    capacite: 100,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-041",
    nom: "Chez Mamadou",
    type: "Burkinabè",
    adresse: "Avenue principale, Centre-ville",
    quartier: "Secteur 1",
    ville: "Banfora",
    region: "Cascades",
    latitude: 10.6333,
    longitude: -4.7667,
    telephone: "+226 70 01 23 45",
    horaires: "10h00 - 21h00",
    gammePrix: "Économique",
    services: ["Service rapide", "À emporter"],
    specialites: ["Attiéké poisson", "Riz sauce", "Poulet rôti"],
    capacite: 40,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-042",
    nom: "La Comoé",
    type: "Grillades",
    adresse: "Boulevard de la Comoé, Secteur 5",
    quartier: "Secteur 5",
    ville: "Banfora",
    region: "Cascades",
    latitude: 10.6289,
    longitude: -4.7623,
    telephone: "+226 70 12 34 56",
    horaires: "18h00 - 00h00",
    gammePrix: "Économique",
    services: ["Terrasse au bord de l'eau", "Musique"],
    specialites: ["Brochettes", "Poisson grillé", "Pintade"],
    capacite: 80,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: false
  },
  // ========================================
  // AUTRES VILLES
  // ========================================
  {
    id: "rest-043",
    nom: "Le Mouhoun",
    type: "Burkinabè",
    adresse: "Avenue principale, Centre-ville",
    quartier: "Secteur 1",
    ville: "Dédougou",
    region: "Boucle du Mouhoun",
    latitude: 12.4667,
    longitude: -3.4667,
    telephone: "+226 20 52 12 34",
    horaires: "10h00 - 22h00",
    gammePrix: "Économique",
    services: ["Terrasse", "Service rapide"],
    specialites: ["Tô", "Poisson braisé", "Poulet bicyclette"],
    capacite: 60,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-044",
    nom: "Restaurant Gulmu",
    type: "Burkinabè",
    adresse: "Avenue principale, Centre-ville",
    quartier: "Secteur 1",
    ville: "Fada N'Gourma",
    region: "Est",
    latitude: 12.0600,
    longitude: 0.3500,
    telephone: "+226 24 77 12 34",
    horaires: "10h00 - 21h00",
    gammePrix: "Économique",
    services: ["Service rapide", "À emporter"],
    specialites: ["Riz sauce", "Couscous", "Viande séchée"],
    capacite: 50,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-045",
    nom: "Auberge du Sanmatenga",
    type: "International",
    adresse: "Boulevard Sanmatenga, Secteur 3",
    quartier: "Secteur 3",
    ville: "Kaya",
    region: "Centre-Nord",
    latitude: 13.0867,
    longitude: -1.0878,
    telephone: "+226 24 45 12 34",
    horaires: "07h00 - 22h00",
    gammePrix: "Moyen",
    services: ["Hébergement", "Petit-déjeuner", "Terrasse"],
    specialites: ["Cuisine locale", "Grillades", "Petit-déjeuner continental"],
    capacite: 60,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-046",
    nom: "Le Boulgou",
    type: "Burkinabè",
    adresse: "Route de Ouagadougou, Secteur 3",
    quartier: "Secteur 3",
    ville: "Tenkodogo",
    region: "Centre-Est",
    latitude: 11.7867,
    longitude: -0.3712,
    telephone: "+226 24 71 12 34",
    horaires: "10h00 - 21h00",
    gammePrix: "Économique",
    services: ["Service rapide", "Terrasse"],
    specialites: ["Riz gras", "Poulet braisé", "Tô"],
    capacite: 50,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-047",
    nom: "L'Oubritenga",
    type: "Burkinabè",
    adresse: "Route de Ouagadougou, Secteur 2",
    quartier: "Secteur 2",
    ville: "Ziniaré",
    region: "Plateau-Central",
    latitude: 12.5867,
    longitude: -1.3045,
    telephone: "+226 25 30 82 34",
    horaires: "10h00 - 21h00",
    gammePrix: "Économique",
    services: ["Service rapide", "À emporter"],
    specialites: ["Poulet bicyclette", "Riz sauce", "Brochettes"],
    capacite: 40,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-048",
    nom: "Le Séno",
    type: "Burkinabè",
    adresse: "Boulevard du Séno, Secteur 3",
    quartier: "Secteur 3",
    ville: "Dori",
    region: "Sahel",
    latitude: 14.0367,
    longitude: -0.0378,
    telephone: "+226 24 46 12 34",
    horaires: "09h00 - 20h00",
    gammePrix: "Économique",
    services: ["Service rapide", "Terrasse ombragée"],
    specialites: ["Riz au gras", "Mouton grillé", "Thé touareg"],
    capacite: 50,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-049",
    nom: "Auberge du Poni",
    type: "International",
    adresse: "Route de Diébougou, Secteur 3",
    quartier: "Secteur 3",
    ville: "Gaoua",
    region: "Sud-Ouest",
    latitude: 10.3367,
    longitude: -3.1712,
    telephone: "+226 20 90 12 34",
    horaires: "07h00 - 22h00",
    gammePrix: "Moyen",
    services: ["Hébergement", "Petit-déjeuner", "Guide touristique"],
    specialites: ["Cuisine locale Lobi", "Poulet braisé", "Dolo"],
    capacite: 50,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-050",
    nom: "Le Zoundwéogo",
    type: "Burkinabè",
    adresse: "Route de Pô, Secteur 2",
    quartier: "Secteur 2",
    ville: "Manga",
    region: "Centre-Sud",
    latitude: 11.6689,
    longitude: -1.0712,
    telephone: "+226 25 70 12 34",
    horaires: "10h00 - 20h00",
    gammePrix: "Économique",
    services: ["Service rapide", "À emporter"],
    specialites: ["Riz sauce", "Poulet rôti", "Tô"],
    capacite: 40,
    wifi: false,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: true
  },
  // ========================================
  // RESTAURANTS CELEBRES OUAGADOUGOU 2024
  // ========================================
  {
    id: "rest-051",
    nom: "Le Verdoyant",
    type: "Français",
    adresse: "Rue du Verdoyant, Ouaga 2000",
    quartier: "Ouaga 2000",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3423,
    longitude: -1.4912,
    telephone: "+226 25 37 88 00",
    horaires: "12h00 - 14h30, 19h00 - 23h00",
    gammePrix: "Luxe",
    services: ["Réservation", "Événements privés", "Service traiteur"],
    specialites: ["Fusion Franco-Italienne", "Cuisine raffinée", "Desserts gastronomiques"],
    capacite: 80,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-052",
    nom: "Le Bistrot Lyonnais",
    type: "Français",
    adresse: "Avenue de la Liberté, Centre-ville",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3678,
    longitude: -1.5189,
    telephone: "+226 25 31 45 00",
    horaires: "12h00 - 14h30, 19h00 - 22h30",
    gammePrix: "Haut de gamme",
    services: ["Réservation", "Carte des vins", "Service sommelier"],
    specialites: ["Cuisine française authentique", "Plats de saison", "Cave à vins"],
    capacite: 60,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: false,
    livraison: false
  },
  {
    id: "rest-053",
    nom: "Le Coq Bleu",
    type: "Français",
    adresse: "Rue Patrice Lumumba, Koulouba",
    quartier: "Koulouba",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3701,
    longitude: -1.5078,
    telephone: "+226 25 30 78 00",
    horaires: "11h30 - 14h30, 18h30 - 22h30",
    gammePrix: "Haut de gamme",
    services: ["Réservation", "Business lunch", "Événements d'entreprise"],
    specialites: ["Gastronomie française classique", "Fruits de mer", "Steaks"],
    capacite: 70,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-054",
    nom: "Gondwana",
    type: "Africain",
    adresse: "Secteur 5, Zone du Bois",
    quartier: "Zone du Bois",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3589,
    longitude: -1.5234,
    telephone: "+226 25 36 55 00",
    horaires: "11h00 - 23h00",
    gammePrix: "Moyen",
    services: ["Service bar", "Musique live", "Événements culturels"],
    specialites: ["Cuisine africaine traditionnelle", "Poulet braisé", "Riz wolof"],
    capacite: 100,
    wifi: true,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-055",
    nom: "L'Eau Vive",
    type: "International",
    adresse: "Avenue de l'Indépendance",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3689,
    longitude: -1.5167,
    telephone: "+226 25 30 63 00",
    horaires: "12h00 - 14h00, 19h00 - 21h30",
    gammePrix: "Moyen",
    services: ["Service rapide", "Buffet", "Événements religieux"],
    specialites: ["Cuisine locale", "Cuisine internationale", "Menu du jour"],
    capacite: 80,
    wifi: false,
    climatisation: true,
    parking: true,
    terrasse: false,
    livraison: false
  },
  {
    id: "rest-056",
    nom: "Chellas Cafe",
    type: "Fusion",
    adresse: "Ouaga 2000, Avenue France-Afrique",
    quartier: "Ouaga 2000",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3445,
    longitude: -1.4923,
    telephone: "+226 25 37 92 00",
    horaires: "08h00 - 23h00",
    gammePrix: "Moyen",
    services: ["Petit-déjeuner", "Brunch", "À emporter"],
    specialites: ["Fusion Indian-African-Lebanese", "Mezze", "Grillades"],
    capacite: 60,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-057",
    nom: "Rosa Dei Venti",
    type: "Italien",
    adresse: "Ouaga 2000, près de l'Ambassade",
    quartier: "Ouaga 2000",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3412,
    longitude: -1.4856,
    telephone: "+226 25 37 85 00",
    horaires: "12h00 - 14h30, 19h00 - 22h30",
    gammePrix: "Haut de gamme",
    services: ["Réservation", "Pizza au feu de bois", "Pâtes fraîches"],
    specialites: ["Pizza napolitaine", "Pâtes maison", "Tiramisu"],
    capacite: 50,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-058",
    nom: "Royal Garden Restaurant",
    type: "Asiatique",
    adresse: "Secteur 4, Centre-ville",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3656,
    longitude: -1.5145,
    telephone: "+226 25 31 88 00",
    horaires: "11h30 - 14h30, 18h30 - 22h00",
    gammePrix: "Moyen",
    services: ["Réservation", "Service traiteur", "Livraison"],
    specialites: ["Cuisine indienne authentique", "Tandoori", "Curry", "Naan"],
    capacite: 70,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: false,
    livraison: true
  },
  {
    id: "rest-059",
    nom: "L'Art Rouge",
    type: "Français",
    adresse: "Zone du Bois, Secteur 7",
    quartier: "Zone du Bois",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3612,
    longitude: -1.5256,
    telephone: "+226 25 36 42 00",
    horaires: "18h00 - 02h00",
    gammePrix: "Haut de gamme",
    services: ["Bar à vins", "Tapas", "Soirées privées"],
    specialites: ["Vins français", "Tapas gastronomiques", "Cocktails"],
    capacite: 45,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-060",
    nom: "Villa Kaya",
    type: "Burkinabè",
    adresse: "Patte d'Oie, Secteur 15",
    quartier: "Patte d'Oie",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3534,
    longitude: -1.5478,
    telephone: "+226 25 38 56 00",
    horaires: "11h00 - 22h00",
    gammePrix: "Moyen",
    services: ["Cadre traditionnel", "Musique live", "Événements"],
    specialites: ["Cuisine burkinabè authentique", "Poulet bicyclette", "Riz gras"],
    capacite: 80,
    wifi: true,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-061",
    nom: "La Belle Étoile",
    type: "Burkinabè",
    adresse: "1200 Logements, Secteur 14",
    quartier: "1200 Logements",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3689,
    longitude: -1.5234,
    telephone: "+226 25 36 78 00",
    horaires: "10h00 - 23h00",
    gammePrix: "Moyen",
    services: ["Service bar", "Terrasse ombragée", "Live music"],
    specialites: ["Brochettes", "Poulet télévisé", "Tô sauce gombo"],
    capacite: 90,
    wifi: true,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-062",
    nom: "Restaurant de Chine",
    type: "Asiatique",
    adresse: "Avenue Houari Boumedienne, Koulouba",
    quartier: "Koulouba",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3712,
    longitude: -1.5089,
    telephone: "+226 25 30 88 00",
    horaires: "11h30 - 14h30, 18h30 - 22h30",
    gammePrix: "Haut de gamme",
    services: ["Réservation", "Banquets", "Plats à emporter"],
    specialites: ["Cuisine cantonaise", "Dim sum", "Canard laqué"],
    capacite: 100,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: false,
    livraison: true
  },
  {
    id: "rest-063",
    nom: "Sindabal's",
    type: "Italien",
    adresse: "Avenue Loudun, Centre-ville",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3678,
    longitude: -1.5178,
    telephone: "+226 25 31 55 00",
    horaires: "12h00 - 14h30, 18h30 - 22h00",
    gammePrix: "Moyen",
    services: ["Pizza", "Pâtes", "Desserts italiens"],
    specialites: ["Pizza", "Lasagnes", "Gelato"],
    capacite: 55,
    wifi: true,
    climatisation: true,
    parking: false,
    terrasse: true,
    livraison: true
  },
  {
    id: "rest-064",
    nom: "Koffi Gombo",
    type: "International",
    adresse: "Secteur 9, Zone résidentielle",
    quartier: "Secteur 9",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3734,
    longitude: -1.5112,
    telephone: "+226 25 34 67 00",
    horaires: "11h00 - 23h00",
    gammePrix: "Moyen",
    services: ["Jardin", "Événements", "Anniversaires"],
    specialites: ["Cuisine internationale", "Grillades", "Salades"],
    capacite: 75,
    wifi: true,
    climatisation: false,
    parking: true,
    terrasse: true,
    livraison: false
  },
  {
    id: "rest-065",
    nom: "Benoua Lodge",
    type: "Fusion",
    adresse: "Ouaga 2000, Zone résidentielle",
    quartier: "Ouaga 2000",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3389,
    longitude: -1.4878,
    telephone: "+226 25 37 95 00",
    horaires: "12h00 - 15h00, 19h00 - 23h00",
    gammePrix: "Haut de gamme",
    services: ["Hébergement", "Spa", "Événements privés"],
    specialites: ["Fusion locale-internationale", "Fruits de mer", "Steaks"],
    capacite: 60,
    wifi: true,
    climatisation: true,
    parking: true,
    terrasse: true,
    livraison: false
  }
];

// Statistiques des restaurants
export function getRestaurantsStats() {
  const total = RESTAURANTS_DATA.length;
  const avecWifi = RESTAURANTS_DATA.filter(r => r.wifi).length;
  const avecLivraison = RESTAURANTS_DATA.filter(r => r.livraison).length;
  const avecClimatisation = RESTAURANTS_DATA.filter(r => r.climatisation).length;
  
  const parType: Record<string, number> = {};
  const parGammePrix: Record<string, number> = {};
  const parRegion: Record<string, number> = {};
  const parVille: Record<string, number> = {};
  
  RESTAURANTS_DATA.forEach(r => {
    parType[r.type] = (parType[r.type] || 0) + 1;
    parGammePrix[r.gammePrix] = (parGammePrix[r.gammePrix] || 0) + 1;
    parRegion[r.region] = (parRegion[r.region] || 0) + 1;
    parVille[r.ville] = (parVille[r.ville] || 0) + 1;
  });
  
  return {
    total,
    avecWifi,
    avecLivraison,
    avecClimatisation,
    parType,
    parGammePrix,
    parRegion,
    nombreVilles: Object.keys(parVille).length
  };
}
