// Service de gestion des banques et caisses populaires du Burkina Faso
// Base de données complète avec localisations précises vérifiées
// Coordonnées GPS vérifiées via OpenStreetMap et Google Maps
// Données 2024 - BCEAO / Commission Bancaire UMOA

export interface Banque {
  id: string;
  nom: string;
  sigle: string;
  type: "Banque" | "Caisse Populaire" | "Microfinance" | "Établissement Financier";
  categorie: "Commerciale" | "Agricole" | "Postale" | "Régionale" | "Microfinance";
  adresse: string;
  quartier: string;
  ville: string;
  region: string;
  latitude: number;
  longitude: number;
  telephone?: string;
  email?: string;
  siteWeb?: string;
  horaires: string;
  services: string[];
  hasGAB: boolean;
  nombreAgences?: number;
  nombreGAB?: number;
  importanceSystemique?: boolean;
}

export const typeColors: Record<string, string> = {
  "Banque": "bg-blue-600 text-white",
  "Caisse Populaire": "bg-green-600 text-white",
  "Microfinance": "bg-amber-600 text-white",
  "Établissement Financier": "bg-purple-600 text-white"
};

export const categorieColors: Record<string, string> = {
  "Commerciale": "bg-blue-500 text-white",
  "Agricole": "bg-green-500 text-white",
  "Postale": "bg-orange-500 text-white",
  "Régionale": "bg-teal-500 text-white",
  "Microfinance": "bg-amber-500 text-white"
};

export const BANQUES_DATA: Banque[] = [
  // ========================================
  // BANQUES COMMERCIALES - OUAGADOUGOU
  // ========================================
  {
    id: "bq-001",
    nom: "Coris Bank International",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue Yennenga, face Station Shell Ciné Rialé",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3689,
    longitude: -1.5178,
    telephone: "+226 25 30 68 14",
    email: "info@coris-bank.com",
    siteWeb: "www.coris-bank.com",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Mobile Banking", "Cartes Visa/Mastercard", "Trade Finance", "Leasing"],
    hasGAB: true,
    nombreAgences: 85,
    nombreGAB: 150,
    importanceSystemique: true
  },
  {
    id: "bq-002",
    nom: "Ecobank Burkina",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "633, Rue Ilboudo Waogyandé",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3701,
    longitude: -1.5156,
    telephone: "+226 25 32 83 28",
    email: "elosbf@ecobank.com",
    siteWeb: "www.ecobank.com/bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Ecobank Mobile", "Cartes bancaires", "Western Union"],
    hasGAB: true,
    nombreAgences: 30,
    nombreGAB: 80,
    importanceSystemique: true
  },
  {
    id: "bq-003",
    nom: "Bank of Africa - Burkina Faso",
    sigle: "BOA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "770 Avenue Kwamé N'Krumah",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3678,
    longitude: -1.5189,
    telephone: "+226 25 30 88 88",
    email: "boabf@boa.bf",
    siteWeb: "www.boabf.com",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "BOA Mobile", "Cartes Visa", "Trade Finance"],
    hasGAB: true,
    nombreAgences: 54,
    nombreGAB: 100,
    importanceSystemique: true
  },
  {
    id: "bq-004",
    nom: "United Bank for Africa Burkina",
    sigle: "UBA Burkina",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue Kwamé N'Krumah",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3695,
    longitude: -1.5167,
    telephone: "+226 25 49 63 00",
    email: "cfcburkina@ubagroup.com",
    siteWeb: "www.ubagroup.com/bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "UBA Mobile", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreAgences: 20,
    nombreGAB: 45,
    importanceSystemique: true
  },
  {
    id: "bq-005",
    nom: "Vista Bank Burkina",
    sigle: "Vista Bank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue Kwamé N'Krumah, ex-Société Générale",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3712,
    longitude: -1.5145,
    telephone: "+226 25 32 60 00",
    email: "contact@vistabank.bf",
    siteWeb: "www.vistabank.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Mobile Banking", "Cartes Visa"],
    hasGAB: true,
    nombreAgences: 25,
    nombreGAB: 60,
    importanceSystemique: true
  },
  {
    id: "bq-006",
    nom: "Banque Internationale pour le Commerce, l'Industrie et l'Agriculture du Burkina",
    sigle: "BICIA-B",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "479, Avenue du Docteur Kwamé N'Krumah",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3667,
    longitude: -1.5201,
    telephone: "+226 25 31 31 31",
    email: "bicia@bicia.bf",
    siteWeb: "www.bicia.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Cartes bancaires", "Financement agricole"],
    hasGAB: true,
    nombreAgences: 18,
    nombreGAB: 40
  },
  {
    id: "bq-007",
    nom: "Banque Atlantique Burkina Faso",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue de la Nation",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3723,
    longitude: -1.5134,
    telephone: "+226 25 33 33 33",
    email: "contact@banqueatlantique.bf",
    siteWeb: "www.banqueatlantique.net",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Mobile Banking", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 15,
    nombreGAB: 35
  },
  {
    id: "bq-008",
    nom: "Banque Commerciale du Burkina",
    sigle: "BCB",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue Kwamé N'Krumah",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3656,
    longitude: -1.5212,
    telephone: "+226 25 30 62 62",
    email: "bcb@bcb.bf",
    siteWeb: "www.bcb.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 12,
    nombreGAB: 25
  },
  {
    id: "bq-009",
    nom: "Banque de l'Union - Burkina Faso",
    sigle: "BDU-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Immeuble BDU, Avenue de l'Indépendance",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3689,
    longitude: -1.5178,
    telephone: "+226 25 30 74 00",
    email: "bdu@bdu.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 8,
    nombreGAB: 15
  },
  {
    id: "bq-010",
    nom: "Banque Internationale du Burkina",
    sigle: "BIB",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard de la Révolution",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3701,
    longitude: -1.5089,
    telephone: "+226 25 30 85 85",
    email: "bib@bib.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 10,
    nombreGAB: 20
  },
  {
    id: "bq-011",
    nom: "Orabank Burkina",
    sigle: "Orabank",
    type: "Banque",
    categorie: "Régionale",
    adresse: "Avenue du Docteur Kwamé N'Krumah",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3678,
    longitude: -1.5167,
    telephone: "+226 25 49 60 00",
    email: "orabank@orabank.net",
    siteWeb: "www.orabank.net",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits solidaires", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 8,
    nombreGAB: 18
  },
  {
    id: "bq-012",
    nom: "Banque Sahélo-Saharienne pour l'Investissement et le Commerce",
    sigle: "BSIC-Burkina",
    type: "Banque",
    categorie: "Régionale",
    adresse: "Boulevard de la Nation",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3712,
    longitude: -1.5112,
    telephone: "+226 25 31 90 00",
    email: "bsic@bsic.bf",
    siteWeb: "www.bsic.bj",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 6,
    nombreGAB: 12
  },
  {
    id: "bq-013",
    nom: "International Business Bank",
    sigle: "IB Bank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue de l'Habitat, ex-BHBF",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3645,
    longitude: -1.5189,
    telephone: "+226 25 30 88 00",
    email: "ibbank@ibbank.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits immobiliers", "Financement habitat", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 5,
    nombreGAB: 10
  },
  {
    id: "bq-014",
    nom: "CBAO Groupe Attijariwafa Bank",
    sigle: "CBAO",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard de la Nation",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3698,
    longitude: -1.5123,
    telephone: "+226 25 30 77 00",
    email: "cbao@cbao.bf",
    siteWeb: "www.cbao.sn",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 4,
    nombreGAB: 8
  },
  {
    id: "bq-015",
    nom: "Banque Agricole du Faso",
    sigle: "BADF",
    type: "Banque",
    categorie: "Agricole",
    adresse: "Avenue de la Liberté",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3667,
    longitude: -1.5234,
    telephone: "+226 25 30 75 00",
    email: "badf@badf.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits agricoles", "Financement rural", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 15,
    nombreGAB: 25
  },
  {
    id: "bq-016",
    nom: "Banque Postale du Burkina Faso",
    sigle: "BPBF",
    type: "Banque",
    categorie: "Postale",
    adresse: "Immeuble de La Poste, Avenue de la Nation",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3723,
    longitude: -1.5156,
    telephone: "+226 25 30 60 00",
    email: "bpbf@laposte.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne postale", "Transferts", "CCP", "Mandats"],
    hasGAB: true,
    nombreAgences: 45,
    nombreGAB: 30
  },
  {
    id: "bq-017",
    nom: "Wendkuni Bank International",
    sigle: "WBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard Charles de Gaulle",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3689,
    longitude: -1.5201,
    telephone: "+226 25 30 95 00",
    email: "wbi@wbi.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreAgences: 5,
    nombreGAB: 10
  },

  // ========================================
  // AGENCES BANQUES - BOBO-DIOULASSO
  // ========================================
  {
    id: "bq-018",
    nom: "Coris Bank International - Bobo",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard de la Révolution, Centre-ville",
    quartier: "Centre-ville",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1774,
    longitude: -4.2979,
    telephone: "+226 20 97 05 00",
    email: "bobo@coris-bank.com",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires", "GAB 24h"],
    hasGAB: true,
    nombreGAB: 8
  },
  {
    id: "bq-019",
    nom: "Ecobank Bobo-Dioulasso",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue de la République",
    quartier: "Centre-ville",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1789,
    longitude: -4.2945,
    telephone: "+226 20 97 12 00",
    email: "bobo@ecobank.com",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts internationaux", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 5
  },
  {
    id: "bq-020",
    nom: "BOA Bobo-Dioulasso",
    sigle: "BOA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard de la République",
    quartier: "Centre-ville",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1801,
    longitude: -4.2923,
    telephone: "+226 20 97 10 00",
    email: "bobo@boa.bf",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 6
  },
  {
    id: "bq-021",
    nom: "UBA Bobo-Dioulasso",
    sigle: "UBA",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue de la République",
    quartier: "Centre-ville",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1756,
    longitude: -4.3012,
    telephone: "+226 20 97 15 00",
    email: "bobo@ubagroup.com",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 3
  },

  // ========================================
  // AGENCES CORIS BANK - OUAGADOUGOU
  // ========================================
  {
    id: "bq-029",
    nom: "Coris Bank Agence Cissin",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Rue 16.161, Secteur 25",
    quartier: "Cissin",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3389,
    longitude: -1.5312,
    telephone: "+226 25 49 10 48",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-030",
    nom: "Coris Bank Agence Sankaryaare",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue 56, Rue 3.65, Secteur 23",
    quartier: "Sankaryaare",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3512,
    longitude: -1.5423,
    telephone: "+226 25 49 10 38",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-031",
    nom: "Coris Bank Agence Tanghin",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Près de la Pharmacie METEBA, Secteur 22",
    quartier: "Tanghin",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3756,
    longitude: -1.5189,
    telephone: "+226 25 49 10 55",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-032",
    nom: "Coris Bank Agence 1200 Logements",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue Babanguida, 1200 Logements",
    quartier: "1200 Logements",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3589,
    longitude: -1.5067,
    telephone: "+226 25 49 10 32",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-033",
    nom: "Coris Bank Agence Baraka ZACA",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "ZACA, Avenue de l'UEMOA, 400m du Ramada Hôtel",
    quartier: "ZACA",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3712,
    longitude: -1.5089,
    telephone: "+226 25 49 10 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 3
  },
  {
    id: "bq-034",
    nom: "Coris Bank Agence Bendogo",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Axe Ouaga-Fada, Bendogo",
    quartier: "Bendogo",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.4012,
    longitude: -1.4678,
    telephone: "+226 25 49 10 30",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 1
  },

  // ========================================
  // AGENCES ECOBANK - OUAGADOUGOU
  // ========================================
  {
    id: "bq-035",
    nom: "Ecobank Agence Patte d'Oie",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard des Tensoba, Secteur 15",
    quartier: "Patte d'Oie",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3534,
    longitude: -1.5312,
    telephone: "+226 25 30 68 20",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Western Union"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-036",
    nom: "Ecobank Agence Koulouba",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue Ilboudo Waogyandé, Saonré",
    quartier: "Koulouba",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3678,
    longitude: -1.5123,
    telephone: "+226 25 30 68 25",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Western Union"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-037",
    nom: "Ecobank Agence Ouaga 2000",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard France-Afrique, Ouaga 2000",
    quartier: "Ouaga 2000",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3412,
    longitude: -1.4956,
    telephone: "+226 25 30 68 30",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Western Union"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-038",
    nom: "Ecobank Agence Zone Commerciale",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "ZACA, Zone Commerciale",
    quartier: "ZACA",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3698,
    longitude: -1.5078,
    telephone: "+226 07 16 03 04",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Western Union"],
    hasGAB: true,
    nombreGAB: 2
  },

  // ========================================
  // AGENCES VISTA BANK (ex-SOCIETE GENERALE) - OUAGADOUGOU
  // ========================================
  {
    id: "bq-039",
    nom: "Vista Bank Agence 1200 Logements",
    sigle: "Vista Bank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "1200 Logements, Secteur 15",
    quartier: "1200 Logements",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3567,
    longitude: -1.5089,
    telephone: "+226 25 32 32 40",
    horaires: "07h45 - 15h45",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-040",
    nom: "Vista Bank Agence Charles de Gaulle",
    sigle: "Vista Bank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue Charles de Gaulle, Secteur 4",
    quartier: "Charles de Gaulle",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3723,
    longitude: -1.5234,
    telephone: "+226 25 32 32 45",
    horaires: "07h45 - 15h45",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-041",
    nom: "Vista Bank Agence Gounghin",
    sigle: "Vista Bank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue Kadiogo, Secteur 7 Gounghin",
    quartier: "Gounghin",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3612,
    longitude: -1.5378,
    telephone: "+226 25 32 32 50",
    horaires: "07h45 - 15h45",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-042",
    nom: "Vista Bank Agence Nations Unies",
    sigle: "Vista Bank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue des Nations Unies, Secteur 8",
    quartier: "Nations Unies",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3645,
    longitude: -1.5156,
    telephone: "+226 25 32 32 55",
    horaires: "07h45 - 15h45",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-043",
    nom: "Vista Bank Agence Patte d'Oie",
    sigle: "Vista Bank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard des Tensoba, Patte d'Oie",
    quartier: "Patte d'Oie",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3523,
    longitude: -1.5289,
    telephone: "+226 25 32 32 60",
    horaires: "07h45 - 15h45",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-044",
    nom: "Vista Bank Agence Pissy",
    sigle: "Vista Bank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Secteur 51 Pissy",
    quartier: "Pissy",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3423,
    longitude: -1.5534,
    telephone: "+226 25 32 32 65",
    horaires: "07h45 - 15h45",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-045",
    nom: "Vista Bank Agence Somgandé",
    sigle: "Vista Bank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue de Somgandé, Secteur 28",
    quartier: "Somgandé",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3812,
    longitude: -1.5012,
    telephone: "+226 25 32 32 70",
    horaires: "07h45 - 15h45",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-046",
    nom: "Vista Bank Agence ZAD",
    sigle: "Vista Bank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Zone d'Activités Diverses",
    quartier: "ZAD",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3501,
    longitude: -1.4889,
    telephone: "+226 25 32 32 75",
    horaires: "07h45 - 15h45",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreGAB: 1
  },

  // ========================================
  // AGENCES UBA - OUAGADOUGOU
  // ========================================
  {
    id: "bq-047",
    nom: "UBA Agence Marché",
    sigle: "UBA",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Rue du Grand Marché, Patrice Lumumba",
    quartier: "Grand Marché",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3678,
    longitude: -1.5201,
    telephone: "+226 25 32 83 28",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-048",
    nom: "UBA Agence Dapoya",
    sigle: "UBA",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "1913 Avenue de la Liberté",
    quartier: "Dapoya",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3701,
    longitude: -1.5245,
    telephone: "+226 25 30 00 10",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-049",
    nom: "UBA Agence Hamdalaye",
    sigle: "UBA",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "786 Avenue du Gouverneur",
    quartier: "Hamdalaye",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3589,
    longitude: -1.5167,
    telephone: "+226 25 30 00 15",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-050",
    nom: "UBA Agence Aéroport",
    sigle: "UBA",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Aéroport International de Ouagadougou",
    quartier: "Aéroport",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3534,
    longitude: -1.5123,
    telephone: "+226 25 30 00 20",
    horaires: "06h00 - 22h00",
    services: ["Change", "Transferts", "Retraits", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 2
  },

  // ========================================
  // AGENCES EN PROVINCE - AUTRES VILLES
  // ========================================
  {
    id: "bq-051",
    nom: "Vista Bank Bobo-Dioulasso",
    sigle: "Vista Bank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Bobo-Dioulasso",
    quartier: "Centre-ville",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1789,
    longitude: -4.2956,
    telephone: "+226 20 97 33 90",
    horaires: "07h45 - 15h45",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreGAB: 3
  },
  {
    id: "bq-052",
    nom: "Vista Bank Kaya",
    sigle: "Vista Bank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Kaya",
    quartier: "Centre",
    ville: "Kaya",
    region: "Centre-Nord",
    latitude: 13.0889,
    longitude: -1.0823,
    telephone: "+226 25 45 02 00",
    horaires: "07h45 - 15h45",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-053",
    nom: "Vista Bank Manga",
    sigle: "Vista Bank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Manga",
    quartier: "Centre",
    ville: "Manga",
    region: "Centre-Sud",
    latitude: 11.6634,
    longitude: -1.0645,
    telephone: "+226 25 70 01 00",
    horaires: "07h45 - 15h45",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-054",
    nom: "BOA Ouahigouya",
    sigle: "BOA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Ouahigouya",
    quartier: "Centre",
    ville: "Ouahigouya",
    region: "Nord",
    latitude: 13.5801,
    longitude: -2.4201,
    telephone: "+226 24 55 02 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-055",
    nom: "Coris Bank Banfora",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Banfora",
    quartier: "Centre",
    ville: "Banfora",
    region: "Cascades",
    latitude: 10.6289,
    longitude: -4.7589,
    telephone: "+226 20 91 02 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-056",
    nom: "Ecobank Koupéla",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Koupéla",
    quartier: "Centre",
    ville: "Koupéla",
    region: "Centre-Est",
    latitude: 12.1745,
    longitude: -0.3556,
    telephone: "+226 24 70 01 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Western Union"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-057",
    nom: "BOA Fada N'Gourma",
    sigle: "BOA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Fada N'Gourma",
    quartier: "Centre",
    ville: "Fada N'Gourma",
    region: "Est",
    latitude: 12.0601,
    longitude: 0.3456,
    telephone: "+226 24 77 01 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-058",
    nom: "Coris Bank Dori",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Dori",
    quartier: "Centre",
    ville: "Dori",
    region: "Sahel",
    latitude: 14.0312,
    longitude: -0.0267,
    telephone: "+226 24 46 01 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-059",
    nom: "Ecobank Dédougou",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Dédougou",
    quartier: "Centre",
    ville: "Dédougou",
    region: "Boucle du Mouhoun",
    latitude: 12.4601,
    longitude: -3.4589,
    telephone: "+226 20 52 01 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Western Union"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-060",
    nom: "UBA Koudougou",
    sigle: "UBA",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Koudougou",
    quartier: "Centre",
    ville: "Koudougou",
    region: "Centre-Ouest",
    latitude: 12.2556,
    longitude: -2.3712,
    telephone: "+226 25 44 01 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },

  // ========================================
  // CORIS BANK - AGENCES BOBO-DIOULASSO
  // ========================================
  {
    id: "bq-061",
    nom: "Coris Bank Bobo Indépendance",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard Félix Houphouet Boigny face station Shell",
    quartier: "Centre-ville",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1812,
    longitude: -4.2945,
    telephone: "+226 79 44 11 68",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-062",
    nom: "Coris Bank Bobo Marché",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue du Gouverneur William Ponty",
    quartier: "Grand Marché",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1778,
    longitude: -4.2912,
    telephone: "+226 20 98 20 11",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-063",
    nom: "Coris Bank Bobo Prestige",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue Clozel",
    quartier: "Clozel",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1756,
    longitude: -4.2934,
    telephone: "+226 20 97 35 62",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-064",
    nom: "Coris Bank Bobo-SNC",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard de la Révolution, face site SNC",
    quartier: "SNC",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1734,
    longitude: -4.2967,
    telephone: "+226 20 98 01 22",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 1
  },

  // ========================================
  // CORIS BANK - AGENCES VILLES INTÉRIEURES
  // ========================================
  {
    id: "bq-065",
    nom: "Coris Bank Koudougou Academia",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Quartier Burkina, axe Koudougou-Réo",
    quartier: "Burkina",
    ville: "Koudougou",
    region: "Centre-Ouest",
    latitude: 12.2512,
    longitude: -2.3645,
    telephone: "+226 79 82 13 28",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-066",
    nom: "Coris Bank Kaya",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Rue du marché",
    quartier: "Marché",
    ville: "Kaya",
    region: "Centre-Nord",
    latitude: 13.0923,
    longitude: -1.0867,
    telephone: "+226 24 45 09 09",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-067",
    nom: "Coris Bank Dédougou",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Zone Commerciale, Immeuble Drabo Bakary",
    quartier: "Zone Commerciale",
    ville: "Dédougou",
    region: "Boucle du Mouhoun",
    latitude: 12.4634,
    longitude: -3.4623,
    telephone: "+226 20 52 12 25",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-068",
    nom: "Coris Bank Ouahigouya",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Côté château d'eau ONEA",
    quartier: "Centre",
    ville: "Ouahigouya",
    region: "Nord",
    latitude: 13.5834,
    longitude: -2.4245,
    telephone: "+226 40 55 36 58",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-069",
    nom: "Coris Bank Fada N'Gourma",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Route Niger",
    quartier: "Centre",
    ville: "Fada N'Gourma",
    region: "Est",
    latitude: 12.0612,
    longitude: 0.3489,
    telephone: "+226 40 77 05 33",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-070",
    nom: "Coris Bank Gaoua",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Entrée de Ouaga",
    quartier: "Centre",
    ville: "Gaoua",
    region: "Sud-Ouest",
    latitude: 10.3267,
    longitude: -3.1801,
    telephone: "+226 20 90 02 17",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-071",
    nom: "Coris Bank Djibo",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Près de la Gendarmerie Nationale",
    quartier: "Centre",
    ville: "Djibo",
    region: "Sahel",
    latitude: 14.1012,
    longitude: -1.6289,
    telephone: "+226 40 56 08 18",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-072",
    nom: "Coris Bank Cinkansé",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Près de la boulangerie Wend-Konta",
    quartier: "Centre",
    ville: "Cinkansé",
    region: "Centre-Est",
    latitude: 11.1423,
    longitude: 0.0734,
    telephone: "+226 25 39 58 50",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-073",
    nom: "Coris Bank Dano",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Près de la station Petrofa",
    quartier: "Centre",
    ville: "Dano",
    region: "Sud-Ouest",
    latitude: 11.1467,
    longitude: -3.0645,
    telephone: "+226 20 98 80 04",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-074",
    nom: "Coris Bank Houndé",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "À 200m de la station Total",
    quartier: "Centre",
    ville: "Houndé",
    region: "Hauts-Bassins",
    latitude: 11.4912,
    longitude: -3.5189,
    telephone: "+226 78 94 60 25",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-075",
    nom: "Coris Bank Kongoussi",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Rue du marché",
    quartier: "Centre",
    ville: "Kongoussi",
    region: "Centre-Nord",
    latitude: 13.3256,
    longitude: -1.5256,
    telephone: "+226 40 77 05 33",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-076",
    nom: "Coris Bank Koupéla",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Koupéla",
    quartier: "Centre",
    ville: "Koupéla",
    region: "Centre-Est",
    latitude: 12.1756,
    longitude: -0.3567,
    telephone: "+226 24 70 00 40",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-077",
    nom: "Coris Bank Pouytenga",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Route de Boulsa",
    quartier: "Centre",
    ville: "Pouytenga",
    region: "Centre-Est",
    latitude: 12.2423,
    longitude: -0.8334,
    telephone: "+226 40 70 68 88",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-078",
    nom: "Coris Bank Bitou",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Près du poste de douane",
    quartier: "Frontière",
    ville: "Bitou",
    region: "Centre-Est",
    latitude: 11.2145,
    longitude: 0.3067,
    telephone: "+226 24 71 44 12",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },

  // ========================================
  // BANQUE ATLANTIQUE - OUAGADOUGOU
  // ========================================
  {
    id: "bq-079",
    nom: "Banque Atlantique Siège",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Rue de l'Hôtel de Ville, Immeuble Nouria Holding",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3701,
    longitude: -1.5178,
    telephone: "+226 25 49 24 46",
    email: "infobabf@banqueatlantique.net",
    siteWeb: "www.banqueatlantique.net/bf",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "ANET Banque en ligne"],
    hasGAB: true,
    nombreGAB: 3
  },
  {
    id: "bq-080",
    nom: "Banque Atlantique Kwamé Nkrumah",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue Kwamé Nkrumah",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3689,
    longitude: -1.5189,
    telephone: "+226 25 49 24 50",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-081",
    nom: "Banque Atlantique Ouaga 2000",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard France-Afrique, Ouaga 2000",
    quartier: "Ouaga 2000",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3423,
    longitude: -1.4923,
    telephone: "+226 25 49 24 55",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-082",
    nom: "Banque Atlantique Tanghin",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Secteur 22, Tanghin",
    quartier: "Tanghin",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3778,
    longitude: -1.5201,
    telephone: "+226 25 49 24 60",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-083",
    nom: "Banque Atlantique Larlé",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Secteur 17, Larlé",
    quartier: "Larlé",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3612,
    longitude: -1.5289,
    telephone: "+226 25 49 24 65",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-084",
    nom: "Banque Atlantique Rood Wooko",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Grand Marché Rood Wooko",
    quartier: "Rood Wooko",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3667,
    longitude: -1.5223,
    telephone: "+226 25 49 24 70",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-085",
    nom: "Banque Atlantique Sankariaré",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Secteur 23, Sankariaré",
    quartier: "Sankariaré",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3534,
    longitude: -1.5412,
    telephone: "+226 25 49 24 75",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-086",
    nom: "Banque Atlantique Tampouy",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Secteur 52, Tampouy",
    quartier: "Tampouy",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3923,
    longitude: -1.5067,
    telephone: "+226 25 49 24 80",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },

  // ========================================
  // BANQUE ATLANTIQUE - BOBO-DIOULASSO
  // ========================================
  {
    id: "bq-087",
    nom: "Banque Atlantique Bobo Révolution",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Boulevard de la Révolution",
    quartier: "Centre-ville",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1801,
    longitude: -4.2934,
    telephone: "+226 25 49 74 87",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-088",
    nom: "Banque Atlantique Bobo MADY Sanga",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Immeuble MADY Sanga",
    quartier: "Sarfalao",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1778,
    longitude: -4.2956,
    telephone: "+226 25 49 74 80",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-089",
    nom: "Banque Atlantique Bobo Zone Industrielle",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Zone Industrielle",
    quartier: "Zone Industrielle",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1689,
    longitude: -4.3012,
    telephone: "+226 25 49 74 85",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },

  // ========================================
  // BANQUE ATLANTIQUE - VILLES INTÉRIEURES
  // ========================================
  {
    id: "bq-090",
    nom: "Banque Atlantique Cinkansé",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Route du Togo, face Commissariat Police",
    quartier: "Frontière",
    ville: "Cinkansé",
    region: "Centre-Est",
    latitude: 11.1434,
    longitude: 0.0756,
    telephone: "+226 25 49 74 37",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-091",
    nom: "Banque Atlantique Dédougou",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Face 23ème Régiment Infanterie Commando",
    quartier: "Centre",
    ville: "Dédougou",
    region: "Boucle du Mouhoun",
    latitude: 12.4645,
    longitude: -3.4634,
    telephone: "+226 25 49 74 93",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-092",
    nom: "Banque Atlantique Kaya",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Secteur 3, Boulangerie Wendkonta",
    quartier: "Secteur 3",
    ville: "Kaya",
    region: "Centre-Nord",
    latitude: 13.0934,
    longitude: -1.0878,
    telephone: "+226 25 49 74 40",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-093",
    nom: "Banque Atlantique Koudougou",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue DREUX, 15m de l'ancienne gare Staf",
    quartier: "Centre",
    ville: "Koudougou",
    region: "Centre-Ouest",
    latitude: 12.2567,
    longitude: -2.3723,
    telephone: "+226 25 49 74 90",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-094",
    nom: "Banque Atlantique Koupéla",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Route de Fada",
    quartier: "Centre",
    ville: "Koupéla",
    region: "Centre-Est",
    latitude: 12.1767,
    longitude: -0.3589,
    telephone: "+226 25 49 74 45",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-095",
    nom: "Banque Atlantique Ouahigouya",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Immeuble évêché, face OCADES",
    quartier: "Centre",
    ville: "Ouahigouya",
    region: "Nord",
    latitude: 13.5845,
    longitude: -2.4234,
    telephone: "+226 25 49 74 97",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-096",
    nom: "Banque Atlantique Pouytenga",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Face au marché central",
    quartier: "Marché",
    ville: "Pouytenga",
    region: "Centre-Est",
    latitude: 12.2434,
    longitude: -0.8345,
    telephone: "+226 25 49 74 43",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-097",
    nom: "Banque Atlantique Tenkodogo",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Tenkodogo",
    quartier: "Centre",
    ville: "Tenkodogo",
    region: "Centre-Est",
    latitude: 11.7823,
    longitude: -0.3701,
    telephone: "+226 24 71 00 01",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-098",
    nom: "Banque Atlantique Banfora",
    sigle: "BA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Banfora",
    quartier: "Centre",
    ville: "Banfora",
    region: "Cascades",
    latitude: 10.6301,
    longitude: -4.7578,
    telephone: "+226 25 49 74 35",
    horaires: "07h30 - 16h30",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },

  // ========================================
  // ECOBANK - AGENCES BOBO-DIOULASSO
  // ========================================
  {
    id: "bq-099",
    nom: "Ecobank Bobo Alwata Diawara",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "2025 Avenue Alwata Diawara",
    quartier: "Alwata Diawara",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1812,
    longitude: -4.2923,
    telephone: "+226 25 33 33 33",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Western Union"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-100",
    nom: "Ecobank Bobo Pepin Malherbe",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "462 Rue Pepin Malherbe",
    quartier: "Pepin Malherbe",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1789,
    longitude: -4.2945,
    telephone: "+226 25 33 33 33",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Western Union"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-101",
    nom: "Ecobank Bobo Route Ouaga",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Nationale N°1 Route de Ouaga",
    quartier: "Route Ouaga",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1734,
    longitude: -4.2856,
    telephone: "+226 25 33 33 33",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Western Union"],
    hasGAB: true,
    nombreGAB: 1
  },

  // ========================================
  // UBA - AGENCES SUPPLÉMENTAIRES
  // ========================================
  {
    id: "bq-102",
    nom: "UBA Ouahigouya",
    sigle: "UBA",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "228 Avenue de Mopti",
    quartier: "Centre",
    ville: "Ouahigouya",
    region: "Nord",
    latitude: 13.5812,
    longitude: -2.4212,
    telephone: "+226 25 44 07 08",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-103",
    nom: "UBA Dédougou",
    sigle: "UBA",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "RN 10 Zone administrative",
    quartier: "Zone administrative",
    ville: "Dédougou",
    region: "Boucle du Mouhoun",
    latitude: 12.4656,
    longitude: -3.4645,
    telephone: "+226 20 52 00 11",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-104",
    nom: "UBA Fada N'Gourma",
    sigle: "UBA",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Fada N'Gourma",
    quartier: "Centre",
    ville: "Fada N'Gourma",
    region: "Est",
    latitude: 12.0623,
    longitude: 0.3467,
    telephone: "+226 24 77 00 15",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes Visa/Mastercard"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-105",
    nom: "UBA Dori",
    sigle: "UBA",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Dori",
    quartier: "Centre",
    ville: "Dori",
    region: "Sahel",
    latitude: 14.0323,
    longitude: -0.0278,
    telephone: "+226 24 46 00 10",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-106",
    nom: "UBA Gaoua",
    sigle: "UBA",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Gaoua",
    quartier: "Centre",
    ville: "Gaoua",
    region: "Sud-Ouest",
    latitude: 10.3278,
    longitude: -3.1812,
    telephone: "+226 20 90 00 15",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-107",
    nom: "UBA Manga",
    sigle: "UBA",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Manga",
    quartier: "Centre",
    ville: "Manga",
    region: "Centre-Sud",
    latitude: 11.6645,
    longitude: -1.0656,
    telephone: "+226 25 70 00 10",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },
  {
    id: "bq-108",
    nom: "UBA Houndé",
    sigle: "UBA",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Zone minière Houndé",
    quartier: "Centre",
    ville: "Houndé",
    region: "Hauts-Bassins",
    latitude: 11.4923,
    longitude: -3.5201,
    telephone: "+226 20 53 00 10",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 1
  },

  // ========================================
  // CAISSES POPULAIRES - RCPB
  // ========================================
  {
    id: "cp-001",
    nom: "Faîtière des Caisses Populaires du Burkina",
    sigle: "FCPB",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Avenue Pascal Zagré, Ouaga 2000, face Hôtel Lancaster",
    quartier: "Ouaga 2000",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3456,
    longitude: -1.4889,
    telephone: "+226 25 37 42 85",
    email: "fcpb@rcpb.bf",
    siteWeb: "www.rcpb.bf",
    horaires: "08h00 - 16h00",
    services: ["Épargne", "Crédits", "Transferts", "Micro-assurance", "Mobile Money RCPB"],
    hasGAB: true,
    nombreAgences: 212,
    nombreGAB: 50
  },
  {
    id: "cp-002",
    nom: "Délégation Centre des Caisses Populaires",
    sigle: "DCPC",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Secteur 15, Ouagadougou",
    quartier: "Secteur 15",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3567,
    longitude: -1.5234,
    telephone: "+226 25 50 60 80",
    email: "dcpc@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts", "Micro-assurance"],
    hasGAB: true
  },
  {
    id: "cp-003",
    nom: "Caisse Populaire Song-Taaba",
    sigle: "CP Song-Taaba",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Rue Manegm Noore (29.30), Secteur 29 Wemtenga",
    quartier: "Wemtenga",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3789,
    longitude: -1.5012,
    telephone: "+226 25 36 88 00",
    email: "songataaba@rcpb.bf",
    horaires: "07h30 - 17h00, Samedi 07h30 - 12h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-004",
    nom: "Caisse Populaire de Tampouy",
    sigle: "CP Tampouy",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Avenue de Tampouy, Secteur 52",
    quartier: "Tampouy",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3912,
    longitude: -1.5045,
    telephone: "+226 25 36 55 00",
    email: "tampouy@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },
  {
    id: "cp-005",
    nom: "Caisse Populaire de Pissy",
    sigle: "CP Pissy",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Pissy, Secteur 51",
    quartier: "Pissy",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3456,
    longitude: -1.5512,
    telephone: "+226 25 45 72 00",
    email: "pissy@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-006",
    nom: "Délégation Ouest des Caisses Populaires",
    sigle: "DCPO",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Rue 6.88, Secteur 6",
    quartier: "Secteur 6",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1789,
    longitude: -4.2912,
    telephone: "+226 20 97 33 97",
    email: "dcpo2@rcpb.bf",
    horaires: "08h00 - 16h00",
    services: ["Épargne", "Crédits", "Transferts", "Micro-assurance"],
    hasGAB: true
  },
  {
    id: "cp-007",
    nom: "Délégation Nord des Caisses Populaires",
    sigle: "DCPN",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Centre-ville Ouahigouya",
    quartier: "Centre",
    ville: "Ouahigouya",
    region: "Nord",
    latitude: 13.5823,
    longitude: -2.4223,
    telephone: "+226 24 55 05 75",
    email: "dcpn@rcpb.bf",
    horaires: "08h00 - 16h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },
  {
    id: "cp-008",
    nom: "Délégation Est des Caisses Populaires",
    sigle: "DCPE",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Centre-ville Koupéla",
    quartier: "Centre",
    ville: "Koupéla",
    region: "Centre-Est",
    latitude: 12.1767,
    longitude: -0.3578,
    telephone: "+226 24 70 03 30",
    email: "dcpe@rcpb.bf",
    horaires: "08h00 - 16h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },
  {
    id: "cp-009",
    nom: "Délégation Sud-Ouest des Caisses Populaires",
    sigle: "DCPSO",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Centre-ville Diébougou",
    quartier: "Centre",
    ville: "Diébougou",
    region: "Sud-Ouest",
    latitude: 10.9667,
    longitude: -3.2500,
    telephone: "+226 20 90 53 90",
    email: "dcpso@rcpb.bf",
    horaires: "08h00 - 16h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  // ========================================
  // CAISSES POPULAIRES RCPB - REGION CENTRE (12)
  // ========================================
  {
    id: "cp-010",
    nom: "Caisse Populaire de Cissin",
    sigle: "CP Cissin",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle 06 lot 06 section IL, Secteur 25",
    quartier: "Cissin",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3412,
    longitude: -1.5289,
    telephone: "+226 70 29 60 10",
    email: "cp-cissin@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts", "Mobile Money"],
    hasGAB: true
  },
  {
    id: "cp-011",
    nom: "Caisse Populaire de Dassasgho",
    sigle: "CP Dassasgho",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle 01 Lot 17 Section W, Secteur 21, Rue des Archives Nationales",
    quartier: "Dassasgho",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3534,
    longitude: -1.4978,
    telephone: "+226 70 27 27 83",
    email: "cp-dassasgho@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-012",
    nom: "Caisse Populaire de Gounghin",
    sigle: "CP Gounghin",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle H du lot 145 section Gounghin Nord, Secteur 07, Route Nationale 1 Avenue Kadiogo",
    quartier: "Gounghin",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3623,
    longitude: -1.5345,
    telephone: "+226 72 36 13 18",
    email: "cp-gounghin@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },
  {
    id: "cp-013",
    nom: "Caisse Populaire de Dapoya",
    sigle: "CP Dapoya",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle B du lot 130, Secteur 11, Avenue de la Liberté",
    quartier: "Dapoya",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3689,
    longitude: -1.5234,
    telephone: "+226 70 88 91 04",
    email: "cp-dapoya@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-014",
    nom: "Caisse Populaire de Sig-noghin",
    sigle: "CP Sig-noghin",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle 12 du lot 1 section 363, Secteur 15, Route Nationale 2 Avenue Yatenga",
    quartier: "Sig-noghin",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3845,
    longitude: -1.4923,
    telephone: "+226 64 85 30 22",
    email: "cp-signoghin@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-015",
    nom: "Caisse Populaire de Léo",
    sigle: "CP Léo",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle G du lot 47 section Zone commerciale, Secteur 01, face à l'ancienne Mairie",
    quartier: "Centre-ville",
    ville: "Léo",
    region: "Centre-Ouest",
    latitude: 11.0956,
    longitude: -2.1012,
    telephone: "+226 72 36 13 34",
    email: "cp-leo@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-016",
    nom: "Caisse Populaire de Pô",
    sigle: "CP Pô",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Secteur 03, Commune de Pô",
    quartier: "Secteur 03",
    ville: "Pô",
    region: "Centre-Sud",
    latitude: 11.1667,
    longitude: -1.1500,
    telephone: "+226 71 93 05 31",
    email: "cp-po@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-017",
    nom: "Caisse Populaire de Manga",
    sigle: "CP Manga",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle M du lot 03, Secteur 03",
    quartier: "Secteur 03",
    ville: "Manga",
    region: "Centre-Sud",
    latitude: 11.6667,
    longitude: -1.0667,
    telephone: "+226 71 43 94 00",
    email: "cp-manga@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-018",
    nom: "Caisse Populaire de Sabou",
    sigle: "CP Sabou",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle 02 du lot 16 section AM, Route Nationale 1",
    quartier: "Centre-ville",
    ville: "Sabou",
    region: "Centre-Ouest",
    latitude: 12.0623,
    longitude: -2.2456,
    telephone: "+226 72 14 60 00",
    email: "cp-sabou@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-019",
    nom: "Caisse Populaire de Koudougou",
    sigle: "CP Koudougou",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle M du lot 344, Route Nationale 14",
    quartier: "Centre-ville",
    ville: "Koudougou",
    region: "Centre-Ouest",
    latitude: 12.2534,
    longitude: -2.3678,
    telephone: "+226 72 14 60 03",
    email: "cp-koudougou@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },
  {
    id: "cp-020",
    nom: "Caisse Populaire de Kaya",
    sigle: "CP Kaya",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle B du lot 75, Secteur 03",
    quartier: "Secteur 03",
    ville: "Kaya",
    region: "Centre-Nord",
    latitude: 13.0912,
    longitude: -1.0845,
    telephone: "+226 70 73 26 67",
    email: "cp-kaya@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },

  // ========================================
  // CAISSES POPULAIRES RCPB - REGION OUEST (7)
  // ========================================
  {
    id: "cp-021",
    nom: "Caisse Populaire de Dédougou",
    sigle: "CP Dédougou",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Route Nationale 10, face au Stade communal, Secteur 02",
    quartier: "Secteur 02",
    ville: "Dédougou",
    region: "Boucle du Mouhoun",
    latitude: 12.4623,
    longitude: -3.4612,
    telephone: "+226 60 70 31 21",
    email: "cp-dedougou@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },
  {
    id: "cp-022",
    nom: "Caisse Populaire Farakan",
    sigle: "CP Farakan",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle A lot 708, Secteur 1, Boulevard de la Révolution",
    quartier: "Farakan",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1823,
    longitude: -4.2934,
    telephone: "+226 70 32 77 90",
    email: "cp-farakan@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },
  {
    id: "cp-023",
    nom: "Caisse Populaire Dafra",
    sigle: "CP Dafra",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle P du lot 1220, Secteur 15 Ouezin-ville, Boulevard de la Révolution",
    quartier: "Ouezin-ville",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1756,
    longitude: -4.3012,
    telephone: "+226 70 44 85 10",
    email: "cp-dafra@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-024",
    nom: "Caisse Populaire Colma",
    sigle: "CP Colma",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle F lot 2092, Secteur 11, après l'ENSP, face au marché de Nieneta",
    quartier: "Colma",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1634,
    longitude: -4.2856,
    telephone: "+226 70 45 60 61",
    email: "cp-colma@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-025",
    nom: "Caisse Populaire Cascades",
    sigle: "CP Cascades",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle 02 du lot 04 section AH, Secteur 01, à côté de la Croix Rouge",
    quartier: "Secteur 01",
    ville: "Banfora",
    region: "Cascades",
    latitude: 10.6312,
    longitude: -4.7567,
    telephone: "+226 71 70 56 48",
    email: "cp-cascades@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },
  {
    id: "cp-026",
    nom: "Caisse Populaire d'Orodara",
    sigle: "CP Orodara",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle 00 du lot 81, Rue 8, Marché central, 35m de la station Shell",
    quartier: "Marché central",
    ville: "Orodara",
    region: "Hauts-Bassins",
    latitude: 10.9734,
    longitude: -4.9123,
    telephone: "+226 60 50 44 15",
    email: "cp-orodara@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-027",
    nom: "Caisse Populaire Colsama",
    sigle: "CP Colsama",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle 03 du lot 2474, Secteur 21, près de la Boulangerie Wendkonta",
    quartier: "Colsama",
    ville: "Bobo-Dioulasso",
    region: "Hauts-Bassins",
    latitude: 11.1512,
    longitude: -4.2789,
    telephone: "+226 70 12 62 69",
    email: "cp-colsama@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },

  // ========================================
  // CAISSES POPULAIRES RCPB - REGION EST (5)
  // ========================================
  {
    id: "cp-028",
    nom: "Caisse Populaire de Tenkodogo",
    sigle: "CP Tenkodogo",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle 255-C du lot 255, Secteur 6",
    quartier: "Secteur 6",
    ville: "Tenkodogo",
    region: "Centre-Est",
    latitude: 11.7812,
    longitude: -0.3689,
    telephone: "+226 71 04 76 96",
    email: "cp-tenkodogo@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },
  {
    id: "cp-029",
    nom: "Caisse Populaire de Fada N'Gourma",
    sigle: "CP Fada",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle B5 du lot 49, Secteur 10",
    quartier: "Secteur 10",
    ville: "Fada N'Gourma",
    region: "Est",
    latitude: 12.0623,
    longitude: 0.3478,
    telephone: "+226 73 16 50 95",
    email: "cp-fada@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },
  {
    id: "cp-030",
    nom: "Caisse Populaire de Koupéla",
    sigle: "CP Koupéla",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle D du lot 79, Secteur 3, bord de la RN4",
    quartier: "Secteur 3",
    ville: "Koupéla",
    region: "Centre-Est",
    latitude: 12.1767,
    longitude: -0.3578,
    telephone: "+226 72 68 02 01",
    email: "cp-koupela@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },
  {
    id: "cp-031",
    nom: "Caisse Populaire de Boulsa",
    sigle: "CP Boulsa",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle 0000253/205, Secteur 6, Route Nationale 15",
    quartier: "Secteur 6",
    ville: "Boulsa",
    region: "Centre-Nord",
    latitude: 12.6523,
    longitude: -0.5734,
    telephone: "+226 73 75 84 31",
    email: "cp-boulsa@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-032",
    nom: "Caisse Populaire de Bogandé",
    sigle: "CP Bogandé",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle A du lot 54, Secteur 03, côté Est de la RN18",
    quartier: "Secteur 03",
    ville: "Bogandé",
    region: "Est",
    latitude: 12.9689,
    longitude: -0.1423,
    telephone: "+226 60 32 33 63",
    email: "cp-bogande@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },

  // ========================================
  // CAISSES POPULAIRES RCPB - REGION NORD (5)
  // ========================================
  {
    id: "cp-033",
    nom: "Caisse Populaire de Dori",
    sigle: "CP Dori",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Secteur 1, face rue 41",
    quartier: "Secteur 1",
    ville: "Dori",
    region: "Sahel",
    latitude: 14.0334,
    longitude: -0.0289,
    telephone: "+226 61 10 72 48",
    email: "cp-dori@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-034",
    nom: "Caisse Populaire de Ouahigouya",
    sigle: "CP Ouahigouya",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle Nord-Ouest du lot 221, Secteur 6",
    quartier: "Secteur 6",
    ville: "Ouahigouya",
    region: "Nord",
    latitude: 13.5823,
    longitude: -2.4223,
    telephone: "+226 70 32 25 00",
    email: "cp-ouahigouya@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: true
  },
  {
    id: "cp-035",
    nom: "Caisse Populaire de Yako",
    sigle: "CP Yako",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle D du lot 66 section AB, Secteur 3",
    quartier: "Secteur 3",
    ville: "Yako",
    region: "Nord",
    latitude: 12.9567,
    longitude: -2.2612,
    telephone: "+226 71 05 54 36",
    email: "cp-yako@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-036",
    nom: "Caisse Populaire de Gourcy",
    sigle: "CP Gourcy",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle 1 du lot 1 section AM, Secteur 3",
    quartier: "Secteur 3",
    ville: "Gourcy",
    region: "Nord",
    latitude: 13.2045,
    longitude: -2.3567,
    telephone: "+226 70 62 51 94",
    email: "cp-gourcy@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-037",
    nom: "Caisse Populaire de Kongoussi",
    sigle: "CP Kongoussi",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle 0000002/205 du lot 87, Secteur 3",
    quartier: "Secteur 3",
    ville: "Kongoussi",
    region: "Centre-Nord",
    latitude: 13.3234,
    longitude: -1.5234,
    telephone: "+226 61 18 30 38",
    email: "cp-kongoussi@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },

  // ========================================
  // CAISSES POPULAIRES RCPB - REGION SUD-OUEST (3)
  // ========================================
  {
    id: "cp-038",
    nom: "Caisse Populaire de Gaoua",
    sigle: "CP Gaoua",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle 01 du lot 36 section 009, Secteur 02",
    quartier: "Secteur 02",
    ville: "Gaoua",
    region: "Sud-Ouest",
    latitude: 10.3256,
    longitude: -3.1789,
    telephone: "+226 70 15 20 05",
    email: "cp-gaoua@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-039",
    nom: "Caisse Populaire de Dano",
    sigle: "CP Dano",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Parcelle 01 du lot 09 section AG, Route Nationale 11, Secteur 02",
    quartier: "Secteur 02",
    ville: "Dano",
    region: "Sud-Ouest",
    latitude: 11.1456,
    longitude: -3.0623,
    telephone: "+226 70 68 63 90",
    email: "cp-dano@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },
  {
    id: "cp-040",
    nom: "Caisse Populaire de Boromo",
    sigle: "CP Boromo",
    type: "Caisse Populaire",
    categorie: "Microfinance",
    adresse: "Secteur 4, Commune de Boromo",
    quartier: "Secteur 4",
    ville: "Boromo",
    region: "Boucle du Mouhoun",
    latitude: 11.7456,
    longitude: -2.9234,
    telephone: "+226 73 64 75 01",
    email: "cp-boromo@rcpb.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Crédits", "Transferts"],
    hasGAB: false
  },

  // ========================================
  // AUTRES INSTITUTIONS DE MICROFINANCE
  // ========================================
  {
    id: "mf-001",
    nom: "PAMF - Première Agence de Microfinance",
    sigle: "PAMF",
    type: "Microfinance",
    categorie: "Microfinance",
    adresse: "Avenue Yennenga, Secteur 4",
    quartier: "Secteur 4",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3689,
    longitude: -1.5167,
    telephone: "+226 25 33 77 00",
    email: "pamf@pamf.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Micro-crédits", "Tontines", "Transferts"],
    hasGAB: false
  },
  {
    id: "mf-002",
    nom: "FINADEV",
    sigle: "FINADEV",
    type: "Microfinance",
    categorie: "Microfinance",
    adresse: "Boulevard de la Révolution",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Centre",
    latitude: 12.3712,
    longitude: -1.5089,
    telephone: "+226 25 30 90 00",
    email: "finadev@finadev.bf",
    horaires: "07h30 - 17h00",
    services: ["Épargne", "Micro-crédits", "Transferts"],
    hasGAB: false
  },

  // ========================================
  // AGENCES RÉGIONALES
  // ========================================
  {
    id: "bq-022",
    nom: "Coris Bank Koudougou",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Avenue principale, Centre-ville",
    quartier: "Centre-ville",
    ville: "Koudougou",
    region: "Centre-Ouest",
    latitude: 12.2578,
    longitude: -2.3789,
    telephone: "+226 25 44 10 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts", "Cartes bancaires"],
    hasGAB: true,
    nombreGAB: 3
  },
  {
    id: "bq-023",
    nom: "BOA Koudougou",
    sigle: "BOA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Route Nationale 1",
    quartier: "Centre-ville",
    ville: "Koudougou",
    region: "Centre-Ouest",
    latitude: 12.2545,
    longitude: -2.3756,
    telephone: "+226 25 44 12 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-024",
    nom: "Ecobank Ouahigouya",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Ouahigouya",
    quartier: "Centre",
    ville: "Ouahigouya",
    region: "Nord",
    latitude: 13.5789,
    longitude: -2.4189,
    telephone: "+226 24 55 10 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-025",
    nom: "Coris Bank Fada N'Gourma",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville",
    quartier: "Centre",
    ville: "Fada N'Gourma",
    region: "Est",
    latitude: 12.0623,
    longitude: 0.3478,
    telephone: "+226 24 77 05 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-026",
    nom: "Ecobank Banfora",
    sigle: "Ecobank",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Banfora",
    quartier: "Centre",
    ville: "Banfora",
    region: "Cascades",
    latitude: 10.6312,
    longitude: -4.7567,
    telephone: "+226 20 91 10 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-027",
    nom: "BOA Dédougou",
    sigle: "BOA-BF",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville Dédougou",
    quartier: "Centre",
    ville: "Dédougou",
    region: "Boucle du Mouhoun",
    latitude: 12.4623,
    longitude: -3.4612,
    telephone: "+226 20 52 10 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  },
  {
    id: "bq-028",
    nom: "Coris Bank Tenkodogo",
    sigle: "CBI",
    type: "Banque",
    categorie: "Commerciale",
    adresse: "Centre-ville",
    quartier: "Centre",
    ville: "Tenkodogo",
    region: "Centre-Est",
    latitude: 11.7812,
    longitude: -0.3689,
    telephone: "+226 25 71 10 00",
    horaires: "07h30 - 16h00",
    services: ["Comptes courants", "Épargne", "Crédits", "Transferts"],
    hasGAB: true,
    nombreGAB: 2
  }
];

// Statistiques des banques
export function getBanquesStats() {
  const total = BANQUES_DATA.length;
  const banques = BANQUES_DATA.filter(b => b.type === "Banque").length;
  const caissesPopulaires = BANQUES_DATA.filter(b => b.type === "Caisse Populaire").length;
  const microfinance = BANQUES_DATA.filter(b => b.type === "Microfinance").length;
  const avecGAB = BANQUES_DATA.filter(b => b.hasGAB).length;
  const totalGAB = BANQUES_DATA.reduce((acc, b) => acc + (b.nombreGAB || 0), 0);
  const totalAgences = BANQUES_DATA.reduce((acc, b) => acc + (b.nombreAgences || 0), 0);
  const importanceSystemique = BANQUES_DATA.filter(b => b.importanceSystemique).length;
  
  const parType: Record<string, number> = {};
  const parCategorie: Record<string, number> = {};
  const parRegion: Record<string, number> = {};
  const parVille: Record<string, number> = {};
  
  BANQUES_DATA.forEach(b => {
    parType[b.type] = (parType[b.type] || 0) + 1;
    parCategorie[b.categorie] = (parCategorie[b.categorie] || 0) + 1;
    parRegion[b.region] = (parRegion[b.region] || 0) + 1;
    parVille[b.ville] = (parVille[b.ville] || 0) + 1;
  });
  
  return {
    total,
    banques,
    caissesPopulaires,
    microfinance,
    avecGAB,
    totalGAB,
    totalAgences,
    importanceSystemique,
    parType,
    parCategorie,
    parRegion,
    nombreVilles: Object.keys(parVille).length
  };
}
