export interface MairiePrefecture {
  id: string;
  nom: string;
  type: "Mairie" | "Prefecture" | "Haut-Commissariat" | "Gouvernorat";
  adresse: string;
  quartier: string;
  ville: string;
  province: string;
  region: string;
  latitude: number;
  longitude: number;
  telephone?: string;
  telephoneSecondaire?: string;
  email?: string;
  website?: string;
  horaires: string;
  services: string[];
  responsable?: string;
  titreResponsable?: string;
}

export const GOUVERNORATS: MairiePrefecture[] = [
  {
    id: "gouv-kadiogo",
    nom: "Gouvernorat de la Region du Kadiogo",
    type: "Gouvernorat",
    adresse: "Avenue de la Liberte",
    quartier: "Ouaga 2000",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3456,
    longitude: -1.5120,
    telephone: "+226 25 30 67 00",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil", "Affaires foncieres"],
    titreResponsable: "Gouverneur"
  },
  {
    id: "gouv-guiriko",
    nom: "Gouvernorat de la Region du Guiriko",
    type: "Gouvernorat",
    adresse: "Route de Sikasso",
    quartier: "Secteur 1",
    ville: "Bobo-Dioulasso",
    province: "Houet",
    region: "Guiriko",
    latitude: 11.1771,
    longitude: -4.2979,
    telephone: "+226 20 97 00 63",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil", "Affaires foncieres"],
    titreResponsable: "Gouverneur"
  },
  {
    id: "gouv-tannounyan",
    nom: "Gouvernorat de la Region du Tannounyan",
    type: "Gouvernorat",
    adresse: "Avenue de la Republique",
    quartier: "Secteur 1",
    ville: "Banfora",
    province: "Comoe",
    region: "Tannounyan",
    latitude: 10.6330,
    longitude: -4.7670,
    telephone: "+226 20 91 01 06",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil"],
    titreResponsable: "Gouverneur"
  },
  {
    id: "gouv-bankui",
    nom: "Gouvernorat de la Region du Bankui",
    type: "Gouvernorat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Dedougou",
    province: "Mouhoun",
    region: "Bankui",
    latitude: 12.4633,
    longitude: -3.4608,
    telephone: "+226 20 52 01 27",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil"],
    titreResponsable: "Gouverneur"
  },
  {
    id: "gouv-kuilse",
    nom: "Gouvernorat de la Region du Kuilse",
    type: "Gouvernorat",
    adresse: "Route Nationale 15",
    quartier: "Secteur 1",
    ville: "Kaya",
    province: "Sanmatenga",
    region: "Kuilse",
    latitude: 13.0910,
    longitude: -1.0840,
    telephone: "+226 25 45 30 02",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil"],
    titreResponsable: "Gouverneur"
  },
  {
    id: "gouv-goulmou",
    nom: "Gouvernorat de la Region du Goulmou",
    type: "Gouvernorat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Fada N'Gourma",
    province: "Gourma",
    region: "Goulmou",
    latitude: 12.0600,
    longitude: 0.3500,
    telephone: "+226 24 77 01 53",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil"],
    titreResponsable: "Gouverneur"
  },
  {
    id: "gouv-nando",
    nom: "Gouvernorat de la Region du Nando",
    type: "Gouvernorat",
    adresse: "Avenue de la Revolution",
    quartier: "Secteur 1",
    ville: "Koudougou",
    province: "Boulkiemde",
    region: "Nando",
    latitude: 12.2536,
    longitude: -2.3633,
    telephone: "+226 25 44 00 82",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil"],
    titreResponsable: "Gouverneur"
  },
  {
    id: "gouv-nakambe",
    nom: "Gouvernorat de la Region du Nakambe",
    type: "Gouvernorat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Tenkodogo",
    province: "Boulgou",
    region: "Nakambe",
    latitude: 11.7800,
    longitude: -0.3700,
    telephone: "+226 25 41 01 55",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil"],
    titreResponsable: "Gouverneur"
  },
  {
    id: "gouv-yaadga",
    nom: "Gouvernorat de la Region du Yaadga",
    type: "Gouvernorat",
    adresse: "Avenue de la Reconciliation",
    quartier: "Secteur 1",
    ville: "Ouahigouya",
    province: "Yatenga",
    region: "Yaadga",
    latitude: 13.5824,
    longitude: -2.4230,
    telephone: "+226 25 55 00 57",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil"],
    titreResponsable: "Gouverneur"
  },
  {
    id: "gouv-liptako",
    nom: "Gouvernorat de la Region du Liptako",
    type: "Gouvernorat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Dori",
    province: "Seno",
    region: "Liptako",
    latitude: 14.0354,
    longitude: -0.0340,
    telephone: "+226 24 46 01 06",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil"],
    titreResponsable: "Gouverneur"
  },
  {
    id: "gouv-djoro",
    nom: "Gouvernorat de la Region du Djoro",
    type: "Gouvernorat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Gaoua",
    province: "Poni",
    region: "Djoro",
    latitude: 10.3250,
    longitude: -3.1750,
    telephone: "+226 20 87 00 43",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil"],
    titreResponsable: "Gouverneur"
  },
  {
    id: "gouv-nazinon",
    nom: "Gouvernorat de la Region du Nazinon",
    type: "Gouvernorat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Leo",
    province: "Sissili",
    region: "Nazinon",
    latitude: 11.0960,
    longitude: -2.1010,
    telephone: "+226 25 40 60 03",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil"],
    titreResponsable: "Gouverneur"
  },
  {
    id: "gouv-oubri",
    nom: "Gouvernorat de la Region du Oubri",
    type: "Gouvernorat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Ziniare",
    province: "Oubritenga",
    region: "Oubri",
    latitude: 12.5827,
    longitude: -1.2968,
    telephone: "+226 25 40 70 45",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil"],
    titreResponsable: "Gouverneur"
  },
  {
    id: "gouv-sirba",
    nom: "Gouvernorat de la Region du Sirba",
    type: "Gouvernorat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Bogande",
    province: "Gnagna",
    region: "Sirba",
    latitude: 12.9690,
    longitude: -0.1380,
    telephone: "+226 24 79 01 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil"],
    titreResponsable: "Gouverneur"
  },
  {
    id: "gouv-soum",
    nom: "Gouvernorat de la Region du Soum",
    type: "Gouvernorat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Djibo",
    province: "Soum",
    region: "Soum",
    latitude: 14.0990,
    longitude: -1.6300,
    telephone: "+226 24 53 01 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil"],
    titreResponsable: "Gouverneur"
  },
  {
    id: "gouv-sourou",
    nom: "Gouvernorat de la Region du Sourou",
    type: "Gouvernorat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Tougan",
    province: "Sourou",
    region: "Sourou",
    latitude: 13.0720,
    longitude: -3.0700,
    telephone: "+226 20 53 01 14",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil"],
    titreResponsable: "Gouverneur"
  },
  {
    id: "gouv-tapoa",
    nom: "Gouvernorat de la Region du Tapoa",
    type: "Gouvernorat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Diapaga",
    province: "Tapoa",
    region: "Tapoa",
    latitude: 12.0740,
    longitude: 1.7880,
    telephone: "+226 24 79 10 02",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration regionale", "Coordination provinciale", "Securite", "Etat civil"],
    titreResponsable: "Gouverneur"
  }
];

export const HAUTS_COMMISSARIATS: MairiePrefecture[] = [
  {
    id: "hc-kadiogo",
    nom: "Haut-Commissariat de la Province du Kadiogo",
    type: "Haut-Commissariat",
    adresse: "Avenue Kwame N'Krumah",
    quartier: "Centre",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3657,
    longitude: -1.5197,
    telephone: "+226 25 30 67 50",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil", "Affaires foncieres", "Coordination communale"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-houet",
    nom: "Haut-Commissariat de la Province du Houet",
    type: "Haut-Commissariat",
    adresse: "Avenue de la Revolution",
    quartier: "Secteur 1",
    ville: "Bobo-Dioulasso",
    province: "Houet",
    region: "Guiriko",
    latitude: 11.1773,
    longitude: -4.2920,
    telephone: "+226 20 97 06 90",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil", "Affaires foncieres"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-comoe",
    nom: "Haut-Commissariat de la Province de la Comoe",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Banfora",
    province: "Comoe",
    region: "Tannounyan",
    latitude: 10.6325,
    longitude: -4.7643,
    telephone: "+226 20 91 01 37",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil", "Affaires foncieres"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-leraba",
    nom: "Haut-Commissariat de la Province de la Leraba",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Sindou",
    province: "Leraba",
    region: "Tannounyan",
    latitude: 10.6670,
    longitude: -5.1680,
    telephone: "+226 20 91 40 13",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-mouhoun",
    nom: "Haut-Commissariat de la Province du Mouhoun",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Dedougou",
    province: "Mouhoun",
    region: "Bankui",
    latitude: 12.4628,
    longitude: -3.4585,
    telephone: "+226 20 52 01 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil", "Affaires foncieres"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-bale",
    nom: "Haut-Commissariat de la Province du Bale",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Boromo",
    province: "Bale",
    region: "Bankui",
    latitude: 11.7450,
    longitude: -2.9300,
    telephone: "+226 20 52 70 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-banwa",
    nom: "Haut-Commissariat de la Province des Banwa",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Solenzo",
    province: "Banwa",
    region: "Bankui",
    latitude: 12.1830,
    longitude: -4.0400,
    telephone: "+226 20 55 01 16",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-kossi",
    nom: "Haut-Commissariat de la Province du Kossi",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Nouna",
    province: "Kossi",
    region: "Bankui",
    latitude: 12.7320,
    longitude: -3.8620,
    telephone: "+226 20 54 01 09",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-nayala",
    nom: "Haut-Commissariat de la Province du Nayala",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Toma",
    province: "Nayala",
    region: "Bankui",
    latitude: 12.7680,
    longitude: -2.8950,
    telephone: "+226 20 56 01 04",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-bougouriba",
    nom: "Haut-Commissariat de la Province de la Bougouriba",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Diebougou",
    province: "Bougouriba",
    region: "Djoro",
    latitude: 10.9680,
    longitude: -3.2520,
    telephone: "+226 20 87 70 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-ioba",
    nom: "Haut-Commissariat de la Province du Ioba",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Dano",
    province: "Ioba",
    region: "Djoro",
    latitude: 11.1460,
    longitude: -3.0620,
    telephone: "+226 20 87 60 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-noumbiel",
    nom: "Haut-Commissariat de la Province du Noumbiel",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Batie",
    province: "Noumbiel",
    region: "Djoro",
    latitude: 9.8830,
    longitude: -2.9210,
    telephone: "+226 20 87 50 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-poni",
    nom: "Haut-Commissariat de la Province du Poni",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Gaoua",
    province: "Poni",
    region: "Djoro",
    latitude: 10.3252,
    longitude: -3.1770,
    telephone: "+226 20 87 00 11",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-gourma",
    nom: "Haut-Commissariat de la Province du Gourma",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Fada N'Gourma",
    province: "Gourma",
    region: "Goulmou",
    latitude: 12.0610,
    longitude: 0.3510,
    telephone: "+226 24 77 01 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-kompienga",
    nom: "Haut-Commissariat de la Province de la Kompienga",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Pama",
    province: "Kompienga",
    region: "Goulmou",
    latitude: 11.2500,
    longitude: 0.7070,
    telephone: "+226 24 77 50 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-kenedougou",
    nom: "Haut-Commissariat de la Province du Kenedougou",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Orodara",
    province: "Kenedougou",
    region: "Guiriko",
    latitude: 10.9740,
    longitude: -4.9100,
    telephone: "+226 20 97 50 04",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-tuy",
    nom: "Haut-Commissariat de la Province du Tuy",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Hounde",
    province: "Tuy",
    region: "Guiriko",
    latitude: 11.4880,
    longitude: -3.5170,
    telephone: "+226 20 98 50 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-bam",
    nom: "Haut-Commissariat de la Province du Bam",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Kongoussi",
    province: "Bam",
    region: "Kuilse",
    latitude: 13.3260,
    longitude: -1.5340,
    telephone: "+226 25 45 70 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-namentenga",
    nom: "Haut-Commissariat de la Province du Namentenga",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Boulsa",
    province: "Namentenga",
    region: "Kuilse",
    latitude: 12.6660,
    longitude: -0.5750,
    telephone: "+226 25 45 50 02",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-sanmatenga",
    nom: "Haut-Commissariat de la Province du Sanmatenga",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Kaya",
    province: "Sanmatenga",
    region: "Kuilse",
    latitude: 13.0920,
    longitude: -1.0820,
    telephone: "+226 25 45 30 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-oudalan",
    nom: "Haut-Commissariat de la Province de l'Oudalan",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Gorom-Gorom",
    province: "Oudalan",
    region: "Liptako",
    latitude: 14.4430,
    longitude: -0.2360,
    telephone: "+226 24 46 50 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-seno",
    nom: "Haut-Commissariat de la Province du Seno",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Dori",
    province: "Seno",
    region: "Liptako",
    latitude: 14.0360,
    longitude: -0.0350,
    telephone: "+226 24 46 01 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-yagha",
    nom: "Haut-Commissariat de la Province du Yagha",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Sebba",
    province: "Yagha",
    region: "Liptako",
    latitude: 13.4370,
    longitude: 0.5290,
    telephone: "+226 24 46 80 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-boulgou",
    nom: "Haut-Commissariat de la Province du Boulgou",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Tenkodogo",
    province: "Boulgou",
    region: "Nakambe",
    latitude: 11.7810,
    longitude: -0.3710,
    telephone: "+226 25 41 01 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-koulpelogo",
    nom: "Haut-Commissariat de la Province du Koulpelogo",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Ouargaye",
    province: "Koulpelogo",
    region: "Nakambe",
    latitude: 11.5060,
    longitude: 0.0600,
    telephone: "+226 25 41 60 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-kouritenga",
    nom: "Haut-Commissariat de la Province du Kouritenga",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Koupela",
    province: "Kouritenga",
    region: "Nakambe",
    latitude: 12.1790,
    longitude: -0.3530,
    telephone: "+226 25 41 40 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-boulkiemde",
    nom: "Haut-Commissariat de la Province du Boulkiemde",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Koudougou",
    province: "Boulkiemde",
    region: "Nando",
    latitude: 12.2540,
    longitude: -2.3610,
    telephone: "+226 25 44 00 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-sanguie",
    nom: "Haut-Commissariat de la Province du Sanguie",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Reo",
    province: "Sanguie",
    region: "Nando",
    latitude: 12.3210,
    longitude: -2.4730,
    telephone: "+226 25 44 50 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-sissili",
    nom: "Haut-Commissariat de la Province du Sissili",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Leo",
    province: "Sissili",
    region: "Nazinon",
    latitude: 11.0965,
    longitude: -2.0990,
    telephone: "+226 25 40 60 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-ziro",
    nom: "Haut-Commissariat de la Province du Ziro",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Sapouy",
    province: "Ziro",
    region: "Nazinon",
    latitude: 11.5540,
    longitude: -1.7720,
    telephone: "+226 25 40 40 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-nahouri",
    nom: "Haut-Commissariat de la Province du Nahouri",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Po",
    province: "Nahouri",
    region: "Nazinon",
    latitude: 11.1740,
    longitude: -1.1500,
    telephone: "+226 25 40 90 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-bazega",
    nom: "Haut-Commissariat de la Province du Bazega",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Kombissiri",
    province: "Bazega",
    region: "Nazinon",
    latitude: 12.0680,
    longitude: -1.3350,
    telephone: "+226 25 40 50 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-zoundweogo",
    nom: "Haut-Commissariat de la Province du Zoundweogo",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Manga",
    province: "Zoundweogo",
    region: "Nazinon",
    latitude: 11.6640,
    longitude: -1.0730,
    telephone: "+226 25 40 80 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-ganzourgou",
    nom: "Haut-Commissariat de la Province du Ganzourgou",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Zorgho",
    province: "Ganzourgou",
    region: "Oubri",
    latitude: 12.2490,
    longitude: -0.6280,
    telephone: "+226 25 40 70 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-kourweogo",
    nom: "Haut-Commissariat de la Province du Kourweogo",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Bousse",
    province: "Kourweogo",
    region: "Oubri",
    latitude: 12.6640,
    longitude: -1.8940,
    telephone: "+226 25 40 65 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-oubritenga",
    nom: "Haut-Commissariat de la Province de l'Oubritenga",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Ziniare",
    province: "Oubritenga",
    region: "Oubri",
    latitude: 12.5830,
    longitude: -1.2950,
    telephone: "+226 25 40 70 50",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-gnagna",
    nom: "Haut-Commissariat de la Province de la Gnagna",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Bogande",
    province: "Gnagna",
    region: "Sirba",
    latitude: 12.9700,
    longitude: -0.1370,
    telephone: "+226 24 79 01 04",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-komondjari",
    nom: "Haut-Commissariat de la Province de la Komondjari",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Gayeri",
    province: "Komondjari",
    region: "Sirba",
    latitude: 12.6220,
    longitude: 0.5240,
    telephone: "+226 24 79 40 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-soum",
    nom: "Haut-Commissariat de la Province du Soum",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Djibo",
    province: "Soum",
    region: "Soum",
    latitude: 14.1000,
    longitude: -1.6280,
    telephone: "+226 24 53 01 05",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-sourou",
    nom: "Haut-Commissariat de la Province du Sourou",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Tougan",
    province: "Sourou",
    region: "Sourou",
    latitude: 13.0730,
    longitude: -3.0680,
    telephone: "+226 20 53 01 02",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-passore",
    nom: "Haut-Commissariat de la Province du Passore",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Yako",
    province: "Passore",
    region: "Sourou",
    latitude: 12.9610,
    longitude: -2.2620,
    telephone: "+226 25 55 60 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-tapoa",
    nom: "Haut-Commissariat de la Province de la Tapoa",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Diapaga",
    province: "Tapoa",
    region: "Tapoa",
    latitude: 12.0750,
    longitude: 1.7870,
    telephone: "+226 24 79 10 05",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-loroum",
    nom: "Haut-Commissariat de la Province du Loroum",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Titao",
    province: "Loroum",
    region: "Yaadga",
    latitude: 13.7710,
    longitude: -2.0750,
    telephone: "+226 25 55 70 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-yatenga",
    nom: "Haut-Commissariat de la Province du Yatenga",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Ouahigouya",
    province: "Yatenga",
    region: "Yaadga",
    latitude: 13.5830,
    longitude: -2.4210,
    telephone: "+226 25 55 00 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  },
  {
    id: "hc-zandoma",
    nom: "Haut-Commissariat de la Province du Zandoma",
    type: "Haut-Commissariat",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Gourcy",
    province: "Zandoma",
    region: "Yaadga",
    latitude: 13.2060,
    longitude: -2.3570,
    telephone: "+226 25 55 40 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Administration provinciale", "Securite", "Etat civil"],
    titreResponsable: "Haut-Commissaire"
  }
];

export const MAIRIES: MairiePrefecture[] = [
  {
    id: "mairie-ouaga",
    nom: "Mairie Centrale de Ouagadougou",
    type: "Mairie",
    adresse: "Avenue de la Nation",
    quartier: "Centre",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3714,
    longitude: -1.5197,
    telephone: "+226 25 30 69 00",
    email: "mairie@ouagadougou.bf",
    website: "https://www.mairie-ouaga.bf",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Voirie", "Assainissement", "Affaires foncieres", "Mariages", "Permis de construire"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-ouaga-arr1",
    nom: "Mairie d'Arrondissement 1 de Ouagadougou",
    type: "Mairie",
    adresse: "Secteur 2",
    quartier: "Paspanga",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3780,
    longitude: -1.5210,
    telephone: "+226 25 31 63 13",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire d'Arrondissement"
  },
  {
    id: "mairie-ouaga-arr2",
    nom: "Mairie d'Arrondissement 2 de Ouagadougou",
    type: "Mairie",
    adresse: "Secteur 5",
    quartier: "Dapoya",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3750,
    longitude: -1.5330,
    telephone: "+226 25 30 65 25",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire d'Arrondissement"
  },
  {
    id: "mairie-ouaga-arr3",
    nom: "Mairie d'Arrondissement 3 de Ouagadougou",
    type: "Mairie",
    adresse: "Secteur 8",
    quartier: "Gounghin",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3630,
    longitude: -1.5420,
    telephone: "+226 25 34 11 56",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire d'Arrondissement"
  },
  {
    id: "mairie-ouaga-arr4",
    nom: "Mairie d'Arrondissement 4 de Ouagadougou",
    type: "Mairie",
    adresse: "Secteur 15",
    quartier: "Pissy",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3580,
    longitude: -1.5610,
    telephone: "+226 25 36 33 07",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire d'Arrondissement"
  },
  {
    id: "mairie-ouaga-arr5",
    nom: "Mairie d'Arrondissement 5 de Ouagadougou",
    type: "Mairie",
    adresse: "Secteur 18",
    quartier: "Kalgondin",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3520,
    longitude: -1.4970,
    telephone: "+226 25 36 75 95",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire d'Arrondissement"
  },
  {
    id: "mairie-ouaga-arr6",
    nom: "Mairie d'Arrondissement 6 de Ouagadougou",
    type: "Mairie",
    adresse: "Secteur 24",
    quartier: "Somgande",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3860,
    longitude: -1.4880,
    telephone: "+226 25 37 82 72",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire d'Arrondissement"
  },
  {
    id: "mairie-bobo",
    nom: "Mairie de Bobo-Dioulasso",
    type: "Mairie",
    adresse: "Avenue Tiefo Amoro",
    quartier: "Secteur 1",
    ville: "Bobo-Dioulasso",
    province: "Houet",
    region: "Guiriko",
    latitude: 11.1773,
    longitude: -4.2979,
    telephone: "+226 20 97 00 56",
    email: "mairie@bobodioulasso.bf",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Voirie", "Assainissement", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-koudougou",
    nom: "Mairie de Koudougou",
    type: "Mairie",
    adresse: "Avenue de la Revolution",
    quartier: "Secteur 1",
    ville: "Koudougou",
    province: "Boulkiemde",
    region: "Nando",
    latitude: 12.2536,
    longitude: -2.3633,
    telephone: "+226 25 44 00 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Voirie", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-ouahigouya",
    nom: "Mairie de Ouahigouya",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Ouahigouya",
    province: "Yatenga",
    region: "Yaadga",
    latitude: 13.5824,
    longitude: -2.4230,
    telephone: "+226 25 55 01 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-banfora",
    nom: "Mairie de Banfora",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Banfora",
    province: "Comoe",
    region: "Tannounyan",
    latitude: 10.6330,
    longitude: -4.7670,
    telephone: "+226 20 91 01 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-kaya",
    nom: "Mairie de Kaya",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Kaya",
    province: "Sanmatenga",
    region: "Kuilse",
    latitude: 13.0910,
    longitude: -1.0840,
    telephone: "+226 25 45 30 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-tenkodogo",
    nom: "Mairie de Tenkodogo",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Tenkodogo",
    province: "Boulgou",
    region: "Nakambe",
    latitude: 11.7800,
    longitude: -0.3700,
    telephone: "+226 25 41 01 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-fada",
    nom: "Mairie de Fada N'Gourma",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Fada N'Gourma",
    province: "Gourma",
    region: "Goulmou",
    latitude: 12.0600,
    longitude: 0.3500,
    telephone: "+226 24 77 01 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-dedougou",
    nom: "Mairie de Dedougou",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Dedougou",
    province: "Mouhoun",
    region: "Bankui",
    latitude: 12.4633,
    longitude: -3.4608,
    telephone: "+226 20 52 01 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-gaoua",
    nom: "Mairie de Gaoua",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Gaoua",
    province: "Poni",
    region: "Djoro",
    latitude: 10.3250,
    longitude: -3.1750,
    telephone: "+226 20 87 00 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-dori",
    nom: "Mairie de Dori",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Dori",
    province: "Seno",
    region: "Liptako",
    latitude: 14.0354,
    longitude: -0.0340,
    telephone: "+226 24 46 01 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-djibo",
    nom: "Mairie de Djibo",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Djibo",
    province: "Soum",
    region: "Soum",
    latitude: 14.0990,
    longitude: -1.6300,
    telephone: "+226 24 53 01 02",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-leo",
    nom: "Mairie de Leo",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Leo",
    province: "Sissili",
    region: "Nazinon",
    latitude: 11.0960,
    longitude: -2.1010,
    telephone: "+226 25 40 60 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-ziniare",
    nom: "Mairie de Ziniare",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Ziniare",
    province: "Oubritenga",
    region: "Oubri",
    latitude: 12.5827,
    longitude: -1.2968,
    telephone: "+226 25 40 70 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-bogande",
    nom: "Mairie de Bogande",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Bogande",
    province: "Gnagna",
    region: "Sirba",
    latitude: 12.9690,
    longitude: -0.1380,
    telephone: "+226 24 79 01 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-tougan",
    nom: "Mairie de Tougan",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Tougan",
    province: "Sourou",
    region: "Sourou",
    latitude: 13.0720,
    longitude: -3.0700,
    telephone: "+226 20 53 01 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-diapaga",
    nom: "Mairie de Diapaga",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Diapaga",
    province: "Tapoa",
    region: "Tapoa",
    latitude: 12.0740,
    longitude: 1.7880,
    telephone: "+226 24 79 10 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-koupela",
    nom: "Mairie de Koupela",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Koupela",
    province: "Kouritenga",
    region: "Nakambe",
    latitude: 12.1790,
    longitude: -0.3530,
    telephone: "+226 25 41 40 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-reo",
    nom: "Mairie de Reo",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Reo",
    province: "Sanguie",
    region: "Nando",
    latitude: 12.3210,
    longitude: -2.4730,
    telephone: "+226 25 44 50 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-boromo",
    nom: "Mairie de Boromo",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Boromo",
    province: "Bale",
    region: "Bankui",
    latitude: 11.7450,
    longitude: -2.9300,
    telephone: "+226 20 52 70 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-solenzo",
    nom: "Mairie de Solenzo",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Solenzo",
    province: "Banwa",
    region: "Bankui",
    latitude: 12.1830,
    longitude: -4.0400,
    telephone: "+226 20 55 01 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-nouna",
    nom: "Mairie de Nouna",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Nouna",
    province: "Kossi",
    region: "Bankui",
    latitude: 12.7320,
    longitude: -3.8620,
    telephone: "+226 20 54 01 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-toma",
    nom: "Mairie de Toma",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Toma",
    province: "Nayala",
    region: "Bankui",
    latitude: 12.7680,
    longitude: -2.8950,
    telephone: "+226 20 56 01 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-diebougou",
    nom: "Mairie de Diebougou",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Diebougou",
    province: "Bougouriba",
    region: "Djoro",
    latitude: 10.9680,
    longitude: -3.2520,
    telephone: "+226 20 87 70 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-dano",
    nom: "Mairie de Dano",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Dano",
    province: "Ioba",
    region: "Djoro",
    latitude: 11.1460,
    longitude: -3.0620,
    telephone: "+226 20 87 60 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-batie",
    nom: "Mairie de Batie",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Batie",
    province: "Noumbiel",
    region: "Djoro",
    latitude: 9.8830,
    longitude: -2.9210,
    telephone: "+226 20 87 50 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-pama",
    nom: "Mairie de Pama",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Pama",
    province: "Kompienga",
    region: "Goulmou",
    latitude: 11.2500,
    longitude: 0.7070,
    telephone: "+226 24 77 50 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-orodara",
    nom: "Mairie d'Orodara",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Orodara",
    province: "Kenedougou",
    region: "Guiriko",
    latitude: 10.9740,
    longitude: -4.9100,
    telephone: "+226 20 97 50 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-hounde",
    nom: "Mairie de Hounde",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Hounde",
    province: "Tuy",
    region: "Guiriko",
    latitude: 11.4880,
    longitude: -3.5170,
    telephone: "+226 20 98 50 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-kongoussi",
    nom: "Mairie de Kongoussi",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Kongoussi",
    province: "Bam",
    region: "Kuilse",
    latitude: 13.3260,
    longitude: -1.5340,
    telephone: "+226 25 45 70 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-boulsa",
    nom: "Mairie de Boulsa",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Boulsa",
    province: "Namentenga",
    region: "Kuilse",
    latitude: 12.6660,
    longitude: -0.5750,
    telephone: "+226 25 45 50 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-gorom-gorom",
    nom: "Mairie de Gorom-Gorom",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Gorom-Gorom",
    province: "Oudalan",
    region: "Liptako",
    latitude: 14.4430,
    longitude: -0.2360,
    telephone: "+226 24 46 50 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-sebba",
    nom: "Mairie de Sebba",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Sebba",
    province: "Yagha",
    region: "Liptako",
    latitude: 13.4370,
    longitude: 0.5290,
    telephone: "+226 24 46 80 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-ouargaye",
    nom: "Mairie de Ouargaye",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Ouargaye",
    province: "Koulpelogo",
    region: "Nakambe",
    latitude: 11.5060,
    longitude: 0.0600,
    telephone: "+226 25 41 60 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-sapouy",
    nom: "Mairie de Sapouy",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Sapouy",
    province: "Ziro",
    region: "Nazinon",
    latitude: 11.5540,
    longitude: -1.7720,
    telephone: "+226 25 40 40 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-po",
    nom: "Mairie de Po",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Po",
    province: "Nahouri",
    region: "Nazinon",
    latitude: 11.1740,
    longitude: -1.1500,
    telephone: "+226 25 40 90 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-kombissiri",
    nom: "Mairie de Kombissiri",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Kombissiri",
    province: "Bazega",
    region: "Nazinon",
    latitude: 12.0680,
    longitude: -1.3350,
    telephone: "+226 25 40 50 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-manga",
    nom: "Mairie de Manga",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Manga",
    province: "Zoundweogo",
    region: "Nazinon",
    latitude: 11.6640,
    longitude: -1.0730,
    telephone: "+226 25 40 80 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-zorgho",
    nom: "Mairie de Zorgho",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Zorgho",
    province: "Ganzourgou",
    region: "Oubri",
    latitude: 12.2490,
    longitude: -0.6280,
    telephone: "+226 25 40 70 15",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-bousse",
    nom: "Mairie de Bousse",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Bousse",
    province: "Kourweogo",
    region: "Oubri",
    latitude: 12.6640,
    longitude: -1.8940,
    telephone: "+226 25 40 65 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-gayeri",
    nom: "Mairie de Gayeri",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Gayeri",
    province: "Komondjari",
    region: "Sirba",
    latitude: 12.6220,
    longitude: 0.5240,
    telephone: "+226 24 79 40 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-yako",
    nom: "Mairie de Yako",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Yako",
    province: "Passore",
    region: "Sourou",
    latitude: 12.9610,
    longitude: -2.2620,
    telephone: "+226 25 55 60 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-sindou",
    nom: "Mairie de Sindou",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Sindou",
    province: "Leraba",
    region: "Tannounyan",
    latitude: 10.6670,
    longitude: -5.1680,
    telephone: "+226 20 91 40 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-titao",
    nom: "Mairie de Titao",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Titao",
    province: "Loroum",
    region: "Yaadga",
    latitude: 13.7710,
    longitude: -2.0750,
    telephone: "+226 25 55 70 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-gourcy",
    nom: "Mairie de Gourcy",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Gourcy",
    province: "Zandoma",
    region: "Yaadga",
    latitude: 13.2060,
    longitude: -2.3570,
    telephone: "+226 25 55 40 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-garango",
    nom: "Mairie de Garango",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Garango",
    province: "Boulgou",
    region: "Nakambe",
    latitude: 11.8000,
    longitude: -0.5510,
    telephone: "+226 25 41 30 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-pouytenga",
    nom: "Mairie de Pouytenga",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Pouytenga",
    province: "Kouritenga",
    region: "Nakambe",
    latitude: 12.2490,
    longitude: -0.1170,
    telephone: "+226 25 41 45 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-saaba",
    nom: "Mairie de Saaba",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Centre",
    ville: "Saaba",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3590,
    longitude: -1.4060,
    telephone: "+226 25 37 80 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-komsilga",
    nom: "Mairie de Komsilga",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Centre",
    ville: "Komsilga",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.2700,
    longitude: -1.5480,
    telephone: "+226 25 38 60 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-kantchari",
    nom: "Mairie de Kantchari",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Kantchari",
    province: "Tapoa",
    region: "Tapoa",
    latitude: 12.4830,
    longitude: 1.5030,
    telephone: "+226 24 79 12 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  },
  {
    id: "mairie-niangoloko",
    nom: "Mairie de Niangoloko",
    type: "Mairie",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Niangoloko",
    province: "Comoe",
    region: "Tannounyan",
    latitude: 10.2680,
    longitude: -4.9190,
    telephone: "+226 20 91 50 01",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Etat civil", "Urbanisme", "Affaires foncieres", "Mariages"],
    titreResponsable: "Maire"
  }
];

export const PREFECTURES: MairiePrefecture[] = [
  {
    id: "pref-ouaga",
    nom: "Prefecture de Ouagadougou",
    type: "Prefecture",
    adresse: "Avenue de l'Independance",
    quartier: "Centre",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3700,
    longitude: -1.5180,
    telephone: "+226 25 30 67 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives", "Laissez-passer"],
    titreResponsable: "Prefet"
  },
  {
    id: "pref-bobo",
    nom: "Prefecture de Bobo-Dioulasso",
    type: "Prefecture",
    adresse: "Centre administratif",
    quartier: "Secteur 1",
    ville: "Bobo-Dioulasso",
    province: "Houet",
    region: "Guiriko",
    latitude: 11.1780,
    longitude: -4.2950,
    telephone: "+226 20 97 00 30",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives"],
    titreResponsable: "Prefet"
  },
  {
    id: "pref-koudougou",
    nom: "Prefecture de Koudougou",
    type: "Prefecture",
    adresse: "Centre administratif",
    quartier: "Secteur 1",
    ville: "Koudougou",
    province: "Boulkiemde",
    region: "Nando",
    latitude: 12.2550,
    longitude: -2.3600,
    telephone: "+226 25 44 00 15",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives"],
    titreResponsable: "Prefet"
  },
  {
    id: "pref-ouahigouya",
    nom: "Prefecture de Ouahigouya",
    type: "Prefecture",
    adresse: "Centre administratif",
    quartier: "Secteur 1",
    ville: "Ouahigouya",
    province: "Yatenga",
    region: "Yaadga",
    latitude: 13.5840,
    longitude: -2.4200,
    telephone: "+226 25 55 00 30",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives"],
    titreResponsable: "Prefet"
  },
  {
    id: "pref-banfora",
    nom: "Prefecture de Banfora",
    type: "Prefecture",
    adresse: "Centre administratif",
    quartier: "Secteur 1",
    ville: "Banfora",
    province: "Comoe",
    region: "Tannounyan",
    latitude: 10.6340,
    longitude: -4.7650,
    telephone: "+226 20 91 01 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives"],
    titreResponsable: "Prefet"
  },
  {
    id: "pref-kaya",
    nom: "Prefecture de Kaya",
    type: "Prefecture",
    adresse: "Centre administratif",
    quartier: "Secteur 1",
    ville: "Kaya",
    province: "Sanmatenga",
    region: "Kuilse",
    latitude: 13.0930,
    longitude: -1.0830,
    telephone: "+226 25 45 30 15",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives"],
    titreResponsable: "Prefet"
  },
  {
    id: "pref-tenkodogo",
    nom: "Prefecture de Tenkodogo",
    type: "Prefecture",
    adresse: "Centre administratif",
    quartier: "Secteur 1",
    ville: "Tenkodogo",
    province: "Boulgou",
    region: "Nakambe",
    latitude: 11.7820,
    longitude: -0.3690,
    telephone: "+226 25 41 01 15",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives"],
    titreResponsable: "Prefet"
  },
  {
    id: "pref-fada",
    nom: "Prefecture de Fada N'Gourma",
    type: "Prefecture",
    adresse: "Centre administratif",
    quartier: "Secteur 1",
    ville: "Fada N'Gourma",
    province: "Gourma",
    region: "Goulmou",
    latitude: 12.0620,
    longitude: 0.3520,
    telephone: "+226 24 77 01 15",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives"],
    titreResponsable: "Prefet"
  },
  {
    id: "pref-dedougou",
    nom: "Prefecture de Dedougou",
    type: "Prefecture",
    adresse: "Centre administratif",
    quartier: "Secteur 1",
    ville: "Dedougou",
    province: "Mouhoun",
    region: "Bankui",
    latitude: 12.4640,
    longitude: -3.4590,
    telephone: "+226 20 52 01 15",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives"],
    titreResponsable: "Prefet"
  },
  {
    id: "pref-gaoua",
    nom: "Prefecture de Gaoua",
    type: "Prefecture",
    adresse: "Centre administratif",
    quartier: "Secteur 1",
    ville: "Gaoua",
    province: "Poni",
    region: "Djoro",
    latitude: 10.3260,
    longitude: -3.1760,
    telephone: "+226 20 87 00 15",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives"],
    titreResponsable: "Prefet"
  },
  {
    id: "pref-dori",
    nom: "Prefecture de Dori",
    type: "Prefecture",
    adresse: "Centre administratif",
    quartier: "Secteur 1",
    ville: "Dori",
    province: "Seno",
    region: "Liptako",
    latitude: 14.0370,
    longitude: -0.0330,
    telephone: "+226 24 46 01 15",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives"],
    titreResponsable: "Prefet"
  },
  {
    id: "pref-djibo",
    nom: "Prefecture de Djibo",
    type: "Prefecture",
    adresse: "Centre administratif",
    quartier: "Secteur 1",
    ville: "Djibo",
    province: "Soum",
    region: "Soum",
    latitude: 14.1010,
    longitude: -1.6290,
    telephone: "+226 24 53 01 15",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives"],
    titreResponsable: "Prefet"
  },
  {
    id: "pref-leo",
    nom: "Prefecture de Leo",
    type: "Prefecture",
    adresse: "Centre administratif",
    quartier: "Secteur 1",
    ville: "Leo",
    province: "Sissili",
    region: "Nazinon",
    latitude: 11.0970,
    longitude: -2.0990,
    telephone: "+226 25 40 60 15",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives"],
    titreResponsable: "Prefet"
  },
  {
    id: "pref-ziniare",
    nom: "Prefecture de Ziniare",
    type: "Prefecture",
    adresse: "Centre administratif",
    quartier: "Secteur 1",
    ville: "Ziniare",
    province: "Oubritenga",
    region: "Oubri",
    latitude: 12.5840,
    longitude: -1.2960,
    telephone: "+226 25 40 70 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives"],
    titreResponsable: "Prefet"
  },
  {
    id: "pref-bogande",
    nom: "Prefecture de Bogande",
    type: "Prefecture",
    adresse: "Centre administratif",
    quartier: "Secteur 1",
    ville: "Bogande",
    province: "Gnagna",
    region: "Sirba",
    latitude: 12.9710,
    longitude: -0.1370,
    telephone: "+226 24 79 01 15",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives"],
    titreResponsable: "Prefet"
  },
  {
    id: "pref-tougan",
    nom: "Prefecture de Tougan",
    type: "Prefecture",
    adresse: "Centre administratif",
    quartier: "Secteur 1",
    ville: "Tougan",
    province: "Sourou",
    region: "Sourou",
    latitude: 13.0740,
    longitude: -3.0690,
    telephone: "+226 20 53 01 15",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives"],
    titreResponsable: "Prefet"
  },
  {
    id: "pref-diapaga",
    nom: "Prefecture de Diapaga",
    type: "Prefecture",
    adresse: "Centre administratif",
    quartier: "Secteur 1",
    ville: "Diapaga",
    province: "Tapoa",
    region: "Tapoa",
    latitude: 12.0760,
    longitude: 1.7890,
    telephone: "+226 24 79 10 15",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Ordre public", "Securite", "Etat civil", "Autorisations administratives"],
    titreResponsable: "Prefet"
  }
];

export const ALL_INSTITUTIONS: MairiePrefecture[] = [
  ...GOUVERNORATS,
  ...HAUTS_COMMISSARIATS,
  ...MAIRIES,
  ...PREFECTURES
];
