export interface AgenceUtilitaire {
  id: string;
  nom: string;
  societe: "SONABEL" | "ONEA";
  type: "Siege" | "Direction Regionale" | "Agence Commerciale" | "Centre" | "Antenne";
  adresse: string;
  quartier: string;
  ville: string;
  region: string;
  latitude: number;
  longitude: number;
  telephone?: string;
  telephoneSecondaire?: string;
  email?: string;
  website?: string;
  horaires: string;
  services: string[];
  numVert?: string;
  bp?: string;
}

export const SONABEL_AGENCES: AgenceUtilitaire[] = [
  {
    id: "sonabel-siege",
    nom: "SONABEL - Siege Social",
    societe: "SONABEL",
    type: "Siege",
    adresse: "55, Avenue de la Nation",
    quartier: "Koulouba",
    ville: "Ouagadougou",
    region: "Kadiogo",
    latitude: 12.3686,
    longitude: -1.5246,
    telephone: "+226 25 30 61 00",
    telephoneSecondaire: "+226 25 30 61 04",
    email: "info@sonabel.bf",
    website: "https://www.sonabel.bf",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Direction Generale", "Abonnement", "Reclamations", "Facturation", "Branchement"],
    numVert: "80 00 11 30",
    bp: "01 BP 54 Ouagadougou 01"
  },
  {
    id: "sonabel-ouaga-est",
    nom: "SONABEL - Agence Ouagadougou Est",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Avenue Charles de Gaulle",
    quartier: "Zone du Bois",
    ville: "Ouagadougou",
    region: "Kadiogo",
    latitude: 12.3622,
    longitude: -1.4988,
    telephone: "+226 25 37 34 94",
    telephoneSecondaire: "+226 25 37 34 95",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement", "Compteur"],
  },
  {
    id: "sonabel-ouaga-ouest",
    nom: "SONABEL - Agence Ouagadougou Ouest",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Avenue Yatenga",
    quartier: "Pissy",
    ville: "Ouagadougou",
    region: "Kadiogo",
    latitude: 12.3530,
    longitude: -1.5580,
    telephone: "+226 25 34 32 70",
    telephoneSecondaire: "+226 25 34 35 70",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement", "Compteur"],
  },
  {
    id: "sonabel-ouaga-nord",
    nom: "SONABEL - Agence Ouagadougou Nord",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Route de Kaya",
    quartier: "Tampouy",
    ville: "Ouagadougou",
    region: "Kadiogo",
    latitude: 12.4050,
    longitude: -1.5320,
    telephone: "+226 25 36 49 50",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement"],
  },
  {
    id: "sonabel-ouaga-sud",
    nom: "SONABEL - Agence Ouagadougou Sud",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Avenue de la Liberte",
    quartier: "Patte d'Oie",
    ville: "Ouagadougou",
    region: "Kadiogo",
    latitude: 12.3400,
    longitude: -1.5400,
    telephone: "+226 25 38 42 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement"],
  },
  {
    id: "sonabel-bobo",
    nom: "SONABEL - Direction Regionale Bobo-Dioulasso",
    societe: "SONABEL",
    type: "Direction Regionale",
    adresse: "Avenue de la Revolution",
    quartier: "Secteur 1",
    ville: "Bobo-Dioulasso",
    region: "Guiriko",
    latitude: 11.1771,
    longitude: -4.2979,
    telephone: "+226 20 97 60 00",
    telephoneSecondaire: "+226 20 97 21 06",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Direction Regionale", "Abonnement", "Paiement factures", "Reclamations", "Branchement", "Compteur"],
  },
  {
    id: "sonabel-bobo-agence",
    nom: "SONABEL - Agence Commerciale Bobo-Dioulasso",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Rue du Commerce",
    quartier: "Secteur 8",
    ville: "Bobo-Dioulasso",
    region: "Guiriko",
    latitude: 11.1800,
    longitude: -4.3050,
    telephone: "+226 20 97 00 43",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement"],
  },
  {
    id: "sonabel-banfora",
    nom: "SONABEL - Agence Banfora",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Banfora",
    region: "Guiriko",
    latitude: 10.6325,
    longitude: -4.7662,
    telephone: "+226 20 91 00 43",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement"],
  },
  {
    id: "sonabel-ouahigouya",
    nom: "SONABEL - Direction Regionale Ouahigouya",
    societe: "SONABEL",
    type: "Direction Regionale",
    adresse: "Route nationale 2",
    quartier: "Secteur 5",
    ville: "Ouahigouya",
    region: "Yaadga",
    latitude: 13.5828,
    longitude: -2.4213,
    telephone: "+226 24 55 02 26",
    telephoneSecondaire: "+226 24 55 36 60",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h30",
    services: ["Direction Regionale", "Abonnement", "Paiement factures", "Reclamations", "Branchement"],
  },
  {
    id: "sonabel-dedougou",
    nom: "SONABEL - Agence Dedougou",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 2",
    ville: "Dedougou",
    region: "Sourou",
    latitude: 12.4635,
    longitude: -3.4610,
    telephone: "+226 20 52 02 62",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement"],
  },
  {
    id: "sonabel-koudougou",
    nom: "SONABEL - Agence Koudougou",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Avenue du 17 Mai",
    quartier: "Secteur 6",
    ville: "Koudougou",
    region: "Kuilse",
    latitude: 12.2532,
    longitude: -2.3633,
    telephone: "+226 25 44 01 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement"],
  },
  {
    id: "sonabel-kaya",
    nom: "SONABEL - Agence Kaya",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 3",
    ville: "Kaya",
    region: "Nakambe",
    latitude: 13.0910,
    longitude: -1.0840,
    telephone: "+226 40 45 30 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement"],
  },
  {
    id: "sonabel-fada",
    nom: "SONABEL - Agence Fada N'Gourma",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Fada N'Gourma",
    region: "Goulmou",
    latitude: 12.0600,
    longitude: 0.3500,
    telephone: "+226 40 77 00 30",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement"],
  },
  {
    id: "sonabel-tenkodogo",
    nom: "SONABEL - Agence Tenkodogo",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 2",
    ville: "Tenkodogo",
    region: "Oubri",
    latitude: 11.7800,
    longitude: -0.3700,
    telephone: "+226 40 71 01 50",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement"],
  },
  {
    id: "sonabel-koupela",
    nom: "SONABEL - Agence Koupela",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Koupela",
    region: "Oubri",
    latitude: 12.1774,
    longitude: -0.3519,
    telephone: "+226 40 70 01 40",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement"],
  },
  {
    id: "sonabel-ziniari",
    nom: "SONABEL - Agence Ziniaré",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Ziniaré",
    region: "Kadiogo",
    latitude: 12.5833,
    longitude: -1.2992,
    telephone: "+226 25 40 60 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations"],
  },
  {
    id: "sonabel-po",
    nom: "SONABEL - Agence Pô",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Pô",
    region: "Nazinon",
    latitude: 11.1667,
    longitude: -1.1500,
    telephone: "+226 40 79 01 30",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations"],
  },
  {
    id: "sonabel-leo",
    nom: "SONABEL - Agence Leo",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Leo",
    region: "Nazinon",
    latitude: 11.1000,
    longitude: -2.1000,
    telephone: "+226 25 40 80 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations"],
  },
  {
    id: "sonabel-tougan",
    nom: "SONABEL - Agence Tougan",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Tougan",
    region: "Sourou",
    latitude: 13.0730,
    longitude: -3.0690,
    telephone: "+226 20 53 01 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations"],
  },
  {
    id: "sonabel-toma",
    nom: "SONABEL - Agence Toma",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Toma",
    region: "Sourou",
    latitude: 12.7660,
    longitude: -2.8950,
    telephone: "+226 20 53 81 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations"],
  },
  {
    id: "sonabel-pama",
    nom: "SONABEL - Centre Pama",
    societe: "SONABEL",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Pama",
    region: "Tapoa",
    latitude: 11.2500,
    longitude: 0.7000,
    telephone: "+226 40 77 90 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Paiement factures", "Reclamations", "Depannage"],
  },
  {
    id: "sonabel-orodara",
    nom: "SONABEL - Agence Orodara",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Orodara",
    region: "Guiriko",
    latitude: 10.9740,
    longitude: -4.9080,
    telephone: "+226 20 91 70 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations"],
  },
  {
    id: "sonabel-gaoua",
    nom: "SONABEL - Agence Gaoua",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Gaoua",
    region: "Nando",
    latitude: 10.3267,
    longitude: -3.1740,
    telephone: "+226 20 87 00 30",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations"],
  },
  {
    id: "sonabel-diebougou",
    nom: "SONABEL - Centre Diebougou",
    societe: "SONABEL",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Diebougou",
    region: "Nando",
    latitude: 10.9667,
    longitude: -3.2500,
    telephone: "+226 20 87 50 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Paiement factures", "Reclamations", "Depannage"],
  },
  {
    id: "sonabel-dori",
    nom: "SONABEL - Agence Dori",
    societe: "SONABEL",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Dori",
    region: "Liptako",
    latitude: 14.0345,
    longitude: -0.0345,
    telephone: "+226 40 46 01 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Abonnement", "Paiement factures", "Reclamations"],
  },
  {
    id: "sonabel-djibo",
    nom: "SONABEL - Centre Djibo",
    societe: "SONABEL",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Djibo",
    region: "Soum",
    latitude: 14.0990,
    longitude: -1.6300,
    telephone: "+226 40 54 01 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Paiement factures", "Reclamations", "Depannage"],
  },
  {
    id: "sonabel-manga",
    nom: "SONABEL - Centre Manga",
    societe: "SONABEL",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Manga",
    region: "Nazinon",
    latitude: 11.6630,
    longitude: -1.0730,
    telephone: "+226 25 40 70 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Paiement factures", "Reclamations", "Depannage"],
  },
  {
    id: "sonabel-boromo",
    nom: "SONABEL - Centre Boromo",
    societe: "SONABEL",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Boromo",
    region: "Kuilse",
    latitude: 11.7450,
    longitude: -2.9300,
    telephone: "+226 20 54 01 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Paiement factures", "Reclamations", "Depannage"],
  },
  {
    id: "sonabel-reo",
    nom: "SONABEL - Centre Reo",
    societe: "SONABEL",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Reo",
    region: "Kuilse",
    latitude: 12.3200,
    longitude: -2.4700,
    telephone: "+226 25 44 30 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Paiement factures", "Reclamations", "Depannage"],
  },
  {
    id: "sonabel-kombissiri",
    nom: "SONABEL - Centre Kombissiri",
    societe: "SONABEL",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Kombissiri",
    region: "Kadiogo",
    latitude: 12.0650,
    longitude: -1.3350,
    telephone: "+226 25 40 50 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Paiement factures", "Reclamations", "Depannage"],
  },
  {
    id: "sonabel-sapouy",
    nom: "SONABEL - Centre Sapouy",
    societe: "SONABEL",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Sapouy",
    region: "Nazinon",
    latitude: 11.5550,
    longitude: -1.7730,
    telephone: "+226 25 40 90 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Paiement factures", "Reclamations", "Depannage"],
  },
  {
    id: "sonabel-sapone",
    nom: "SONABEL - Centre Sapone",
    societe: "SONABEL",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Sapone",
    region: "Kadiogo",
    latitude: 12.0540,
    longitude: -1.5950,
    telephone: "+226 25 40 40 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Paiement factures", "Reclamations", "Depannage"],
  },
  {
    id: "sonabel-yako",
    nom: "SONABEL - Centre Yako",
    societe: "SONABEL",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Yako",
    region: "Bankui",
    latitude: 12.9570,
    longitude: -2.2610,
    telephone: "+226 25 45 01 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Paiement factures", "Reclamations", "Depannage"],
  },
  {
    id: "sonabel-kongoussi",
    nom: "SONABEL - Centre Kongoussi",
    societe: "SONABEL",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Kongoussi",
    region: "Nakambe",
    latitude: 13.3260,
    longitude: -1.5340,
    telephone: "+226 40 45 60 10",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-17h00",
    services: ["Paiement factures", "Reclamations", "Depannage"],
  },
];

export const ONEA_AGENCES: AgenceUtilitaire[] = [
  {
    id: "onea-siege",
    nom: "ONEA - Siege Social",
    societe: "ONEA",
    type: "Siege",
    adresse: "220, Avenue de l'ONEA, Secteur 17",
    quartier: "Pissy",
    ville: "Ouagadougou",
    region: "Kadiogo",
    latitude: 12.3480,
    longitude: -1.5530,
    telephone: "+226 25 43 19 00",
    telephoneSecondaire: "+226 25 43 19 08",
    email: "oneadg@fasonet.bf",
    website: "https://oneabf.com",
    horaires: "Lun-Ven: 07h30-16h00",
    services: ["Direction Generale", "Abonnement", "Reclamations", "Facturation", "Branchement", "Assainissement"],
    numVert: "80 00 11 11",
    bp: "01 BP 171 Ouagadougou 01"
  },
  {
    id: "onea-ouaga-agence1",
    nom: "ONEA - Agence Ouagadougou Centre",
    societe: "ONEA",
    type: "Agence Commerciale",
    adresse: "Avenue Kwame Nkrumah",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    region: "Kadiogo",
    latitude: 12.3700,
    longitude: -1.5220,
    telephone: "+226 25 31 22 50",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-16h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-ouaga-agence2",
    nom: "ONEA - Agence Ouagadougou Nord",
    societe: "ONEA",
    type: "Agence Commerciale",
    adresse: "Route de Kaya",
    quartier: "Tampouy",
    ville: "Ouagadougou",
    region: "Kadiogo",
    latitude: 12.4020,
    longitude: -1.5280,
    telephone: "+226 25 36 48 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-16h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-ouaga-agence3",
    nom: "ONEA - Agence Ouagadougou Sud",
    societe: "ONEA",
    type: "Agence Commerciale",
    adresse: "Avenue de la Liberte",
    quartier: "Zone 1",
    ville: "Ouagadougou",
    region: "Kadiogo",
    latitude: 12.3350,
    longitude: -1.5150,
    telephone: "+226 25 38 15 30",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-16h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-ouaga-agence-ouest",
    nom: "ONEA - Agence Ouagadougou Ouest",
    societe: "ONEA",
    type: "Agence Commerciale",
    adresse: "Secteur 17",
    quartier: "Pissy",
    ville: "Ouagadougou",
    region: "Kadiogo",
    latitude: 12.3500,
    longitude: -1.5650,
    telephone: "+226 25 34 28 40",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-16h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-bobo",
    nom: "ONEA - Direction Regionale Bobo-Dioulasso",
    societe: "ONEA",
    type: "Direction Regionale",
    adresse: "Rue Alwata Diawara, Porte 2478, Secteur 1",
    quartier: "Secteur 1",
    ville: "Bobo-Dioulasso",
    region: "Guiriko",
    latitude: 11.1780,
    longitude: -4.2950,
    telephone: "+226 20 97 11 11",
    telephoneSecondaire: "+226 20 97 65 65",
    horaires: "Lun-Ven: 07h30-16h00",
    services: ["Direction Regionale", "Abonnement", "Paiement factures", "Reclamations", "Branchement eau", "Assainissement"],
    bp: "01 BP 55 Bobo-Dioulasso 01"
  },
  {
    id: "onea-bobo-agence",
    nom: "ONEA - Agence Commerciale Bobo-Dioulasso",
    societe: "ONEA",
    type: "Agence Commerciale",
    adresse: "Secteur 8",
    quartier: "Secteur 8",
    ville: "Bobo-Dioulasso",
    region: "Guiriko",
    latitude: 11.1750,
    longitude: -4.3020,
    telephone: "+226 20 97 30 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-16h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-banfora",
    nom: "ONEA - Direction Regionale Banfora",
    societe: "ONEA",
    type: "Direction Regionale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Banfora",
    region: "Guiriko",
    latitude: 10.6330,
    longitude: -4.7670,
    telephone: "+226 20 91 01 38",
    telephoneSecondaire: "+226 20 91 07 66",
    horaires: "Lun-Ven: 07h30-16h00",
    services: ["Direction Regionale", "Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-koudougou",
    nom: "ONEA - Direction Regionale Koudougou",
    societe: "ONEA",
    type: "Direction Regionale",
    adresse: "Centre-ville",
    quartier: "Secteur 3",
    ville: "Koudougou",
    region: "Kuilse",
    latitude: 12.2530,
    longitude: -2.3640,
    telephone: "+226 25 44 00 19",
    telephoneSecondaire: "+226 25 44 02 48",
    horaires: "Lun-Ven: 07h30-16h00",
    services: ["Direction Regionale", "Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-koupela",
    nom: "ONEA - Direction Regionale Koupela",
    societe: "ONEA",
    type: "Direction Regionale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Koupela",
    region: "Oubri",
    latitude: 12.1770,
    longitude: -0.3520,
    telephone: "+226 40 70 01 62",
    horaires: "Lun-Ven: 07h30-16h00",
    services: ["Direction Regionale", "Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-kaya",
    nom: "ONEA - Direction Regionale Kaya",
    societe: "ONEA",
    type: "Direction Regionale",
    adresse: "Centre-ville",
    quartier: "Secteur 2",
    ville: "Kaya",
    region: "Nakambe",
    latitude: 13.0900,
    longitude: -1.0830,
    telephone: "+226 40 45 33 27",
    horaires: "Lun-Ven: 07h30-16h00",
    services: ["Direction Regionale", "Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-ouahigouya",
    nom: "ONEA - Direction Regionale Ouahigouya",
    societe: "ONEA",
    type: "Direction Regionale",
    adresse: "Centre-ville",
    quartier: "Secteur 4",
    ville: "Ouahigouya",
    region: "Yaadga",
    latitude: 13.5830,
    longitude: -2.4210,
    telephone: "+226 40 55 00 57",
    horaires: "Lun-Ven: 07h30-16h00",
    services: ["Direction Regionale", "Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-fada",
    nom: "ONEA - Direction Regionale Fada N'Gourma",
    societe: "ONEA",
    type: "Direction Regionale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Fada N'Gourma",
    region: "Goulmou",
    latitude: 12.0610,
    longitude: 0.3510,
    telephone: "+226 40 77 01 70",
    horaires: "Lun-Ven: 07h30-16h00",
    services: ["Direction Regionale", "Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-po",
    nom: "ONEA - Direction Regionale Pô",
    societe: "ONEA",
    type: "Direction Regionale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Pô",
    region: "Nazinon",
    latitude: 11.1670,
    longitude: -1.1490,
    telephone: "+226 25 40 31 55",
    horaires: "Lun-Ven: 07h30-16h00",
    services: ["Direction Regionale", "Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-dedougou",
    nom: "ONEA - Agence Dedougou",
    societe: "ONEA",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 2",
    ville: "Dedougou",
    region: "Sourou",
    latitude: 12.4640,
    longitude: -3.4620,
    telephone: "+226 20 52 05 30",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-16h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-tenkodogo",
    nom: "ONEA - Agence Tenkodogo",
    societe: "ONEA",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Tenkodogo",
    region: "Oubri",
    latitude: 11.7810,
    longitude: -0.3710,
    telephone: "+226 40 71 02 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-16h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-ziniari",
    nom: "ONEA - Agence Ziniaré",
    societe: "ONEA",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Ziniaré",
    region: "Kadiogo",
    latitude: 12.5840,
    longitude: -1.2990,
    telephone: "+226 25 40 61 30",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-16h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-dori",
    nom: "ONEA - Agence Dori",
    societe: "ONEA",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Dori",
    region: "Liptako",
    latitude: 14.0350,
    longitude: -0.0350,
    telephone: "+226 40 46 02 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-16h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-gaoua",
    nom: "ONEA - Agence Gaoua",
    societe: "ONEA",
    type: "Agence Commerciale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Gaoua",
    region: "Nando",
    latitude: 10.3270,
    longitude: -3.1750,
    telephone: "+226 20 87 01 40",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-16h00",
    services: ["Abonnement", "Paiement factures", "Reclamations", "Branchement eau"],
  },
  {
    id: "onea-manga",
    nom: "ONEA - Centre Manga",
    societe: "ONEA",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Manga",
    region: "Nazinon",
    latitude: 11.6640,
    longitude: -1.0740,
    telephone: "+226 25 40 71 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-16h00",
    services: ["Paiement factures", "Reclamations", "Depannage eau"],
  },
  {
    id: "onea-orodara",
    nom: "ONEA - Centre Orodara",
    societe: "ONEA",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Orodara",
    region: "Guiriko",
    latitude: 10.9750,
    longitude: -4.9090,
    telephone: "+226 20 91 71 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-16h00",
    services: ["Paiement factures", "Reclamations", "Depannage eau"],
  },
  {
    id: "onea-boromo",
    nom: "ONEA - Centre Boromo",
    societe: "ONEA",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Boromo",
    region: "Kuilse",
    latitude: 11.7460,
    longitude: -2.9310,
    telephone: "+226 20 54 02 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-16h00",
    services: ["Paiement factures", "Reclamations", "Depannage eau"],
  },
  {
    id: "onea-yako",
    nom: "ONEA - Centre Yako",
    societe: "ONEA",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Yako",
    region: "Bankui",
    latitude: 12.9580,
    longitude: -2.2620,
    telephone: "+226 25 45 02 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-16h00",
    services: ["Paiement factures", "Reclamations", "Depannage eau"],
  },
  {
    id: "onea-kombissiri",
    nom: "ONEA - Centre Kombissiri",
    societe: "ONEA",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Kombissiri",
    region: "Kadiogo",
    latitude: 12.0660,
    longitude: -1.3360,
    telephone: "+226 25 40 51 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-16h00",
    services: ["Paiement factures", "Reclamations", "Depannage eau"],
  },
  {
    id: "onea-kongoussi",
    nom: "ONEA - Centre Kongoussi",
    societe: "ONEA",
    type: "Centre",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Kongoussi",
    region: "Nakambe",
    latitude: 13.3270,
    longitude: -1.5350,
    telephone: "+226 40 45 61 20",
    horaires: "Lun-Ven: 07h30-12h30 / 13h00-16h00",
    services: ["Paiement factures", "Reclamations", "Depannage eau"],
  },
];

export const ALL_AGENCES = [...SONABEL_AGENCES, ...ONEA_AGENCES];
