export interface AgenceTelephonie {
  id: string;
  nom: string;
  operateur: "Orange Burkina" | "Moov Africa" | "Telecel Faso";
  type: "Agence Principale" | "Boutique" | "Point de Vente" | "Direction" | "Centre de Service";
  adresse: string;
  quartier: string;
  ville: string;
  province: string;
  region: string;
  latitude: number;
  longitude: number;
  telephone?: string;
  telephoneSecondaire?: string;
  email?: string;
  website?: string;
  horaires: string;
  services: string[];
}

export const ORANGE_AGENCES: AgenceTelephonie[] = [
  {
    id: "orange-siege",
    nom: "Orange Burkina - Siege Social",
    operateur: "Orange Burkina",
    type: "Direction",
    adresse: "Avenue de la Nation",
    quartier: "Koulouba",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3720,
    longitude: -1.5150,
    telephone: "+226 25 33 40 00",
    email: "contact@orange.bf",
    website: "https://www.orange.bf",
    horaires: "Lun-Ven: 07h30-17h30",
    services: ["Direction generale", "Service client", "Partenariats", "Entreprises"]
  },
  {
    id: "orange-ouaga-kwame",
    nom: "Boutique Orange - Avenue Kwame N'Krumah",
    operateur: "Orange Burkina",
    type: "Boutique",
    adresse: "Avenue Kwame N'Krumah",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3680,
    longitude: -1.5220,
    telephone: "+226 25 33 40 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money", "Internet fixe", "Smartphones", "SAV"]
  },
  {
    id: "orange-ouaga-2000",
    nom: "Boutique Orange - Ouaga 2000",
    operateur: "Orange Burkina",
    type: "Boutique",
    adresse: "Boulevard des Heros Nationaux",
    quartier: "Ouaga 2000",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3450,
    longitude: -1.5130,
    telephone: "+226 25 33 40 12",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money", "Internet fixe", "Smartphones"]
  },
  {
    id: "orange-ouaga-zad",
    nom: "Boutique Orange - Zone d'Activites Diverses",
    operateur: "Orange Burkina",
    type: "Boutique",
    adresse: "Zone d'Activites Diverses",
    quartier: "ZAD",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3600,
    longitude: -1.5000,
    telephone: "+226 25 33 40 14",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money", "Smartphones"]
  },
  {
    id: "orange-ouaga-tampouy",
    nom: "Boutique Orange - Tampouy",
    operateur: "Orange Burkina",
    type: "Boutique",
    adresse: "Tampouy",
    quartier: "Tampouy",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3950,
    longitude: -1.5350,
    telephone: "+226 25 33 40 16",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money", "Smartphones"]
  },
  {
    id: "orange-ouaga-pissy",
    nom: "Boutique Orange - Pissy",
    operateur: "Orange Burkina",
    type: "Boutique",
    adresse: "Secteur 17",
    quartier: "Pissy",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3520,
    longitude: -1.5600,
    telephone: "+226 25 33 40 18",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money"]
  },
  {
    id: "orange-ouaga-gounghin",
    nom: "Boutique Orange - Gounghin",
    operateur: "Orange Burkina",
    type: "Boutique",
    adresse: "Gounghin",
    quartier: "Gounghin",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3640,
    longitude: -1.5430,
    telephone: "+226 25 33 40 20",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money"]
  },
  {
    id: "orange-bobo-centre",
    nom: "Agence Orange - Bobo-Dioulasso Centre",
    operateur: "Orange Burkina",
    type: "Agence Principale",
    adresse: "Avenue de la Revolution",
    quartier: "Secteur 1",
    ville: "Bobo-Dioulasso",
    province: "Houet",
    region: "Guiriko",
    latitude: 11.1773,
    longitude: -4.2920,
    telephone: "+226 20 97 40 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money", "Internet fixe", "Smartphones", "SAV", "Entreprises"]
  },
  {
    id: "orange-bobo-sarfalao",
    nom: "Boutique Orange - Sarfalao",
    operateur: "Orange Burkina",
    type: "Boutique",
    adresse: "Sarfalao",
    quartier: "Sarfalao",
    ville: "Bobo-Dioulasso",
    province: "Houet",
    region: "Guiriko",
    latitude: 11.1850,
    longitude: -4.3050,
    telephone: "+226 20 97 40 12",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money", "Smartphones"]
  },
  {
    id: "orange-koudougou",
    nom: "Agence Orange - Koudougou",
    operateur: "Orange Burkina",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Koudougou",
    province: "Boulkiemde",
    region: "Nando",
    latitude: 12.2536,
    longitude: -2.3633,
    telephone: "+226 25 44 40 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money", "Internet fixe", "Smartphones"]
  },
  {
    id: "orange-ouahigouya",
    nom: "Agence Orange - Ouahigouya",
    operateur: "Orange Burkina",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Ouahigouya",
    province: "Yatenga",
    region: "Yaadga",
    latitude: 13.5824,
    longitude: -2.4230,
    telephone: "+226 25 55 40 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money", "Smartphones"]
  },
  {
    id: "orange-banfora",
    nom: "Agence Orange - Banfora",
    operateur: "Orange Burkina",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Banfora",
    province: "Comoe",
    region: "Tannounyan",
    latitude: 10.6330,
    longitude: -4.7670,
    telephone: "+226 20 91 40 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money", "Smartphones"]
  },
  {
    id: "orange-kaya",
    nom: "Agence Orange - Kaya",
    operateur: "Orange Burkina",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Kaya",
    province: "Sanmatenga",
    region: "Kuilse",
    latitude: 13.0910,
    longitude: -1.0840,
    telephone: "+226 25 45 40 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money", "Smartphones"]
  },
  {
    id: "orange-fada",
    nom: "Agence Orange - Fada N'Gourma",
    operateur: "Orange Burkina",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Fada N'Gourma",
    province: "Gourma",
    region: "Goulmou",
    latitude: 12.0600,
    longitude: 0.3500,
    telephone: "+226 24 77 40 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money", "Smartphones"]
  },
  {
    id: "orange-tenkodogo",
    nom: "Agence Orange - Tenkodogo",
    operateur: "Orange Burkina",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Tenkodogo",
    province: "Boulgou",
    region: "Nakambe",
    latitude: 11.7800,
    longitude: -0.3700,
    telephone: "+226 25 41 40 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money"]
  },
  {
    id: "orange-dedougou",
    nom: "Agence Orange - Dedougou",
    operateur: "Orange Burkina",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Dedougou",
    province: "Mouhoun",
    region: "Bankui",
    latitude: 12.4633,
    longitude: -3.4608,
    telephone: "+226 20 52 40 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money"]
  },
  {
    id: "orange-dori",
    nom: "Agence Orange - Dori",
    operateur: "Orange Burkina",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Dori",
    province: "Seno",
    region: "Liptako",
    latitude: 14.0354,
    longitude: -0.0340,
    telephone: "+226 24 46 40 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money"]
  },
  {
    id: "orange-gaoua",
    nom: "Agence Orange - Gaoua",
    operateur: "Orange Burkina",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Gaoua",
    province: "Poni",
    region: "Djoro",
    latitude: 10.3250,
    longitude: -3.1750,
    telephone: "+226 20 87 40 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money"]
  },
  {
    id: "orange-koupela",
    nom: "Agence Orange - Koupela",
    operateur: "Orange Burkina",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Koupela",
    province: "Kouritenga",
    region: "Nakambe",
    latitude: 12.1790,
    longitude: -0.3530,
    telephone: "+226 25 41 45 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money"]
  },
  {
    id: "orange-orodara",
    nom: "Boutique Orange - Orodara",
    operateur: "Orange Burkina",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Orodara",
    province: "Kenedougou",
    region: "Guiriko",
    latitude: 10.9740,
    longitude: -4.9100,
    telephone: "+226 20 97 55 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money"]
  },
  {
    id: "orange-pouytenga",
    nom: "Boutique Orange - Pouytenga",
    operateur: "Orange Burkina",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Pouytenga",
    province: "Kouritenga",
    region: "Nakambe",
    latitude: 12.2490,
    longitude: -0.1170,
    telephone: "+226 25 41 47 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money"]
  },
  {
    id: "orange-leo",
    nom: "Boutique Orange - Leo",
    operateur: "Orange Burkina",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Leo",
    province: "Sissili",
    region: "Nazinon",
    latitude: 11.0960,
    longitude: -2.1010,
    telephone: "+226 25 40 68 10",
    horaires: "Lun-Sam: 08h00-17h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money"]
  },
  {
    id: "orange-kongoussi",
    nom: "Boutique Orange - Kongoussi",
    operateur: "Orange Burkina",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Kongoussi",
    province: "Bam",
    region: "Kuilse",
    latitude: 13.3260,
    longitude: -1.5340,
    telephone: "+226 25 45 75 10",
    horaires: "Lun-Sam: 08h00-17h00",
    services: ["Abonnements", "SIM", "Recharges", "Orange Money"]
  }
];

export const MOOV_AGENCES: AgenceTelephonie[] = [
  {
    id: "moov-siege",
    nom: "Moov Africa - Siege Social",
    operateur: "Moov Africa",
    type: "Direction",
    adresse: "Avenue de la Nation",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3690,
    longitude: -1.5230,
    telephone: "+226 25 33 06 06",
    email: "contact@moov-africa.bf",
    website: "https://www.moov-africa.bf",
    horaires: "Lun-Ven: 07h30-17h30",
    services: ["Direction generale", "Service client", "Partenariats", "Entreprises"]
  },
  {
    id: "moov-ouaga-kwame",
    nom: "Agence Moov Africa - Kwame N'Krumah",
    operateur: "Moov Africa",
    type: "Agence Principale",
    adresse: "Avenue Kwame N'Krumah",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3670,
    longitude: -1.5200,
    telephone: "+226 25 33 06 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money", "Internet", "Smartphones", "SAV"]
  },
  {
    id: "moov-ouaga-2000",
    nom: "Boutique Moov Africa - Ouaga 2000",
    operateur: "Moov Africa",
    type: "Boutique",
    adresse: "Ouaga 2000",
    quartier: "Ouaga 2000",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3440,
    longitude: -1.5110,
    telephone: "+226 25 33 06 12",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money", "Smartphones"]
  },
  {
    id: "moov-ouaga-zad",
    nom: "Boutique Moov Africa - ZAD",
    operateur: "Moov Africa",
    type: "Boutique",
    adresse: "Zone d'Activites Diverses",
    quartier: "ZAD",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3580,
    longitude: -1.4980,
    telephone: "+226 25 33 06 14",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money", "Smartphones"]
  },
  {
    id: "moov-ouaga-dassasgho",
    nom: "Boutique Moov Africa - Dassasgho",
    operateur: "Moov Africa",
    type: "Boutique",
    adresse: "Dassasgho",
    quartier: "Dassasgho",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3800,
    longitude: -1.4920,
    telephone: "+226 25 33 06 16",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money"]
  },
  {
    id: "moov-ouaga-tampouy",
    nom: "Boutique Moov Africa - Tampouy",
    operateur: "Moov Africa",
    type: "Boutique",
    adresse: "Tampouy",
    quartier: "Tampouy",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3960,
    longitude: -1.5380,
    telephone: "+226 25 33 06 18",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money"]
  },
  {
    id: "moov-ouaga-cissin",
    nom: "Boutique Moov Africa - Cissin",
    operateur: "Moov Africa",
    type: "Boutique",
    adresse: "Cissin",
    quartier: "Cissin",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3420,
    longitude: -1.5300,
    telephone: "+226 25 33 06 20",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money"]
  },
  {
    id: "moov-bobo-centre",
    nom: "Agence Moov Africa - Bobo-Dioulasso",
    operateur: "Moov Africa",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Bobo-Dioulasso",
    province: "Houet",
    region: "Guiriko",
    latitude: 11.1780,
    longitude: -4.2950,
    telephone: "+226 20 97 06 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money", "Internet", "Smartphones", "SAV"]
  },
  {
    id: "moov-bobo-accart",
    nom: "Boutique Moov Africa - Accart-Ville",
    operateur: "Moov Africa",
    type: "Boutique",
    adresse: "Accart-Ville",
    quartier: "Accart-Ville",
    ville: "Bobo-Dioulasso",
    province: "Houet",
    region: "Guiriko",
    latitude: 11.1810,
    longitude: -4.2880,
    telephone: "+226 20 97 06 12",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money"]
  },
  {
    id: "moov-koudougou",
    nom: "Agence Moov Africa - Koudougou",
    operateur: "Moov Africa",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Koudougou",
    province: "Boulkiemde",
    region: "Nando",
    latitude: 12.2530,
    longitude: -2.3610,
    telephone: "+226 25 44 06 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money", "Smartphones"]
  },
  {
    id: "moov-ouahigouya",
    nom: "Agence Moov Africa - Ouahigouya",
    operateur: "Moov Africa",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Ouahigouya",
    province: "Yatenga",
    region: "Yaadga",
    latitude: 13.5830,
    longitude: -2.4200,
    telephone: "+226 25 55 06 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money", "Smartphones"]
  },
  {
    id: "moov-banfora",
    nom: "Agence Moov Africa - Banfora",
    operateur: "Moov Africa",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Banfora",
    province: "Comoe",
    region: "Tannounyan",
    latitude: 10.6340,
    longitude: -4.7680,
    telephone: "+226 20 91 06 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money"]
  },
  {
    id: "moov-kaya",
    nom: "Agence Moov Africa - Kaya",
    operateur: "Moov Africa",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Kaya",
    province: "Sanmatenga",
    region: "Kuilse",
    latitude: 13.0920,
    longitude: -1.0850,
    telephone: "+226 25 45 06 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money"]
  },
  {
    id: "moov-fada",
    nom: "Agence Moov Africa - Fada N'Gourma",
    operateur: "Moov Africa",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Fada N'Gourma",
    province: "Gourma",
    region: "Goulmou",
    latitude: 12.0610,
    longitude: 0.3520,
    telephone: "+226 24 77 06 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money"]
  },
  {
    id: "moov-tenkodogo",
    nom: "Agence Moov Africa - Tenkodogo",
    operateur: "Moov Africa",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Tenkodogo",
    province: "Boulgou",
    region: "Nakambe",
    latitude: 11.7810,
    longitude: -0.3710,
    telephone: "+226 25 41 06 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money"]
  },
  {
    id: "moov-dedougou",
    nom: "Agence Moov Africa - Dedougou",
    operateur: "Moov Africa",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Dedougou",
    province: "Mouhoun",
    region: "Bankui",
    latitude: 12.4640,
    longitude: -3.4610,
    telephone: "+226 20 52 06 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money"]
  },
  {
    id: "moov-dori",
    nom: "Boutique Moov Africa - Dori",
    operateur: "Moov Africa",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Dori",
    province: "Seno",
    region: "Liptako",
    latitude: 14.0360,
    longitude: -0.0350,
    telephone: "+226 24 46 06 10",
    horaires: "Lun-Sam: 08h00-17h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money"]
  },
  {
    id: "moov-gaoua",
    nom: "Boutique Moov Africa - Gaoua",
    operateur: "Moov Africa",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Gaoua",
    province: "Poni",
    region: "Djoro",
    latitude: 10.3260,
    longitude: -3.1760,
    telephone: "+226 20 87 06 10",
    horaires: "Lun-Sam: 08h00-17h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money"]
  },
  {
    id: "moov-koupela",
    nom: "Boutique Moov Africa - Koupela",
    operateur: "Moov Africa",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Koupela",
    province: "Kouritenga",
    region: "Nakambe",
    latitude: 12.1800,
    longitude: -0.3540,
    telephone: "+226 25 41 46 10",
    horaires: "Lun-Sam: 08h00-17h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money"]
  },
  {
    id: "moov-ziniare",
    nom: "Boutique Moov Africa - Ziniare",
    operateur: "Moov Africa",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Ziniare",
    province: "Oubritenga",
    region: "Oubri",
    latitude: 12.5830,
    longitude: -1.2960,
    telephone: "+226 25 40 76 10",
    horaires: "Lun-Sam: 08h00-17h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money"]
  },
  {
    id: "moov-po",
    nom: "Boutique Moov Africa - Po",
    operateur: "Moov Africa",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Po",
    province: "Nahouri",
    region: "Nazinon",
    latitude: 11.1740,
    longitude: -1.1490,
    telephone: "+226 25 40 96 10",
    horaires: "Lun-Sam: 08h00-17h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money"]
  },
  {
    id: "moov-hounde",
    nom: "Boutique Moov Africa - Hounde",
    operateur: "Moov Africa",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Hounde",
    province: "Tuy",
    region: "Guiriko",
    latitude: 11.4880,
    longitude: -3.5160,
    telephone: "+226 20 98 56 10",
    horaires: "Lun-Sam: 08h00-17h00",
    services: ["Abonnements", "SIM", "Recharges", "Moov Money"]
  }
];

export const TELECEL_AGENCES: AgenceTelephonie[] = [
  {
    id: "telecel-siege",
    nom: "Telecel Faso - Siege Social",
    operateur: "Telecel Faso",
    type: "Direction",
    adresse: "Avenue de la Resistance du 17 Mai",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3660,
    longitude: -1.5180,
    telephone: "+226 25 33 28 28",
    email: "contact@telecelfaso.bf",
    website: "https://www.telecelfaso.bf",
    horaires: "Lun-Ven: 07h30-17h30",
    services: ["Direction generale", "Service client", "Partenariats", "Entreprises"]
  },
  {
    id: "telecel-ouaga-kwame",
    nom: "Agence Telecel - Kwame N'Krumah",
    operateur: "Telecel Faso",
    type: "Agence Principale",
    adresse: "Avenue Kwame N'Krumah",
    quartier: "Centre-ville",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3665,
    longitude: -1.5210,
    telephone: "+226 25 33 28 30",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Telecel Cash", "Internet", "Smartphones", "SAV"]
  },
  {
    id: "telecel-ouaga-2000",
    nom: "Boutique Telecel - Ouaga 2000",
    operateur: "Telecel Faso",
    type: "Boutique",
    adresse: "Ouaga 2000",
    quartier: "Ouaga 2000",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3460,
    longitude: -1.5140,
    telephone: "+226 25 33 28 32",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Telecel Cash", "Smartphones"]
  },
  {
    id: "telecel-ouaga-zad",
    nom: "Boutique Telecel - ZAD",
    operateur: "Telecel Faso",
    type: "Boutique",
    adresse: "Zone d'Activites Diverses",
    quartier: "ZAD",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3590,
    longitude: -1.4990,
    telephone: "+226 25 33 28 34",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Telecel Cash"]
  },
  {
    id: "telecel-ouaga-kossodo",
    nom: "Boutique Telecel - Kossodo",
    operateur: "Telecel Faso",
    type: "Boutique",
    adresse: "Kossodo",
    quartier: "Kossodo",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.4010,
    longitude: -1.5020,
    telephone: "+226 25 33 28 36",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Telecel Cash"]
  },
  {
    id: "telecel-ouaga-somgande",
    nom: "Boutique Telecel - Somgande",
    operateur: "Telecel Faso",
    type: "Boutique",
    adresse: "Somgande",
    quartier: "Somgande",
    ville: "Ouagadougou",
    province: "Kadiogo",
    region: "Kadiogo",
    latitude: 12.3870,
    longitude: -1.4870,
    telephone: "+226 25 33 28 38",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Telecel Cash"]
  },
  {
    id: "telecel-bobo",
    nom: "Agence Telecel - Bobo-Dioulasso",
    operateur: "Telecel Faso",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Bobo-Dioulasso",
    province: "Houet",
    region: "Guiriko",
    latitude: 11.1790,
    longitude: -4.2960,
    telephone: "+226 20 97 28 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Telecel Cash", "Internet", "Smartphones", "SAV"]
  },
  {
    id: "telecel-koudougou",
    nom: "Agence Telecel - Koudougou",
    operateur: "Telecel Faso",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Koudougou",
    province: "Boulkiemde",
    region: "Nando",
    latitude: 12.2540,
    longitude: -2.3620,
    telephone: "+226 25 44 28 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Telecel Cash", "Smartphones"]
  },
  {
    id: "telecel-ouahigouya",
    nom: "Agence Telecel - Ouahigouya",
    operateur: "Telecel Faso",
    type: "Agence Principale",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Ouahigouya",
    province: "Yatenga",
    region: "Yaadga",
    latitude: 13.5840,
    longitude: -2.4220,
    telephone: "+226 25 55 28 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Telecel Cash"]
  },
  {
    id: "telecel-banfora",
    nom: "Boutique Telecel - Banfora",
    operateur: "Telecel Faso",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Banfora",
    province: "Comoe",
    region: "Tannounyan",
    latitude: 10.6350,
    longitude: -4.7690,
    telephone: "+226 20 91 28 10",
    horaires: "Lun-Sam: 08h00-18h00",
    services: ["Abonnements", "SIM", "Recharges", "Telecel Cash"]
  },
  {
    id: "telecel-kaya",
    nom: "Boutique Telecel - Kaya",
    operateur: "Telecel Faso",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Kaya",
    province: "Sanmatenga",
    region: "Kuilse",
    latitude: 13.0930,
    longitude: -1.0860,
    telephone: "+226 25 45 28 10",
    horaires: "Lun-Sam: 08h00-17h00",
    services: ["Abonnements", "SIM", "Recharges", "Telecel Cash"]
  },
  {
    id: "telecel-fada",
    nom: "Boutique Telecel - Fada N'Gourma",
    operateur: "Telecel Faso",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Fada N'Gourma",
    province: "Gourma",
    region: "Goulmou",
    latitude: 12.0620,
    longitude: 0.3530,
    telephone: "+226 24 77 28 10",
    horaires: "Lun-Sam: 08h00-17h00",
    services: ["Abonnements", "SIM", "Recharges", "Telecel Cash"]
  },
  {
    id: "telecel-dedougou",
    nom: "Boutique Telecel - Dedougou",
    operateur: "Telecel Faso",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Dedougou",
    province: "Mouhoun",
    region: "Bankui",
    latitude: 12.4650,
    longitude: -3.4600,
    telephone: "+226 20 52 28 10",
    horaires: "Lun-Sam: 08h00-17h00",
    services: ["Abonnements", "SIM", "Recharges", "Telecel Cash"]
  },
  {
    id: "telecel-tenkodogo",
    nom: "Boutique Telecel - Tenkodogo",
    operateur: "Telecel Faso",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Tenkodogo",
    province: "Boulgou",
    region: "Nakambe",
    latitude: 11.7820,
    longitude: -0.3720,
    telephone: "+226 25 41 28 10",
    horaires: "Lun-Sam: 08h00-17h00",
    services: ["Abonnements", "SIM", "Recharges", "Telecel Cash"]
  },
  {
    id: "telecel-dori",
    nom: "Boutique Telecel - Dori",
    operateur: "Telecel Faso",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Dori",
    province: "Seno",
    region: "Liptako",
    latitude: 14.0370,
    longitude: -0.0360,
    telephone: "+226 24 46 28 10",
    horaires: "Lun-Sam: 08h00-17h00",
    services: ["Abonnements", "SIM", "Recharges", "Telecel Cash"]
  },
  {
    id: "telecel-gaoua",
    nom: "Boutique Telecel - Gaoua",
    operateur: "Telecel Faso",
    type: "Boutique",
    adresse: "Centre-ville",
    quartier: "Secteur 1",
    ville: "Gaoua",
    province: "Poni",
    region: "Djoro",
    latitude: 10.3270,
    longitude: -3.1770,
    telephone: "+226 20 87 28 10",
    horaires: "Lun-Sam: 08h00-17h00",
    services: ["Abonnements", "SIM", "Recharges", "Telecel Cash"]
  }
];

export const ALL_AGENCES_TELEPHONIE: AgenceTelephonie[] = [
  ...ORANGE_AGENCES,
  ...MOOV_AGENCES,
  ...TELECEL_AGENCES
];
